// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"bytes"
	"database/sql/driver"
	"encoding/json"
	"strconv"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/null/v8/convert"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]any

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("sqlboiler: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

type TriggerType string

// Enum values for TriggerType
const (
	TriggerTypeMANUAL        TriggerType = "MANUAL"
	TriggerTypeSCHEDULED     TriggerType = "SCHEDULED"
	TriggerTypePROJECT_EVENT TriggerType = "PROJECT_EVENT"
	TriggerTypeCRISIS_EVENT  TriggerType = "CRISIS_EVENT"
	TriggerTypeWEBHOOK_PUSH  TriggerType = "WEBHOOK_PUSH"
)

func AllTriggerType() []TriggerType {
	return []TriggerType{
		TriggerTypeMANUAL,
		TriggerTypeSCHEDULED,
		TriggerTypePROJECT_EVENT,
		TriggerTypeCRISIS_EVENT,
		TriggerTypeWEBHOOK_PUSH,
	}
}

func (e TriggerType) IsValid() error {
	switch e {
	case TriggerTypeMANUAL, TriggerTypeSCHEDULED, TriggerTypePROJECT_EVENT, TriggerTypeCRISIS_EVENT, TriggerTypeWEBHOOK_PUSH:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e TriggerType) String() string {
	return string(e)
}

func (e TriggerType) Ordinal() int {
	switch e {
	case TriggerTypeMANUAL:
		return 0
	case TriggerTypeSCHEDULED:
		return 1
	case TriggerTypePROJECT_EVENT:
		return 2
	case TriggerTypeCRISIS_EVENT:
		return 3
	case TriggerTypeWEBHOOK_PUSH:
		return 4

	default:
		panic(errors.New("enum is not valid"))
	}
}

type CrawlMode string

// Enum values for CrawlMode
const (
	CrawlModeSLEEP  CrawlMode = "SLEEP"
	CrawlModeNORMAL CrawlMode = "NORMAL"
	CrawlModeCRISIS CrawlMode = "CRISIS"
)

func AllCrawlMode() []CrawlMode {
	return []CrawlMode{
		CrawlModeSLEEP,
		CrawlModeNORMAL,
		CrawlModeCRISIS,
	}
}

func (e CrawlMode) IsValid() error {
	switch e {
	case CrawlModeSLEEP, CrawlModeNORMAL, CrawlModeCRISIS:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e CrawlMode) String() string {
	return string(e)
}

func (e CrawlMode) Ordinal() int {
	switch e {
	case CrawlModeSLEEP:
		return 0
	case CrawlModeNORMAL:
		return 1
	case CrawlModeCRISIS:
		return 2

	default:
		panic(errors.New("enum is not valid"))
	}
}

type TargetType string

// Enum values for TargetType
const (
	TargetTypeKEYWORD  TargetType = "KEYWORD"
	TargetTypePROFILE  TargetType = "PROFILE"
	TargetTypePOST_URL TargetType = "POST_URL"
)

func AllTargetType() []TargetType {
	return []TargetType{
		TargetTypeKEYWORD,
		TargetTypePROFILE,
		TargetTypePOST_URL,
	}
}

func (e TargetType) IsValid() error {
	switch e {
	case TargetTypeKEYWORD, TargetTypePROFILE, TargetTypePOST_URL:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e TargetType) String() string {
	return string(e)
}

func (e TargetType) Ordinal() int {
	switch e {
	case TargetTypeKEYWORD:
		return 0
	case TargetTypePROFILE:
		return 1
	case TargetTypePOST_URL:
		return 2

	default:
		panic(errors.New("enum is not valid"))
	}
}

type SourceType string

// Enum values for SourceType
const (
	SourceTypeTIKTOK      SourceType = "TIKTOK"
	SourceTypeFACEBOOK    SourceType = "FACEBOOK"
	SourceTypeYOUTUBE     SourceType = "YOUTUBE"
	SourceTypeFILE_UPLOAD SourceType = "FILE_UPLOAD"
	SourceTypeWEBHOOK     SourceType = "WEBHOOK"
)

func AllSourceType() []SourceType {
	return []SourceType{
		SourceTypeTIKTOK,
		SourceTypeFACEBOOK,
		SourceTypeYOUTUBE,
		SourceTypeFILE_UPLOAD,
		SourceTypeWEBHOOK,
	}
}

func (e SourceType) IsValid() error {
	switch e {
	case SourceTypeTIKTOK, SourceTypeFACEBOOK, SourceTypeYOUTUBE, SourceTypeFILE_UPLOAD, SourceTypeWEBHOOK:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e SourceType) String() string {
	return string(e)
}

func (e SourceType) Ordinal() int {
	switch e {
	case SourceTypeTIKTOK:
		return 0
	case SourceTypeFACEBOOK:
		return 1
	case SourceTypeYOUTUBE:
		return 2
	case SourceTypeFILE_UPLOAD:
		return 3
	case SourceTypeWEBHOOK:
		return 4

	default:
		panic(errors.New("enum is not valid"))
	}
}

type SourceCategory string

// Enum values for SourceCategory
const (
	SourceCategoryCRAWL   SourceCategory = "CRAWL"
	SourceCategoryPASSIVE SourceCategory = "PASSIVE"
)

func AllSourceCategory() []SourceCategory {
	return []SourceCategory{
		SourceCategoryCRAWL,
		SourceCategoryPASSIVE,
	}
}

func (e SourceCategory) IsValid() error {
	switch e {
	case SourceCategoryCRAWL, SourceCategoryPASSIVE:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e SourceCategory) String() string {
	return string(e)
}

func (e SourceCategory) Ordinal() int {
	switch e {
	case SourceCategoryCRAWL:
		return 0
	case SourceCategoryPASSIVE:
		return 1

	default:
		panic(errors.New("enum is not valid"))
	}
}

type SourceStatus string

// Enum values for SourceStatus
const (
	SourceStatusPENDING   SourceStatus = "PENDING"
	SourceStatusREADY     SourceStatus = "READY"
	SourceStatusACTIVE    SourceStatus = "ACTIVE"
	SourceStatusPAUSED    SourceStatus = "PAUSED"
	SourceStatusFAILED    SourceStatus = "FAILED"
	SourceStatusCOMPLETED SourceStatus = "COMPLETED"
	SourceStatusARCHIVED  SourceStatus = "ARCHIVED"
)

func AllSourceStatus() []SourceStatus {
	return []SourceStatus{
		SourceStatusPENDING,
		SourceStatusREADY,
		SourceStatusACTIVE,
		SourceStatusPAUSED,
		SourceStatusFAILED,
		SourceStatusCOMPLETED,
		SourceStatusARCHIVED,
	}
}

func (e SourceStatus) IsValid() error {
	switch e {
	case SourceStatusPENDING, SourceStatusREADY, SourceStatusACTIVE, SourceStatusPAUSED, SourceStatusFAILED, SourceStatusCOMPLETED, SourceStatusARCHIVED:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e SourceStatus) String() string {
	return string(e)
}

func (e SourceStatus) Ordinal() int {
	switch e {
	case SourceStatusPENDING:
		return 0
	case SourceStatusREADY:
		return 1
	case SourceStatusACTIVE:
		return 2
	case SourceStatusPAUSED:
		return 3
	case SourceStatusFAILED:
		return 4
	case SourceStatusCOMPLETED:
		return 5
	case SourceStatusARCHIVED:
		return 6

	default:
		panic(errors.New("enum is not valid"))
	}
}

type OnboardingStatus string

// Enum values for OnboardingStatus
const (
	OnboardingStatusNOT_REQUIRED OnboardingStatus = "NOT_REQUIRED"
	OnboardingStatusPENDING      OnboardingStatus = "PENDING"
	OnboardingStatusANALYZING    OnboardingStatus = "ANALYZING"
	OnboardingStatusSUGGESTED    OnboardingStatus = "SUGGESTED"
	OnboardingStatusCONFIRMED    OnboardingStatus = "CONFIRMED"
	OnboardingStatusFAILED       OnboardingStatus = "FAILED"
)

func AllOnboardingStatus() []OnboardingStatus {
	return []OnboardingStatus{
		OnboardingStatusNOT_REQUIRED,
		OnboardingStatusPENDING,
		OnboardingStatusANALYZING,
		OnboardingStatusSUGGESTED,
		OnboardingStatusCONFIRMED,
		OnboardingStatusFAILED,
	}
}

func (e OnboardingStatus) IsValid() error {
	switch e {
	case OnboardingStatusNOT_REQUIRED, OnboardingStatusPENDING, OnboardingStatusANALYZING, OnboardingStatusSUGGESTED, OnboardingStatusCONFIRMED, OnboardingStatusFAILED:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e OnboardingStatus) String() string {
	return string(e)
}

func (e OnboardingStatus) Ordinal() int {
	switch e {
	case OnboardingStatusNOT_REQUIRED:
		return 0
	case OnboardingStatusPENDING:
		return 1
	case OnboardingStatusANALYZING:
		return 2
	case OnboardingStatusSUGGESTED:
		return 3
	case OnboardingStatusCONFIRMED:
		return 4
	case OnboardingStatusFAILED:
		return 5

	default:
		panic(errors.New("enum is not valid"))
	}
}

type DryrunStatus string

// Enum values for DryrunStatus
const (
	DryrunStatusNOT_REQUIRED DryrunStatus = "NOT_REQUIRED"
	DryrunStatusPENDING      DryrunStatus = "PENDING"
	DryrunStatusRUNNING      DryrunStatus = "RUNNING"
	DryrunStatusSUCCESS      DryrunStatus = "SUCCESS"
	DryrunStatusWARNING      DryrunStatus = "WARNING"
	DryrunStatusFAILED       DryrunStatus = "FAILED"
)

func AllDryrunStatus() []DryrunStatus {
	return []DryrunStatus{
		DryrunStatusNOT_REQUIRED,
		DryrunStatusPENDING,
		DryrunStatusRUNNING,
		DryrunStatusSUCCESS,
		DryrunStatusWARNING,
		DryrunStatusFAILED,
	}
}

func (e DryrunStatus) IsValid() error {
	switch e {
	case DryrunStatusNOT_REQUIRED, DryrunStatusPENDING, DryrunStatusRUNNING, DryrunStatusSUCCESS, DryrunStatusWARNING, DryrunStatusFAILED:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e DryrunStatus) String() string {
	return string(e)
}

func (e DryrunStatus) Ordinal() int {
	switch e {
	case DryrunStatusNOT_REQUIRED:
		return 0
	case DryrunStatusPENDING:
		return 1
	case DryrunStatusRUNNING:
		return 2
	case DryrunStatusSUCCESS:
		return 3
	case DryrunStatusWARNING:
		return 4
	case DryrunStatusFAILED:
		return 5

	default:
		panic(errors.New("enum is not valid"))
	}
}

// NullCrawlMode is a nullable CrawlMode enum type. It supports SQL and JSON serialization.
type NullCrawlMode struct {
	Val   CrawlMode
	Valid bool
}

// NullCrawlModeFrom creates a new CrawlMode that will never be blank.
func NullCrawlModeFrom(v CrawlMode) NullCrawlMode {
	return NewNullCrawlMode(v, true)
}

// NullCrawlModeFromPtr creates a new NullCrawlMode that be null if s is nil.
func NullCrawlModeFromPtr(v *CrawlMode) NullCrawlMode {
	if v == nil {
		return NewNullCrawlMode("", false)
	}
	return NewNullCrawlMode(*v, true)
}

// NewNullCrawlMode creates a new NullCrawlMode
func NewNullCrawlMode(v CrawlMode, valid bool) NullCrawlMode {
	return NullCrawlMode{
		Val:   v,
		Valid: valid,
	}
}

// UnmarshalJSON implements json.Unmarshaler.
func (e *NullCrawlMode) UnmarshalJSON(data []byte) error {
	if bytes.Equal(data, null.NullBytes) {
		e.Val = ""
		e.Valid = false
		return nil
	}

	if err := json.Unmarshal(data, &e.Val); err != nil {
		return err
	}

	e.Valid = true
	return nil
}

// MarshalJSON implements json.Marshaler.
func (e NullCrawlMode) MarshalJSON() ([]byte, error) {
	if !e.Valid {
		return null.NullBytes, nil
	}
	return json.Marshal(e.Val)
}

// MarshalText implements encoding.TextMarshaler.
func (e NullCrawlMode) MarshalText() ([]byte, error) {
	if !e.Valid {
		return []byte{}, nil
	}
	return []byte(e.Val), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (e *NullCrawlMode) UnmarshalText(text []byte) error {
	if text == nil || len(text) == 0 {
		e.Valid = false
		return nil
	}

	e.Val = CrawlMode(text)
	e.Valid = true
	return nil
}

// SetValid changes this NullCrawlMode value and also sets it to be non-null.
func (e *NullCrawlMode) SetValid(v CrawlMode) {
	e.Val = v
	e.Valid = true
}

// Ptr returns a pointer to this NullCrawlMode value, or a nil pointer if this NullCrawlMode is null.
func (e NullCrawlMode) Ptr() *CrawlMode {
	if !e.Valid {
		return nil
	}
	return &e.Val
}

// IsZero returns true for null types.
func (e NullCrawlMode) IsZero() bool {
	return !e.Valid
}

// Scan implements the Scanner interface.
func (e *NullCrawlMode) Scan(value any) error {
	if value == nil {
		e.Val, e.Valid = "", false
		return nil
	}
	e.Valid = true
	return convert.ConvertAssign((*string)(&e.Val), value)
}

// Value implements the driver Valuer interface.
func (e NullCrawlMode) Value() (driver.Value, error) {
	if !e.Valid {
		return nil, nil
	}
	return string(e.Val), nil
}

type JobStatus string

// Enum values for JobStatus
const (
	JobStatusPENDING   JobStatus = "PENDING"
	JobStatusRUNNING   JobStatus = "RUNNING"
	JobStatusSUCCESS   JobStatus = "SUCCESS"
	JobStatusPARTIAL   JobStatus = "PARTIAL"
	JobStatusFAILED    JobStatus = "FAILED"
	JobStatusCANCELLED JobStatus = "CANCELLED"
)

func AllJobStatus() []JobStatus {
	return []JobStatus{
		JobStatusPENDING,
		JobStatusRUNNING,
		JobStatusSUCCESS,
		JobStatusPARTIAL,
		JobStatusFAILED,
		JobStatusCANCELLED,
	}
}

func (e JobStatus) IsValid() error {
	switch e {
	case JobStatusPENDING, JobStatusRUNNING, JobStatusSUCCESS, JobStatusPARTIAL, JobStatusFAILED, JobStatusCANCELLED:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e JobStatus) String() string {
	return string(e)
}

func (e JobStatus) Ordinal() int {
	switch e {
	case JobStatusPENDING:
		return 0
	case JobStatusRUNNING:
		return 1
	case JobStatusSUCCESS:
		return 2
	case JobStatusPARTIAL:
		return 3
	case JobStatusFAILED:
		return 4
	case JobStatusCANCELLED:
		return 5

	default:
		panic(errors.New("enum is not valid"))
	}
}

type BatchStatus string

// Enum values for BatchStatus
const (
	BatchStatusRECEIVED   BatchStatus = "RECEIVED"
	BatchStatusDOWNLOADED BatchStatus = "DOWNLOADED"
	BatchStatusPARSED     BatchStatus = "PARSED"
	BatchStatusFAILED     BatchStatus = "FAILED"
)

func AllBatchStatus() []BatchStatus {
	return []BatchStatus{
		BatchStatusRECEIVED,
		BatchStatusDOWNLOADED,
		BatchStatusPARSED,
		BatchStatusFAILED,
	}
}

func (e BatchStatus) IsValid() error {
	switch e {
	case BatchStatusRECEIVED, BatchStatusDOWNLOADED, BatchStatusPARSED, BatchStatusFAILED:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e BatchStatus) String() string {
	return string(e)
}

func (e BatchStatus) Ordinal() int {
	switch e {
	case BatchStatusRECEIVED:
		return 0
	case BatchStatusDOWNLOADED:
		return 1
	case BatchStatusPARSED:
		return 2
	case BatchStatusFAILED:
		return 3

	default:
		panic(errors.New("enum is not valid"))
	}
}

type PublishStatus string

// Enum values for PublishStatus
const (
	PublishStatusPENDING    PublishStatus = "PENDING"
	PublishStatusPUBLISHING PublishStatus = "PUBLISHING"
	PublishStatusSUCCESS    PublishStatus = "SUCCESS"
	PublishStatusFAILED     PublishStatus = "FAILED"
)

func AllPublishStatus() []PublishStatus {
	return []PublishStatus{
		PublishStatusPENDING,
		PublishStatusPUBLISHING,
		PublishStatusSUCCESS,
		PublishStatusFAILED,
	}
}

func (e PublishStatus) IsValid() error {
	switch e {
	case PublishStatusPENDING, PublishStatusPUBLISHING, PublishStatusSUCCESS, PublishStatusFAILED:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e PublishStatus) String() string {
	return string(e)
}

func (e PublishStatus) Ordinal() int {
	switch e {
	case PublishStatusPENDING:
		return 0
	case PublishStatusPUBLISHING:
		return 1
	case PublishStatusSUCCESS:
		return 2
	case PublishStatusFAILED:
		return 3

	default:
		panic(errors.New("enum is not valid"))
	}
}
