// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	CrawlModeChanges  string
	CrawlModeDefaults string
	CrawlTargets      string
	DataSources       string
	DryrunResults     string
	ExternalTasks     string
	RawBatches        string
	ScheduledJobs     string
}{
	CrawlModeChanges:  "crawl_mode_changes",
	CrawlModeDefaults: "crawl_mode_defaults",
	CrawlTargets:      "crawl_targets",
	DataSources:       "data_sources",
	DryrunResults:     "dryrun_results",
	ExternalTasks:     "external_tasks",
	RawBatches:        "raw_batches",
	ScheduledJobs:     "scheduled_jobs",
}
