// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// CrawlTarget is an object representing the database table.
type CrawlTarget struct {
	ID                   string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	DataSourceID         string      `boil:"data_source_id" json:"data_source_id" toml:"data_source_id" yaml:"data_source_id"`
	TargetType           TargetType  `boil:"target_type" json:"target_type" toml:"target_type" yaml:"target_type"`
	Values               types.JSON  `boil:"values" json:"values" toml:"values" yaml:"values"`
	Label                null.String `boil:"label" json:"label,omitempty" toml:"label" yaml:"label,omitempty"`
	PlatformMeta         null.JSON   `boil:"platform_meta" json:"platform_meta,omitempty" toml:"platform_meta" yaml:"platform_meta,omitempty"`
	IsActive             bool        `boil:"is_active" json:"is_active" toml:"is_active" yaml:"is_active"`
	Priority             int         `boil:"priority" json:"priority" toml:"priority" yaml:"priority"`
	CrawlIntervalMinutes int         `boil:"crawl_interval_minutes" json:"crawl_interval_minutes" toml:"crawl_interval_minutes" yaml:"crawl_interval_minutes"`
	NextCrawlAt          null.Time   `boil:"next_crawl_at" json:"next_crawl_at,omitempty" toml:"next_crawl_at" yaml:"next_crawl_at,omitempty"`
	LastCrawlAt          null.Time   `boil:"last_crawl_at" json:"last_crawl_at,omitempty" toml:"last_crawl_at" yaml:"last_crawl_at,omitempty"`
	LastSuccessAt        null.Time   `boil:"last_success_at" json:"last_success_at,omitempty" toml:"last_success_at" yaml:"last_success_at,omitempty"`
	LastErrorAt          null.Time   `boil:"last_error_at" json:"last_error_at,omitempty" toml:"last_error_at" yaml:"last_error_at,omitempty"`
	LastErrorMessage     null.String `boil:"last_error_message" json:"last_error_message,omitempty" toml:"last_error_message" yaml:"last_error_message,omitempty"`
	CreatedAt            time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt            time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *crawlTargetR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L crawlTargetL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CrawlTargetColumns = struct {
	ID                   string
	DataSourceID         string
	TargetType           string
	Values               string
	Label                string
	PlatformMeta         string
	IsActive             string
	Priority             string
	CrawlIntervalMinutes string
	NextCrawlAt          string
	LastCrawlAt          string
	LastSuccessAt        string
	LastErrorAt          string
	LastErrorMessage     string
	CreatedAt            string
	UpdatedAt            string
}{
	ID:                   "id",
	DataSourceID:         "data_source_id",
	TargetType:           "target_type",
	Values:               "values",
	Label:                "label",
	PlatformMeta:         "platform_meta",
	IsActive:             "is_active",
	Priority:             "priority",
	CrawlIntervalMinutes: "crawl_interval_minutes",
	NextCrawlAt:          "next_crawl_at",
	LastCrawlAt:          "last_crawl_at",
	LastSuccessAt:        "last_success_at",
	LastErrorAt:          "last_error_at",
	LastErrorMessage:     "last_error_message",
	CreatedAt:            "created_at",
	UpdatedAt:            "updated_at",
}

var CrawlTargetTableColumns = struct {
	ID                   string
	DataSourceID         string
	TargetType           string
	Values               string
	Label                string
	PlatformMeta         string
	IsActive             string
	Priority             string
	CrawlIntervalMinutes string
	NextCrawlAt          string
	LastCrawlAt          string
	LastSuccessAt        string
	LastErrorAt          string
	LastErrorMessage     string
	CreatedAt            string
	UpdatedAt            string
}{
	ID:                   "crawl_targets.id",
	DataSourceID:         "crawl_targets.data_source_id",
	TargetType:           "crawl_targets.target_type",
	Values:               "crawl_targets.values",
	Label:                "crawl_targets.label",
	PlatformMeta:         "crawl_targets.platform_meta",
	IsActive:             "crawl_targets.is_active",
	Priority:             "crawl_targets.priority",
	CrawlIntervalMinutes: "crawl_targets.crawl_interval_minutes",
	NextCrawlAt:          "crawl_targets.next_crawl_at",
	LastCrawlAt:          "crawl_targets.last_crawl_at",
	LastSuccessAt:        "crawl_targets.last_success_at",
	LastErrorAt:          "crawl_targets.last_error_at",
	LastErrorMessage:     "crawl_targets.last_error_message",
	CreatedAt:            "crawl_targets.created_at",
	UpdatedAt:            "crawl_targets.updated_at",
}

// Generated where

type whereHelperTargetType struct{ field string }

func (w whereHelperTargetType) EQ(x TargetType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperTargetType) NEQ(x TargetType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperTargetType) LT(x TargetType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperTargetType) LTE(x TargetType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperTargetType) GT(x TargetType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperTargetType) GTE(x TargetType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperTargetType) IN(slice []TargetType) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperTargetType) NIN(slice []TargetType) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var CrawlTargetWhere = struct {
	ID                   whereHelperstring
	DataSourceID         whereHelperstring
	TargetType           whereHelperTargetType
	Values               whereHelpertypes_JSON
	Label                whereHelpernull_String
	PlatformMeta         whereHelpernull_JSON
	IsActive             whereHelperbool
	Priority             whereHelperint
	CrawlIntervalMinutes whereHelperint
	NextCrawlAt          whereHelpernull_Time
	LastCrawlAt          whereHelpernull_Time
	LastSuccessAt        whereHelpernull_Time
	LastErrorAt          whereHelpernull_Time
	LastErrorMessage     whereHelpernull_String
	CreatedAt            whereHelpertime_Time
	UpdatedAt            whereHelpertime_Time
}{
	ID:                   whereHelperstring{field: "\"ingest\".\"crawl_targets\".\"id\""},
	DataSourceID:         whereHelperstring{field: "\"ingest\".\"crawl_targets\".\"data_source_id\""},
	TargetType:           whereHelperTargetType{field: "\"ingest\".\"crawl_targets\".\"target_type\""},
	Values:               whereHelpertypes_JSON{field: "\"ingest\".\"crawl_targets\".\"values\""},
	Label:                whereHelpernull_String{field: "\"ingest\".\"crawl_targets\".\"label\""},
	PlatformMeta:         whereHelpernull_JSON{field: "\"ingest\".\"crawl_targets\".\"platform_meta\""},
	IsActive:             whereHelperbool{field: "\"ingest\".\"crawl_targets\".\"is_active\""},
	Priority:             whereHelperint{field: "\"ingest\".\"crawl_targets\".\"priority\""},
	CrawlIntervalMinutes: whereHelperint{field: "\"ingest\".\"crawl_targets\".\"crawl_interval_minutes\""},
	NextCrawlAt:          whereHelpernull_Time{field: "\"ingest\".\"crawl_targets\".\"next_crawl_at\""},
	LastCrawlAt:          whereHelpernull_Time{field: "\"ingest\".\"crawl_targets\".\"last_crawl_at\""},
	LastSuccessAt:        whereHelpernull_Time{field: "\"ingest\".\"crawl_targets\".\"last_success_at\""},
	LastErrorAt:          whereHelpernull_Time{field: "\"ingest\".\"crawl_targets\".\"last_error_at\""},
	LastErrorMessage:     whereHelpernull_String{field: "\"ingest\".\"crawl_targets\".\"last_error_message\""},
	CreatedAt:            whereHelpertime_Time{field: "\"ingest\".\"crawl_targets\".\"created_at\""},
	UpdatedAt:            whereHelpertime_Time{field: "\"ingest\".\"crawl_targets\".\"updated_at\""},
}

// CrawlTargetRels is where relationship names are stored.
var CrawlTargetRels = struct {
	DataSource          string
	TargetDryrunResults string
	TargetExternalTasks string
	TargetScheduledJobs string
}{
	DataSource:          "DataSource",
	TargetDryrunResults: "TargetDryrunResults",
	TargetExternalTasks: "TargetExternalTasks",
	TargetScheduledJobs: "TargetScheduledJobs",
}

// crawlTargetR is where relationships are stored.
type crawlTargetR struct {
	DataSource          *DataSource       `boil:"DataSource" json:"DataSource" toml:"DataSource" yaml:"DataSource"`
	TargetDryrunResults DryrunResultSlice `boil:"TargetDryrunResults" json:"TargetDryrunResults" toml:"TargetDryrunResults" yaml:"TargetDryrunResults"`
	TargetExternalTasks ExternalTaskSlice `boil:"TargetExternalTasks" json:"TargetExternalTasks" toml:"TargetExternalTasks" yaml:"TargetExternalTasks"`
	TargetScheduledJobs ScheduledJobSlice `boil:"TargetScheduledJobs" json:"TargetScheduledJobs" toml:"TargetScheduledJobs" yaml:"TargetScheduledJobs"`
}

// NewStruct creates a new relationship struct
func (*crawlTargetR) NewStruct() *crawlTargetR {
	return &crawlTargetR{}
}

func (o *CrawlTarget) GetDataSource() *DataSource {
	if o == nil {
		return nil
	}

	return o.R.GetDataSource()
}

func (r *crawlTargetR) GetDataSource() *DataSource {
	if r == nil {
		return nil
	}

	return r.DataSource
}

func (o *CrawlTarget) GetTargetDryrunResults() DryrunResultSlice {
	if o == nil {
		return nil
	}

	return o.R.GetTargetDryrunResults()
}

func (r *crawlTargetR) GetTargetDryrunResults() DryrunResultSlice {
	if r == nil {
		return nil
	}

	return r.TargetDryrunResults
}

func (o *CrawlTarget) GetTargetExternalTasks() ExternalTaskSlice {
	if o == nil {
		return nil
	}

	return o.R.GetTargetExternalTasks()
}

func (r *crawlTargetR) GetTargetExternalTasks() ExternalTaskSlice {
	if r == nil {
		return nil
	}

	return r.TargetExternalTasks
}

func (o *CrawlTarget) GetTargetScheduledJobs() ScheduledJobSlice {
	if o == nil {
		return nil
	}

	return o.R.GetTargetScheduledJobs()
}

func (r *crawlTargetR) GetTargetScheduledJobs() ScheduledJobSlice {
	if r == nil {
		return nil
	}

	return r.TargetScheduledJobs
}

// crawlTargetL is where Load methods for each relationship are stored.
type crawlTargetL struct{}

var (
	crawlTargetAllColumns            = []string{"id", "data_source_id", "target_type", "values", "label", "platform_meta", "is_active", "priority", "crawl_interval_minutes", "next_crawl_at", "last_crawl_at", "last_success_at", "last_error_at", "last_error_message", "created_at", "updated_at"}
	crawlTargetColumnsWithoutDefault = []string{"data_source_id", "target_type", "values"}
	crawlTargetColumnsWithDefault    = []string{"id", "label", "platform_meta", "is_active", "priority", "crawl_interval_minutes", "next_crawl_at", "last_crawl_at", "last_success_at", "last_error_at", "last_error_message", "created_at", "updated_at"}
	crawlTargetPrimaryKeyColumns     = []string{"id"}
	crawlTargetGeneratedColumns      = []string{}
)

type (
	// CrawlTargetSlice is an alias for a slice of pointers to CrawlTarget.
	// This should almost always be used instead of []CrawlTarget.
	CrawlTargetSlice []*CrawlTarget
	// CrawlTargetHook is the signature for custom CrawlTarget hook methods
	CrawlTargetHook func(context.Context, boil.ContextExecutor, *CrawlTarget) error

	crawlTargetQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	crawlTargetType                 = reflect.TypeOf(&CrawlTarget{})
	crawlTargetMapping              = queries.MakeStructMapping(crawlTargetType)
	crawlTargetPrimaryKeyMapping, _ = queries.BindMapping(crawlTargetType, crawlTargetMapping, crawlTargetPrimaryKeyColumns)
	crawlTargetInsertCacheMut       sync.RWMutex
	crawlTargetInsertCache          = make(map[string]insertCache)
	crawlTargetUpdateCacheMut       sync.RWMutex
	crawlTargetUpdateCache          = make(map[string]updateCache)
	crawlTargetUpsertCacheMut       sync.RWMutex
	crawlTargetUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var crawlTargetAfterSelectMu sync.Mutex
var crawlTargetAfterSelectHooks []CrawlTargetHook

var crawlTargetBeforeInsertMu sync.Mutex
var crawlTargetBeforeInsertHooks []CrawlTargetHook
var crawlTargetAfterInsertMu sync.Mutex
var crawlTargetAfterInsertHooks []CrawlTargetHook

var crawlTargetBeforeUpdateMu sync.Mutex
var crawlTargetBeforeUpdateHooks []CrawlTargetHook
var crawlTargetAfterUpdateMu sync.Mutex
var crawlTargetAfterUpdateHooks []CrawlTargetHook

var crawlTargetBeforeDeleteMu sync.Mutex
var crawlTargetBeforeDeleteHooks []CrawlTargetHook
var crawlTargetAfterDeleteMu sync.Mutex
var crawlTargetAfterDeleteHooks []CrawlTargetHook

var crawlTargetBeforeUpsertMu sync.Mutex
var crawlTargetBeforeUpsertHooks []CrawlTargetHook
var crawlTargetAfterUpsertMu sync.Mutex
var crawlTargetAfterUpsertHooks []CrawlTargetHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CrawlTarget) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CrawlTarget) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CrawlTarget) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CrawlTarget) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CrawlTarget) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CrawlTarget) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CrawlTarget) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CrawlTarget) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CrawlTarget) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlTargetAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCrawlTargetHook registers your hook function for all future operations.
func AddCrawlTargetHook(hookPoint boil.HookPoint, crawlTargetHook CrawlTargetHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		crawlTargetAfterSelectMu.Lock()
		crawlTargetAfterSelectHooks = append(crawlTargetAfterSelectHooks, crawlTargetHook)
		crawlTargetAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		crawlTargetBeforeInsertMu.Lock()
		crawlTargetBeforeInsertHooks = append(crawlTargetBeforeInsertHooks, crawlTargetHook)
		crawlTargetBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		crawlTargetAfterInsertMu.Lock()
		crawlTargetAfterInsertHooks = append(crawlTargetAfterInsertHooks, crawlTargetHook)
		crawlTargetAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		crawlTargetBeforeUpdateMu.Lock()
		crawlTargetBeforeUpdateHooks = append(crawlTargetBeforeUpdateHooks, crawlTargetHook)
		crawlTargetBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		crawlTargetAfterUpdateMu.Lock()
		crawlTargetAfterUpdateHooks = append(crawlTargetAfterUpdateHooks, crawlTargetHook)
		crawlTargetAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		crawlTargetBeforeDeleteMu.Lock()
		crawlTargetBeforeDeleteHooks = append(crawlTargetBeforeDeleteHooks, crawlTargetHook)
		crawlTargetBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		crawlTargetAfterDeleteMu.Lock()
		crawlTargetAfterDeleteHooks = append(crawlTargetAfterDeleteHooks, crawlTargetHook)
		crawlTargetAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		crawlTargetBeforeUpsertMu.Lock()
		crawlTargetBeforeUpsertHooks = append(crawlTargetBeforeUpsertHooks, crawlTargetHook)
		crawlTargetBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		crawlTargetAfterUpsertMu.Lock()
		crawlTargetAfterUpsertHooks = append(crawlTargetAfterUpsertHooks, crawlTargetHook)
		crawlTargetAfterUpsertMu.Unlock()
	}
}

// One returns a single crawlTarget record from the query.
func (q crawlTargetQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CrawlTarget, error) {
	o := &CrawlTarget{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for crawl_targets")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CrawlTarget records from the query.
func (q crawlTargetQuery) All(ctx context.Context, exec boil.ContextExecutor) (CrawlTargetSlice, error) {
	var o []*CrawlTarget

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to CrawlTarget slice")
	}

	if len(crawlTargetAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CrawlTarget records in the query.
func (q crawlTargetQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count crawl_targets rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q crawlTargetQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if crawl_targets exists")
	}

	return count > 0, nil
}

// DataSource pointed to by the foreign key.
func (o *CrawlTarget) DataSource(mods ...qm.QueryMod) dataSourceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DataSourceID),
	}

	queryMods = append(queryMods, mods...)

	return DataSources(queryMods...)
}

// TargetDryrunResults retrieves all the dryrun_result's DryrunResults with an executor via target_id column.
func (o *CrawlTarget) TargetDryrunResults(mods ...qm.QueryMod) dryrunResultQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ingest\".\"dryrun_results\".\"target_id\"=?", o.ID),
	)

	return DryrunResults(queryMods...)
}

// TargetExternalTasks retrieves all the external_task's ExternalTasks with an executor via target_id column.
func (o *CrawlTarget) TargetExternalTasks(mods ...qm.QueryMod) externalTaskQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ingest\".\"external_tasks\".\"target_id\"=?", o.ID),
	)

	return ExternalTasks(queryMods...)
}

// TargetScheduledJobs retrieves all the scheduled_job's ScheduledJobs with an executor via target_id column.
func (o *CrawlTarget) TargetScheduledJobs(mods ...qm.QueryMod) scheduledJobQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ingest\".\"scheduled_jobs\".\"target_id\"=?", o.ID),
	)

	return ScheduledJobs(queryMods...)
}

// LoadDataSource allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (crawlTargetL) LoadDataSource(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCrawlTarget any, mods queries.Applicator) error {
	var slice []*CrawlTarget
	var object *CrawlTarget

	if singular {
		var ok bool
		object, ok = maybeCrawlTarget.(*CrawlTarget)
		if !ok {
			object = new(CrawlTarget)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCrawlTarget)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCrawlTarget))
			}
		}
	} else {
		s, ok := maybeCrawlTarget.(*[]*CrawlTarget)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCrawlTarget)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCrawlTarget))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &crawlTargetR{}
		}
		args[object.DataSourceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &crawlTargetR{}
			}

			args[obj.DataSourceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.data_sources`),
		qm.WhereIn(`ingest.data_sources.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`ingest.data_sources.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataSource")
	}

	var resultSlice []*DataSource
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataSource")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_sources")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_sources")
	}

	if len(dataSourceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DataSource = foreign
		if foreign.R == nil {
			foreign.R = &dataSourceR{}
		}
		foreign.R.CrawlTargets = append(foreign.R.CrawlTargets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DataSourceID == foreign.ID {
				local.R.DataSource = foreign
				if foreign.R == nil {
					foreign.R = &dataSourceR{}
				}
				foreign.R.CrawlTargets = append(foreign.R.CrawlTargets, local)
				break
			}
		}
	}

	return nil
}

// LoadTargetDryrunResults allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (crawlTargetL) LoadTargetDryrunResults(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCrawlTarget any, mods queries.Applicator) error {
	var slice []*CrawlTarget
	var object *CrawlTarget

	if singular {
		var ok bool
		object, ok = maybeCrawlTarget.(*CrawlTarget)
		if !ok {
			object = new(CrawlTarget)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCrawlTarget)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCrawlTarget))
			}
		}
	} else {
		s, ok := maybeCrawlTarget.(*[]*CrawlTarget)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCrawlTarget)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCrawlTarget))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &crawlTargetR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &crawlTargetR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.dryrun_results`),
		qm.WhereIn(`ingest.dryrun_results.target_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load dryrun_results")
	}

	var resultSlice []*DryrunResult
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice dryrun_results")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on dryrun_results")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for dryrun_results")
	}

	if len(dryrunResultAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TargetDryrunResults = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &dryrunResultR{}
			}
			foreign.R.Target = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.TargetID) {
				local.R.TargetDryrunResults = append(local.R.TargetDryrunResults, foreign)
				if foreign.R == nil {
					foreign.R = &dryrunResultR{}
				}
				foreign.R.Target = local
				break
			}
		}
	}

	return nil
}

// LoadTargetExternalTasks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (crawlTargetL) LoadTargetExternalTasks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCrawlTarget any, mods queries.Applicator) error {
	var slice []*CrawlTarget
	var object *CrawlTarget

	if singular {
		var ok bool
		object, ok = maybeCrawlTarget.(*CrawlTarget)
		if !ok {
			object = new(CrawlTarget)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCrawlTarget)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCrawlTarget))
			}
		}
	} else {
		s, ok := maybeCrawlTarget.(*[]*CrawlTarget)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCrawlTarget)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCrawlTarget))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &crawlTargetR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &crawlTargetR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.external_tasks`),
		qm.WhereIn(`ingest.external_tasks.target_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load external_tasks")
	}

	var resultSlice []*ExternalTask
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice external_tasks")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on external_tasks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for external_tasks")
	}

	if len(externalTaskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TargetExternalTasks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &externalTaskR{}
			}
			foreign.R.Target = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.TargetID) {
				local.R.TargetExternalTasks = append(local.R.TargetExternalTasks, foreign)
				if foreign.R == nil {
					foreign.R = &externalTaskR{}
				}
				foreign.R.Target = local
				break
			}
		}
	}

	return nil
}

// LoadTargetScheduledJobs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (crawlTargetL) LoadTargetScheduledJobs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCrawlTarget any, mods queries.Applicator) error {
	var slice []*CrawlTarget
	var object *CrawlTarget

	if singular {
		var ok bool
		object, ok = maybeCrawlTarget.(*CrawlTarget)
		if !ok {
			object = new(CrawlTarget)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCrawlTarget)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCrawlTarget))
			}
		}
	} else {
		s, ok := maybeCrawlTarget.(*[]*CrawlTarget)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCrawlTarget)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCrawlTarget))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &crawlTargetR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &crawlTargetR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.scheduled_jobs`),
		qm.WhereIn(`ingest.scheduled_jobs.target_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load scheduled_jobs")
	}

	var resultSlice []*ScheduledJob
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice scheduled_jobs")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on scheduled_jobs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for scheduled_jobs")
	}

	if len(scheduledJobAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TargetScheduledJobs = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &scheduledJobR{}
			}
			foreign.R.Target = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.TargetID) {
				local.R.TargetScheduledJobs = append(local.R.TargetScheduledJobs, foreign)
				if foreign.R == nil {
					foreign.R = &scheduledJobR{}
				}
				foreign.R.Target = local
				break
			}
		}
	}

	return nil
}

// SetDataSource of the crawlTarget to the related item.
// Sets o.R.DataSource to related.
// Adds o to related.R.CrawlTargets.
func (o *CrawlTarget) SetDataSource(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataSource) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ingest\".\"crawl_targets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"data_source_id"}),
		strmangle.WhereClause("\"", "\"", 2, crawlTargetPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DataSourceID = related.ID
	if o.R == nil {
		o.R = &crawlTargetR{
			DataSource: related,
		}
	} else {
		o.R.DataSource = related
	}

	if related.R == nil {
		related.R = &dataSourceR{
			CrawlTargets: CrawlTargetSlice{o},
		}
	} else {
		related.R.CrawlTargets = append(related.R.CrawlTargets, o)
	}

	return nil
}

// AddTargetDryrunResults adds the given related objects to the existing relationships
// of the crawl_target, optionally inserting them as new records.
// Appends related to o.R.TargetDryrunResults.
// Sets related.R.Target appropriately.
func (o *CrawlTarget) AddTargetDryrunResults(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DryrunResult) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.TargetID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ingest\".\"dryrun_results\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"target_id"}),
				strmangle.WhereClause("\"", "\"", 2, dryrunResultPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.TargetID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &crawlTargetR{
			TargetDryrunResults: related,
		}
	} else {
		o.R.TargetDryrunResults = append(o.R.TargetDryrunResults, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &dryrunResultR{
				Target: o,
			}
		} else {
			rel.R.Target = o
		}
	}
	return nil
}

// SetTargetDryrunResults removes all previously related items of the
// crawl_target replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Target's TargetDryrunResults accordingly.
// Replaces o.R.TargetDryrunResults with related.
// Sets related.R.Target's TargetDryrunResults accordingly.
func (o *CrawlTarget) SetTargetDryrunResults(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DryrunResult) error {
	query := "update \"ingest\".\"dryrun_results\" set \"target_id\" = null where \"target_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.TargetDryrunResults {
			queries.SetScanner(&rel.TargetID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Target = nil
		}
		o.R.TargetDryrunResults = nil
	}

	return o.AddTargetDryrunResults(ctx, exec, insert, related...)
}

// RemoveTargetDryrunResults relationships from objects passed in.
// Removes related items from R.TargetDryrunResults (uses pointer comparison, removal does not keep order)
// Sets related.R.Target.
func (o *CrawlTarget) RemoveTargetDryrunResults(ctx context.Context, exec boil.ContextExecutor, related ...*DryrunResult) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.TargetID, nil)
		if rel.R != nil {
			rel.R.Target = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("target_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.TargetDryrunResults {
			if rel != ri {
				continue
			}

			ln := len(o.R.TargetDryrunResults)
			if ln > 1 && i < ln-1 {
				o.R.TargetDryrunResults[i] = o.R.TargetDryrunResults[ln-1]
			}
			o.R.TargetDryrunResults = o.R.TargetDryrunResults[:ln-1]
			break
		}
	}

	return nil
}

// AddTargetExternalTasks adds the given related objects to the existing relationships
// of the crawl_target, optionally inserting them as new records.
// Appends related to o.R.TargetExternalTasks.
// Sets related.R.Target appropriately.
func (o *CrawlTarget) AddTargetExternalTasks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ExternalTask) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.TargetID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ingest\".\"external_tasks\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"target_id"}),
				strmangle.WhereClause("\"", "\"", 2, externalTaskPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.TargetID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &crawlTargetR{
			TargetExternalTasks: related,
		}
	} else {
		o.R.TargetExternalTasks = append(o.R.TargetExternalTasks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &externalTaskR{
				Target: o,
			}
		} else {
			rel.R.Target = o
		}
	}
	return nil
}

// SetTargetExternalTasks removes all previously related items of the
// crawl_target replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Target's TargetExternalTasks accordingly.
// Replaces o.R.TargetExternalTasks with related.
// Sets related.R.Target's TargetExternalTasks accordingly.
func (o *CrawlTarget) SetTargetExternalTasks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ExternalTask) error {
	query := "update \"ingest\".\"external_tasks\" set \"target_id\" = null where \"target_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.TargetExternalTasks {
			queries.SetScanner(&rel.TargetID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Target = nil
		}
		o.R.TargetExternalTasks = nil
	}

	return o.AddTargetExternalTasks(ctx, exec, insert, related...)
}

// RemoveTargetExternalTasks relationships from objects passed in.
// Removes related items from R.TargetExternalTasks (uses pointer comparison, removal does not keep order)
// Sets related.R.Target.
func (o *CrawlTarget) RemoveTargetExternalTasks(ctx context.Context, exec boil.ContextExecutor, related ...*ExternalTask) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.TargetID, nil)
		if rel.R != nil {
			rel.R.Target = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("target_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.TargetExternalTasks {
			if rel != ri {
				continue
			}

			ln := len(o.R.TargetExternalTasks)
			if ln > 1 && i < ln-1 {
				o.R.TargetExternalTasks[i] = o.R.TargetExternalTasks[ln-1]
			}
			o.R.TargetExternalTasks = o.R.TargetExternalTasks[:ln-1]
			break
		}
	}

	return nil
}

// AddTargetScheduledJobs adds the given related objects to the existing relationships
// of the crawl_target, optionally inserting them as new records.
// Appends related to o.R.TargetScheduledJobs.
// Sets related.R.Target appropriately.
func (o *CrawlTarget) AddTargetScheduledJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ScheduledJob) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.TargetID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ingest\".\"scheduled_jobs\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"target_id"}),
				strmangle.WhereClause("\"", "\"", 2, scheduledJobPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.TargetID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &crawlTargetR{
			TargetScheduledJobs: related,
		}
	} else {
		o.R.TargetScheduledJobs = append(o.R.TargetScheduledJobs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &scheduledJobR{
				Target: o,
			}
		} else {
			rel.R.Target = o
		}
	}
	return nil
}

// SetTargetScheduledJobs removes all previously related items of the
// crawl_target replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Target's TargetScheduledJobs accordingly.
// Replaces o.R.TargetScheduledJobs with related.
// Sets related.R.Target's TargetScheduledJobs accordingly.
func (o *CrawlTarget) SetTargetScheduledJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ScheduledJob) error {
	query := "update \"ingest\".\"scheduled_jobs\" set \"target_id\" = null where \"target_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.TargetScheduledJobs {
			queries.SetScanner(&rel.TargetID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Target = nil
		}
		o.R.TargetScheduledJobs = nil
	}

	return o.AddTargetScheduledJobs(ctx, exec, insert, related...)
}

// RemoveTargetScheduledJobs relationships from objects passed in.
// Removes related items from R.TargetScheduledJobs (uses pointer comparison, removal does not keep order)
// Sets related.R.Target.
func (o *CrawlTarget) RemoveTargetScheduledJobs(ctx context.Context, exec boil.ContextExecutor, related ...*ScheduledJob) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.TargetID, nil)
		if rel.R != nil {
			rel.R.Target = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("target_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.TargetScheduledJobs {
			if rel != ri {
				continue
			}

			ln := len(o.R.TargetScheduledJobs)
			if ln > 1 && i < ln-1 {
				o.R.TargetScheduledJobs[i] = o.R.TargetScheduledJobs[ln-1]
			}
			o.R.TargetScheduledJobs = o.R.TargetScheduledJobs[:ln-1]
			break
		}
	}

	return nil
}

// CrawlTargets retrieves all the records using an executor.
func CrawlTargets(mods ...qm.QueryMod) crawlTargetQuery {
	mods = append(mods, qm.From("\"ingest\".\"crawl_targets\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ingest\".\"crawl_targets\".*"})
	}

	return crawlTargetQuery{q}
}

// FindCrawlTarget retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCrawlTarget(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*CrawlTarget, error) {
	crawlTargetObj := &CrawlTarget{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ingest\".\"crawl_targets\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, crawlTargetObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from crawl_targets")
	}

	if err = crawlTargetObj.doAfterSelectHooks(ctx, exec); err != nil {
		return crawlTargetObj, err
	}

	return crawlTargetObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CrawlTarget) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no crawl_targets provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(crawlTargetColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	crawlTargetInsertCacheMut.RLock()
	cache, cached := crawlTargetInsertCache[key]
	crawlTargetInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			crawlTargetAllColumns,
			crawlTargetColumnsWithDefault,
			crawlTargetColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(crawlTargetType, crawlTargetMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(crawlTargetType, crawlTargetMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ingest\".\"crawl_targets\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ingest\".\"crawl_targets\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into crawl_targets")
	}

	if !cached {
		crawlTargetInsertCacheMut.Lock()
		crawlTargetInsertCache[key] = cache
		crawlTargetInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CrawlTarget.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CrawlTarget) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	crawlTargetUpdateCacheMut.RLock()
	cache, cached := crawlTargetUpdateCache[key]
	crawlTargetUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			crawlTargetAllColumns,
			crawlTargetPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update crawl_targets, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ingest\".\"crawl_targets\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, crawlTargetPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(crawlTargetType, crawlTargetMapping, append(wl, crawlTargetPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update crawl_targets row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for crawl_targets")
	}

	if !cached {
		crawlTargetUpdateCacheMut.Lock()
		crawlTargetUpdateCache[key] = cache
		crawlTargetUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q crawlTargetQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for crawl_targets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for crawl_targets")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CrawlTargetSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlTargetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ingest\".\"crawl_targets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, crawlTargetPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in crawlTarget slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all crawlTarget")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CrawlTarget) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no crawl_targets provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(crawlTargetColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	crawlTargetUpsertCacheMut.RLock()
	cache, cached := crawlTargetUpsertCache[key]
	crawlTargetUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			crawlTargetAllColumns,
			crawlTargetColumnsWithDefault,
			crawlTargetColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			crawlTargetAllColumns,
			crawlTargetPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert crawl_targets, could not build update column list")
		}

		ret := strmangle.SetComplement(crawlTargetAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(crawlTargetPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert crawl_targets, could not build conflict column list")
			}

			conflict = make([]string, len(crawlTargetPrimaryKeyColumns))
			copy(conflict, crawlTargetPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ingest\".\"crawl_targets\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(crawlTargetType, crawlTargetMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(crawlTargetType, crawlTargetMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert crawl_targets")
	}

	if !cached {
		crawlTargetUpsertCacheMut.Lock()
		crawlTargetUpsertCache[key] = cache
		crawlTargetUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CrawlTarget record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CrawlTarget) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no CrawlTarget provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), crawlTargetPrimaryKeyMapping)
	sql := "DELETE FROM \"ingest\".\"crawl_targets\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from crawl_targets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for crawl_targets")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q crawlTargetQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no crawlTargetQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from crawl_targets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for crawl_targets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CrawlTargetSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(crawlTargetBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlTargetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ingest\".\"crawl_targets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, crawlTargetPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from crawlTarget slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for crawl_targets")
	}

	if len(crawlTargetAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CrawlTarget) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCrawlTarget(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CrawlTargetSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CrawlTargetSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlTargetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ingest\".\"crawl_targets\".* FROM \"ingest\".\"crawl_targets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, crawlTargetPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in CrawlTargetSlice")
	}

	*o = slice

	return nil
}

// CrawlTargetExists checks if the CrawlTarget row exists.
func CrawlTargetExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ingest\".\"crawl_targets\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if crawl_targets exists")
	}

	return exists, nil
}

// Exists checks if the CrawlTarget row exists.
func (o *CrawlTarget) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CrawlTargetExists(ctx, exec, o.ID)
}
