// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// CrawlModeChange is an object representing the database table.
type CrawlModeChange struct {
	ID                  string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	SourceID            string      `boil:"source_id" json:"source_id" toml:"source_id" yaml:"source_id"`
	ProjectID           string      `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	TriggerType         TriggerType `boil:"trigger_type" json:"trigger_type" toml:"trigger_type" yaml:"trigger_type"`
	FromMode            CrawlMode   `boil:"from_mode" json:"from_mode" toml:"from_mode" yaml:"from_mode"`
	ToMode              CrawlMode   `boil:"to_mode" json:"to_mode" toml:"to_mode" yaml:"to_mode"`
	FromIntervalMinutes int         `boil:"from_interval_minutes" json:"from_interval_minutes" toml:"from_interval_minutes" yaml:"from_interval_minutes"`
	ToIntervalMinutes   int         `boil:"to_interval_minutes" json:"to_interval_minutes" toml:"to_interval_minutes" yaml:"to_interval_minutes"`
	Reason              null.String `boil:"reason" json:"reason,omitempty" toml:"reason" yaml:"reason,omitempty"`
	EventRef            null.String `boil:"event_ref" json:"event_ref,omitempty" toml:"event_ref" yaml:"event_ref,omitempty"`
	TriggeredBy         null.String `boil:"triggered_by" json:"triggered_by,omitempty" toml:"triggered_by" yaml:"triggered_by,omitempty"`
	TriggeredAt         time.Time   `boil:"triggered_at" json:"triggered_at" toml:"triggered_at" yaml:"triggered_at"`
	CreatedAt           time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *crawlModeChangeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L crawlModeChangeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CrawlModeChangeColumns = struct {
	ID                  string
	SourceID            string
	ProjectID           string
	TriggerType         string
	FromMode            string
	ToMode              string
	FromIntervalMinutes string
	ToIntervalMinutes   string
	Reason              string
	EventRef            string
	TriggeredBy         string
	TriggeredAt         string
	CreatedAt           string
}{
	ID:                  "id",
	SourceID:            "source_id",
	ProjectID:           "project_id",
	TriggerType:         "trigger_type",
	FromMode:            "from_mode",
	ToMode:              "to_mode",
	FromIntervalMinutes: "from_interval_minutes",
	ToIntervalMinutes:   "to_interval_minutes",
	Reason:              "reason",
	EventRef:            "event_ref",
	TriggeredBy:         "triggered_by",
	TriggeredAt:         "triggered_at",
	CreatedAt:           "created_at",
}

var CrawlModeChangeTableColumns = struct {
	ID                  string
	SourceID            string
	ProjectID           string
	TriggerType         string
	FromMode            string
	ToMode              string
	FromIntervalMinutes string
	ToIntervalMinutes   string
	Reason              string
	EventRef            string
	TriggeredBy         string
	TriggeredAt         string
	CreatedAt           string
}{
	ID:                  "crawl_mode_changes.id",
	SourceID:            "crawl_mode_changes.source_id",
	ProjectID:           "crawl_mode_changes.project_id",
	TriggerType:         "crawl_mode_changes.trigger_type",
	FromMode:            "crawl_mode_changes.from_mode",
	ToMode:              "crawl_mode_changes.to_mode",
	FromIntervalMinutes: "crawl_mode_changes.from_interval_minutes",
	ToIntervalMinutes:   "crawl_mode_changes.to_interval_minutes",
	Reason:              "crawl_mode_changes.reason",
	EventRef:            "crawl_mode_changes.event_ref",
	TriggeredBy:         "crawl_mode_changes.triggered_by",
	TriggeredAt:         "crawl_mode_changes.triggered_at",
	CreatedAt:           "crawl_mode_changes.created_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperTriggerType struct{ field string }

func (w whereHelperTriggerType) EQ(x TriggerType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperTriggerType) NEQ(x TriggerType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperTriggerType) LT(x TriggerType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperTriggerType) LTE(x TriggerType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperTriggerType) GT(x TriggerType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperTriggerType) GTE(x TriggerType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperTriggerType) IN(slice []TriggerType) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperTriggerType) NIN(slice []TriggerType) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperCrawlMode struct{ field string }

func (w whereHelperCrawlMode) EQ(x CrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperCrawlMode) NEQ(x CrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperCrawlMode) LT(x CrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperCrawlMode) LTE(x CrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperCrawlMode) GT(x CrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperCrawlMode) GTE(x CrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperCrawlMode) IN(slice []CrawlMode) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperCrawlMode) NIN(slice []CrawlMode) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var CrawlModeChangeWhere = struct {
	ID                  whereHelperstring
	SourceID            whereHelperstring
	ProjectID           whereHelperstring
	TriggerType         whereHelperTriggerType
	FromMode            whereHelperCrawlMode
	ToMode              whereHelperCrawlMode
	FromIntervalMinutes whereHelperint
	ToIntervalMinutes   whereHelperint
	Reason              whereHelpernull_String
	EventRef            whereHelpernull_String
	TriggeredBy         whereHelpernull_String
	TriggeredAt         whereHelpertime_Time
	CreatedAt           whereHelpertime_Time
}{
	ID:                  whereHelperstring{field: "\"ingest\".\"crawl_mode_changes\".\"id\""},
	SourceID:            whereHelperstring{field: "\"ingest\".\"crawl_mode_changes\".\"source_id\""},
	ProjectID:           whereHelperstring{field: "\"ingest\".\"crawl_mode_changes\".\"project_id\""},
	TriggerType:         whereHelperTriggerType{field: "\"ingest\".\"crawl_mode_changes\".\"trigger_type\""},
	FromMode:            whereHelperCrawlMode{field: "\"ingest\".\"crawl_mode_changes\".\"from_mode\""},
	ToMode:              whereHelperCrawlMode{field: "\"ingest\".\"crawl_mode_changes\".\"to_mode\""},
	FromIntervalMinutes: whereHelperint{field: "\"ingest\".\"crawl_mode_changes\".\"from_interval_minutes\""},
	ToIntervalMinutes:   whereHelperint{field: "\"ingest\".\"crawl_mode_changes\".\"to_interval_minutes\""},
	Reason:              whereHelpernull_String{field: "\"ingest\".\"crawl_mode_changes\".\"reason\""},
	EventRef:            whereHelpernull_String{field: "\"ingest\".\"crawl_mode_changes\".\"event_ref\""},
	TriggeredBy:         whereHelpernull_String{field: "\"ingest\".\"crawl_mode_changes\".\"triggered_by\""},
	TriggeredAt:         whereHelpertime_Time{field: "\"ingest\".\"crawl_mode_changes\".\"triggered_at\""},
	CreatedAt:           whereHelpertime_Time{field: "\"ingest\".\"crawl_mode_changes\".\"created_at\""},
}

// CrawlModeChangeRels is where relationship names are stored.
var CrawlModeChangeRels = struct {
	Source string
}{
	Source: "Source",
}

// crawlModeChangeR is where relationships are stored.
type crawlModeChangeR struct {
	Source *DataSource `boil:"Source" json:"Source" toml:"Source" yaml:"Source"`
}

// NewStruct creates a new relationship struct
func (*crawlModeChangeR) NewStruct() *crawlModeChangeR {
	return &crawlModeChangeR{}
}

func (o *CrawlModeChange) GetSource() *DataSource {
	if o == nil {
		return nil
	}

	return o.R.GetSource()
}

func (r *crawlModeChangeR) GetSource() *DataSource {
	if r == nil {
		return nil
	}

	return r.Source
}

// crawlModeChangeL is where Load methods for each relationship are stored.
type crawlModeChangeL struct{}

var (
	crawlModeChangeAllColumns            = []string{"id", "source_id", "project_id", "trigger_type", "from_mode", "to_mode", "from_interval_minutes", "to_interval_minutes", "reason", "event_ref", "triggered_by", "triggered_at", "created_at"}
	crawlModeChangeColumnsWithoutDefault = []string{"id", "source_id", "project_id", "trigger_type", "from_mode", "to_mode", "from_interval_minutes", "to_interval_minutes"}
	crawlModeChangeColumnsWithDefault    = []string{"reason", "event_ref", "triggered_by", "triggered_at", "created_at"}
	crawlModeChangePrimaryKeyColumns     = []string{"id"}
	crawlModeChangeGeneratedColumns      = []string{}
)

type (
	// CrawlModeChangeSlice is an alias for a slice of pointers to CrawlModeChange.
	// This should almost always be used instead of []CrawlModeChange.
	CrawlModeChangeSlice []*CrawlModeChange
	// CrawlModeChangeHook is the signature for custom CrawlModeChange hook methods
	CrawlModeChangeHook func(context.Context, boil.ContextExecutor, *CrawlModeChange) error

	crawlModeChangeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	crawlModeChangeType                 = reflect.TypeOf(&CrawlModeChange{})
	crawlModeChangeMapping              = queries.MakeStructMapping(crawlModeChangeType)
	crawlModeChangePrimaryKeyMapping, _ = queries.BindMapping(crawlModeChangeType, crawlModeChangeMapping, crawlModeChangePrimaryKeyColumns)
	crawlModeChangeInsertCacheMut       sync.RWMutex
	crawlModeChangeInsertCache          = make(map[string]insertCache)
	crawlModeChangeUpdateCacheMut       sync.RWMutex
	crawlModeChangeUpdateCache          = make(map[string]updateCache)
	crawlModeChangeUpsertCacheMut       sync.RWMutex
	crawlModeChangeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var crawlModeChangeAfterSelectMu sync.Mutex
var crawlModeChangeAfterSelectHooks []CrawlModeChangeHook

var crawlModeChangeBeforeInsertMu sync.Mutex
var crawlModeChangeBeforeInsertHooks []CrawlModeChangeHook
var crawlModeChangeAfterInsertMu sync.Mutex
var crawlModeChangeAfterInsertHooks []CrawlModeChangeHook

var crawlModeChangeBeforeUpdateMu sync.Mutex
var crawlModeChangeBeforeUpdateHooks []CrawlModeChangeHook
var crawlModeChangeAfterUpdateMu sync.Mutex
var crawlModeChangeAfterUpdateHooks []CrawlModeChangeHook

var crawlModeChangeBeforeDeleteMu sync.Mutex
var crawlModeChangeBeforeDeleteHooks []CrawlModeChangeHook
var crawlModeChangeAfterDeleteMu sync.Mutex
var crawlModeChangeAfterDeleteHooks []CrawlModeChangeHook

var crawlModeChangeBeforeUpsertMu sync.Mutex
var crawlModeChangeBeforeUpsertHooks []CrawlModeChangeHook
var crawlModeChangeAfterUpsertMu sync.Mutex
var crawlModeChangeAfterUpsertHooks []CrawlModeChangeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CrawlModeChange) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CrawlModeChange) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CrawlModeChange) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CrawlModeChange) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CrawlModeChange) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CrawlModeChange) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CrawlModeChange) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CrawlModeChange) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CrawlModeChange) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeChangeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCrawlModeChangeHook registers your hook function for all future operations.
func AddCrawlModeChangeHook(hookPoint boil.HookPoint, crawlModeChangeHook CrawlModeChangeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		crawlModeChangeAfterSelectMu.Lock()
		crawlModeChangeAfterSelectHooks = append(crawlModeChangeAfterSelectHooks, crawlModeChangeHook)
		crawlModeChangeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		crawlModeChangeBeforeInsertMu.Lock()
		crawlModeChangeBeforeInsertHooks = append(crawlModeChangeBeforeInsertHooks, crawlModeChangeHook)
		crawlModeChangeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		crawlModeChangeAfterInsertMu.Lock()
		crawlModeChangeAfterInsertHooks = append(crawlModeChangeAfterInsertHooks, crawlModeChangeHook)
		crawlModeChangeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		crawlModeChangeBeforeUpdateMu.Lock()
		crawlModeChangeBeforeUpdateHooks = append(crawlModeChangeBeforeUpdateHooks, crawlModeChangeHook)
		crawlModeChangeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		crawlModeChangeAfterUpdateMu.Lock()
		crawlModeChangeAfterUpdateHooks = append(crawlModeChangeAfterUpdateHooks, crawlModeChangeHook)
		crawlModeChangeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		crawlModeChangeBeforeDeleteMu.Lock()
		crawlModeChangeBeforeDeleteHooks = append(crawlModeChangeBeforeDeleteHooks, crawlModeChangeHook)
		crawlModeChangeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		crawlModeChangeAfterDeleteMu.Lock()
		crawlModeChangeAfterDeleteHooks = append(crawlModeChangeAfterDeleteHooks, crawlModeChangeHook)
		crawlModeChangeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		crawlModeChangeBeforeUpsertMu.Lock()
		crawlModeChangeBeforeUpsertHooks = append(crawlModeChangeBeforeUpsertHooks, crawlModeChangeHook)
		crawlModeChangeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		crawlModeChangeAfterUpsertMu.Lock()
		crawlModeChangeAfterUpsertHooks = append(crawlModeChangeAfterUpsertHooks, crawlModeChangeHook)
		crawlModeChangeAfterUpsertMu.Unlock()
	}
}

// One returns a single crawlModeChange record from the query.
func (q crawlModeChangeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CrawlModeChange, error) {
	o := &CrawlModeChange{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for crawl_mode_changes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CrawlModeChange records from the query.
func (q crawlModeChangeQuery) All(ctx context.Context, exec boil.ContextExecutor) (CrawlModeChangeSlice, error) {
	var o []*CrawlModeChange

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to CrawlModeChange slice")
	}

	if len(crawlModeChangeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CrawlModeChange records in the query.
func (q crawlModeChangeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count crawl_mode_changes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q crawlModeChangeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if crawl_mode_changes exists")
	}

	return count > 0, nil
}

// Source pointed to by the foreign key.
func (o *CrawlModeChange) Source(mods ...qm.QueryMod) dataSourceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SourceID),
	}

	queryMods = append(queryMods, mods...)

	return DataSources(queryMods...)
}

// LoadSource allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (crawlModeChangeL) LoadSource(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCrawlModeChange any, mods queries.Applicator) error {
	var slice []*CrawlModeChange
	var object *CrawlModeChange

	if singular {
		var ok bool
		object, ok = maybeCrawlModeChange.(*CrawlModeChange)
		if !ok {
			object = new(CrawlModeChange)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCrawlModeChange)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCrawlModeChange))
			}
		}
	} else {
		s, ok := maybeCrawlModeChange.(*[]*CrawlModeChange)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCrawlModeChange)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCrawlModeChange))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &crawlModeChangeR{}
		}
		args[object.SourceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &crawlModeChangeR{}
			}

			args[obj.SourceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.data_sources`),
		qm.WhereIn(`ingest.data_sources.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`ingest.data_sources.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataSource")
	}

	var resultSlice []*DataSource
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataSource")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_sources")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_sources")
	}

	if len(dataSourceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Source = foreign
		if foreign.R == nil {
			foreign.R = &dataSourceR{}
		}
		foreign.R.SourceCrawlModeChanges = append(foreign.R.SourceCrawlModeChanges, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SourceID == foreign.ID {
				local.R.Source = foreign
				if foreign.R == nil {
					foreign.R = &dataSourceR{}
				}
				foreign.R.SourceCrawlModeChanges = append(foreign.R.SourceCrawlModeChanges, local)
				break
			}
		}
	}

	return nil
}

// SetSource of the crawlModeChange to the related item.
// Sets o.R.Source to related.
// Adds o to related.R.SourceCrawlModeChanges.
func (o *CrawlModeChange) SetSource(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataSource) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ingest\".\"crawl_mode_changes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
		strmangle.WhereClause("\"", "\"", 2, crawlModeChangePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SourceID = related.ID
	if o.R == nil {
		o.R = &crawlModeChangeR{
			Source: related,
		}
	} else {
		o.R.Source = related
	}

	if related.R == nil {
		related.R = &dataSourceR{
			SourceCrawlModeChanges: CrawlModeChangeSlice{o},
		}
	} else {
		related.R.SourceCrawlModeChanges = append(related.R.SourceCrawlModeChanges, o)
	}

	return nil
}

// CrawlModeChanges retrieves all the records using an executor.
func CrawlModeChanges(mods ...qm.QueryMod) crawlModeChangeQuery {
	mods = append(mods, qm.From("\"ingest\".\"crawl_mode_changes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ingest\".\"crawl_mode_changes\".*"})
	}

	return crawlModeChangeQuery{q}
}

// FindCrawlModeChange retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCrawlModeChange(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*CrawlModeChange, error) {
	crawlModeChangeObj := &CrawlModeChange{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ingest\".\"crawl_mode_changes\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, crawlModeChangeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from crawl_mode_changes")
	}

	if err = crawlModeChangeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return crawlModeChangeObj, err
	}

	return crawlModeChangeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CrawlModeChange) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no crawl_mode_changes provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(crawlModeChangeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	crawlModeChangeInsertCacheMut.RLock()
	cache, cached := crawlModeChangeInsertCache[key]
	crawlModeChangeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			crawlModeChangeAllColumns,
			crawlModeChangeColumnsWithDefault,
			crawlModeChangeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(crawlModeChangeType, crawlModeChangeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(crawlModeChangeType, crawlModeChangeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ingest\".\"crawl_mode_changes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ingest\".\"crawl_mode_changes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into crawl_mode_changes")
	}

	if !cached {
		crawlModeChangeInsertCacheMut.Lock()
		crawlModeChangeInsertCache[key] = cache
		crawlModeChangeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CrawlModeChange.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CrawlModeChange) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	crawlModeChangeUpdateCacheMut.RLock()
	cache, cached := crawlModeChangeUpdateCache[key]
	crawlModeChangeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			crawlModeChangeAllColumns,
			crawlModeChangePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update crawl_mode_changes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ingest\".\"crawl_mode_changes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, crawlModeChangePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(crawlModeChangeType, crawlModeChangeMapping, append(wl, crawlModeChangePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update crawl_mode_changes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for crawl_mode_changes")
	}

	if !cached {
		crawlModeChangeUpdateCacheMut.Lock()
		crawlModeChangeUpdateCache[key] = cache
		crawlModeChangeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q crawlModeChangeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for crawl_mode_changes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for crawl_mode_changes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CrawlModeChangeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlModeChangePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ingest\".\"crawl_mode_changes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, crawlModeChangePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in crawlModeChange slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all crawlModeChange")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CrawlModeChange) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no crawl_mode_changes provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(crawlModeChangeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	crawlModeChangeUpsertCacheMut.RLock()
	cache, cached := crawlModeChangeUpsertCache[key]
	crawlModeChangeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			crawlModeChangeAllColumns,
			crawlModeChangeColumnsWithDefault,
			crawlModeChangeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			crawlModeChangeAllColumns,
			crawlModeChangePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert crawl_mode_changes, could not build update column list")
		}

		ret := strmangle.SetComplement(crawlModeChangeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(crawlModeChangePrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert crawl_mode_changes, could not build conflict column list")
			}

			conflict = make([]string, len(crawlModeChangePrimaryKeyColumns))
			copy(conflict, crawlModeChangePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ingest\".\"crawl_mode_changes\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(crawlModeChangeType, crawlModeChangeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(crawlModeChangeType, crawlModeChangeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert crawl_mode_changes")
	}

	if !cached {
		crawlModeChangeUpsertCacheMut.Lock()
		crawlModeChangeUpsertCache[key] = cache
		crawlModeChangeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CrawlModeChange record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CrawlModeChange) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no CrawlModeChange provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), crawlModeChangePrimaryKeyMapping)
	sql := "DELETE FROM \"ingest\".\"crawl_mode_changes\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from crawl_mode_changes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for crawl_mode_changes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q crawlModeChangeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no crawlModeChangeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from crawl_mode_changes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for crawl_mode_changes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CrawlModeChangeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(crawlModeChangeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlModeChangePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ingest\".\"crawl_mode_changes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, crawlModeChangePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from crawlModeChange slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for crawl_mode_changes")
	}

	if len(crawlModeChangeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CrawlModeChange) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCrawlModeChange(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CrawlModeChangeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CrawlModeChangeSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlModeChangePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ingest\".\"crawl_mode_changes\".* FROM \"ingest\".\"crawl_mode_changes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, crawlModeChangePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in CrawlModeChangeSlice")
	}

	*o = slice

	return nil
}

// CrawlModeChangeExists checks if the CrawlModeChange row exists.
func CrawlModeChangeExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ingest\".\"crawl_mode_changes\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if crawl_mode_changes exists")
	}

	return exists, nil
}

// Exists checks if the CrawlModeChange row exists.
func (o *CrawlModeChange) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CrawlModeChangeExists(ctx, exec, o.ID)
}
