// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// CrawlModeDefault is an object representing the database table.
type CrawlModeDefault struct {
	Mode            CrawlMode     `boil:"mode" json:"mode" toml:"mode" yaml:"mode"`
	IntervalMinutes int           `boil:"interval_minutes" json:"interval_minutes" toml:"interval_minutes" yaml:"interval_minutes"`
	ModeMultiplier  types.Decimal `boil:"mode_multiplier" json:"mode_multiplier" toml:"mode_multiplier" yaml:"mode_multiplier"`
	Description     null.String   `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	CreatedAt       time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt       time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *crawlModeDefaultR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L crawlModeDefaultL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CrawlModeDefaultColumns = struct {
	Mode            string
	IntervalMinutes string
	ModeMultiplier  string
	Description     string
	CreatedAt       string
	UpdatedAt       string
}{
	Mode:            "mode",
	IntervalMinutes: "interval_minutes",
	ModeMultiplier:  "mode_multiplier",
	Description:     "description",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
}

var CrawlModeDefaultTableColumns = struct {
	Mode            string
	IntervalMinutes string
	ModeMultiplier  string
	Description     string
	CreatedAt       string
	UpdatedAt       string
}{
	Mode:            "crawl_mode_defaults.mode",
	IntervalMinutes: "crawl_mode_defaults.interval_minutes",
	ModeMultiplier:  "crawl_mode_defaults.mode_multiplier",
	Description:     "crawl_mode_defaults.description",
	CreatedAt:       "crawl_mode_defaults.created_at",
	UpdatedAt:       "crawl_mode_defaults.updated_at",
}

// Generated where

type whereHelpertypes_Decimal struct{ field string }

func (w whereHelpertypes_Decimal) EQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_Decimal) NEQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_Decimal) LT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_Decimal) LTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_Decimal) GT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_Decimal) GTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var CrawlModeDefaultWhere = struct {
	Mode            whereHelperCrawlMode
	IntervalMinutes whereHelperint
	ModeMultiplier  whereHelpertypes_Decimal
	Description     whereHelpernull_String
	CreatedAt       whereHelpertime_Time
	UpdatedAt       whereHelpertime_Time
}{
	Mode:            whereHelperCrawlMode{field: "\"ingest\".\"crawl_mode_defaults\".\"mode\""},
	IntervalMinutes: whereHelperint{field: "\"ingest\".\"crawl_mode_defaults\".\"interval_minutes\""},
	ModeMultiplier:  whereHelpertypes_Decimal{field: "\"ingest\".\"crawl_mode_defaults\".\"mode_multiplier\""},
	Description:     whereHelpernull_String{field: "\"ingest\".\"crawl_mode_defaults\".\"description\""},
	CreatedAt:       whereHelpertime_Time{field: "\"ingest\".\"crawl_mode_defaults\".\"created_at\""},
	UpdatedAt:       whereHelpertime_Time{field: "\"ingest\".\"crawl_mode_defaults\".\"updated_at\""},
}

// CrawlModeDefaultRels is where relationship names are stored.
var CrawlModeDefaultRels = struct {
}{}

// crawlModeDefaultR is where relationships are stored.
type crawlModeDefaultR struct {
}

// NewStruct creates a new relationship struct
func (*crawlModeDefaultR) NewStruct() *crawlModeDefaultR {
	return &crawlModeDefaultR{}
}

// crawlModeDefaultL is where Load methods for each relationship are stored.
type crawlModeDefaultL struct{}

var (
	crawlModeDefaultAllColumns            = []string{"mode", "interval_minutes", "mode_multiplier", "description", "created_at", "updated_at"}
	crawlModeDefaultColumnsWithoutDefault = []string{"mode", "interval_minutes"}
	crawlModeDefaultColumnsWithDefault    = []string{"mode_multiplier", "description", "created_at", "updated_at"}
	crawlModeDefaultPrimaryKeyColumns     = []string{"mode"}
	crawlModeDefaultGeneratedColumns      = []string{}
)

type (
	// CrawlModeDefaultSlice is an alias for a slice of pointers to CrawlModeDefault.
	// This should almost always be used instead of []CrawlModeDefault.
	CrawlModeDefaultSlice []*CrawlModeDefault
	// CrawlModeDefaultHook is the signature for custom CrawlModeDefault hook methods
	CrawlModeDefaultHook func(context.Context, boil.ContextExecutor, *CrawlModeDefault) error

	crawlModeDefaultQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	crawlModeDefaultType                 = reflect.TypeOf(&CrawlModeDefault{})
	crawlModeDefaultMapping              = queries.MakeStructMapping(crawlModeDefaultType)
	crawlModeDefaultPrimaryKeyMapping, _ = queries.BindMapping(crawlModeDefaultType, crawlModeDefaultMapping, crawlModeDefaultPrimaryKeyColumns)
	crawlModeDefaultInsertCacheMut       sync.RWMutex
	crawlModeDefaultInsertCache          = make(map[string]insertCache)
	crawlModeDefaultUpdateCacheMut       sync.RWMutex
	crawlModeDefaultUpdateCache          = make(map[string]updateCache)
	crawlModeDefaultUpsertCacheMut       sync.RWMutex
	crawlModeDefaultUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var crawlModeDefaultAfterSelectMu sync.Mutex
var crawlModeDefaultAfterSelectHooks []CrawlModeDefaultHook

var crawlModeDefaultBeforeInsertMu sync.Mutex
var crawlModeDefaultBeforeInsertHooks []CrawlModeDefaultHook
var crawlModeDefaultAfterInsertMu sync.Mutex
var crawlModeDefaultAfterInsertHooks []CrawlModeDefaultHook

var crawlModeDefaultBeforeUpdateMu sync.Mutex
var crawlModeDefaultBeforeUpdateHooks []CrawlModeDefaultHook
var crawlModeDefaultAfterUpdateMu sync.Mutex
var crawlModeDefaultAfterUpdateHooks []CrawlModeDefaultHook

var crawlModeDefaultBeforeDeleteMu sync.Mutex
var crawlModeDefaultBeforeDeleteHooks []CrawlModeDefaultHook
var crawlModeDefaultAfterDeleteMu sync.Mutex
var crawlModeDefaultAfterDeleteHooks []CrawlModeDefaultHook

var crawlModeDefaultBeforeUpsertMu sync.Mutex
var crawlModeDefaultBeforeUpsertHooks []CrawlModeDefaultHook
var crawlModeDefaultAfterUpsertMu sync.Mutex
var crawlModeDefaultAfterUpsertHooks []CrawlModeDefaultHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CrawlModeDefault) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CrawlModeDefault) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CrawlModeDefault) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CrawlModeDefault) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CrawlModeDefault) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CrawlModeDefault) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CrawlModeDefault) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CrawlModeDefault) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CrawlModeDefault) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range crawlModeDefaultAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCrawlModeDefaultHook registers your hook function for all future operations.
func AddCrawlModeDefaultHook(hookPoint boil.HookPoint, crawlModeDefaultHook CrawlModeDefaultHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		crawlModeDefaultAfterSelectMu.Lock()
		crawlModeDefaultAfterSelectHooks = append(crawlModeDefaultAfterSelectHooks, crawlModeDefaultHook)
		crawlModeDefaultAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		crawlModeDefaultBeforeInsertMu.Lock()
		crawlModeDefaultBeforeInsertHooks = append(crawlModeDefaultBeforeInsertHooks, crawlModeDefaultHook)
		crawlModeDefaultBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		crawlModeDefaultAfterInsertMu.Lock()
		crawlModeDefaultAfterInsertHooks = append(crawlModeDefaultAfterInsertHooks, crawlModeDefaultHook)
		crawlModeDefaultAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		crawlModeDefaultBeforeUpdateMu.Lock()
		crawlModeDefaultBeforeUpdateHooks = append(crawlModeDefaultBeforeUpdateHooks, crawlModeDefaultHook)
		crawlModeDefaultBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		crawlModeDefaultAfterUpdateMu.Lock()
		crawlModeDefaultAfterUpdateHooks = append(crawlModeDefaultAfterUpdateHooks, crawlModeDefaultHook)
		crawlModeDefaultAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		crawlModeDefaultBeforeDeleteMu.Lock()
		crawlModeDefaultBeforeDeleteHooks = append(crawlModeDefaultBeforeDeleteHooks, crawlModeDefaultHook)
		crawlModeDefaultBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		crawlModeDefaultAfterDeleteMu.Lock()
		crawlModeDefaultAfterDeleteHooks = append(crawlModeDefaultAfterDeleteHooks, crawlModeDefaultHook)
		crawlModeDefaultAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		crawlModeDefaultBeforeUpsertMu.Lock()
		crawlModeDefaultBeforeUpsertHooks = append(crawlModeDefaultBeforeUpsertHooks, crawlModeDefaultHook)
		crawlModeDefaultBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		crawlModeDefaultAfterUpsertMu.Lock()
		crawlModeDefaultAfterUpsertHooks = append(crawlModeDefaultAfterUpsertHooks, crawlModeDefaultHook)
		crawlModeDefaultAfterUpsertMu.Unlock()
	}
}

// One returns a single crawlModeDefault record from the query.
func (q crawlModeDefaultQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CrawlModeDefault, error) {
	o := &CrawlModeDefault{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for crawl_mode_defaults")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CrawlModeDefault records from the query.
func (q crawlModeDefaultQuery) All(ctx context.Context, exec boil.ContextExecutor) (CrawlModeDefaultSlice, error) {
	var o []*CrawlModeDefault

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to CrawlModeDefault slice")
	}

	if len(crawlModeDefaultAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CrawlModeDefault records in the query.
func (q crawlModeDefaultQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count crawl_mode_defaults rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q crawlModeDefaultQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if crawl_mode_defaults exists")
	}

	return count > 0, nil
}

// CrawlModeDefaults retrieves all the records using an executor.
func CrawlModeDefaults(mods ...qm.QueryMod) crawlModeDefaultQuery {
	mods = append(mods, qm.From("\"ingest\".\"crawl_mode_defaults\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ingest\".\"crawl_mode_defaults\".*"})
	}

	return crawlModeDefaultQuery{q}
}

// FindCrawlModeDefault retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCrawlModeDefault(ctx context.Context, exec boil.ContextExecutor, mode CrawlMode, selectCols ...string) (*CrawlModeDefault, error) {
	crawlModeDefaultObj := &CrawlModeDefault{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ingest\".\"crawl_mode_defaults\" where \"mode\"=$1", sel,
	)

	q := queries.Raw(query, mode)

	err := q.Bind(ctx, exec, crawlModeDefaultObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from crawl_mode_defaults")
	}

	if err = crawlModeDefaultObj.doAfterSelectHooks(ctx, exec); err != nil {
		return crawlModeDefaultObj, err
	}

	return crawlModeDefaultObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CrawlModeDefault) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no crawl_mode_defaults provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(crawlModeDefaultColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	crawlModeDefaultInsertCacheMut.RLock()
	cache, cached := crawlModeDefaultInsertCache[key]
	crawlModeDefaultInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			crawlModeDefaultAllColumns,
			crawlModeDefaultColumnsWithDefault,
			crawlModeDefaultColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(crawlModeDefaultType, crawlModeDefaultMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(crawlModeDefaultType, crawlModeDefaultMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ingest\".\"crawl_mode_defaults\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ingest\".\"crawl_mode_defaults\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into crawl_mode_defaults")
	}

	if !cached {
		crawlModeDefaultInsertCacheMut.Lock()
		crawlModeDefaultInsertCache[key] = cache
		crawlModeDefaultInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CrawlModeDefault.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CrawlModeDefault) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	crawlModeDefaultUpdateCacheMut.RLock()
	cache, cached := crawlModeDefaultUpdateCache[key]
	crawlModeDefaultUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			crawlModeDefaultAllColumns,
			crawlModeDefaultPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update crawl_mode_defaults, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ingest\".\"crawl_mode_defaults\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, crawlModeDefaultPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(crawlModeDefaultType, crawlModeDefaultMapping, append(wl, crawlModeDefaultPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update crawl_mode_defaults row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for crawl_mode_defaults")
	}

	if !cached {
		crawlModeDefaultUpdateCacheMut.Lock()
		crawlModeDefaultUpdateCache[key] = cache
		crawlModeDefaultUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q crawlModeDefaultQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for crawl_mode_defaults")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for crawl_mode_defaults")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CrawlModeDefaultSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlModeDefaultPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ingest\".\"crawl_mode_defaults\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, crawlModeDefaultPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in crawlModeDefault slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all crawlModeDefault")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CrawlModeDefault) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no crawl_mode_defaults provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(crawlModeDefaultColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	crawlModeDefaultUpsertCacheMut.RLock()
	cache, cached := crawlModeDefaultUpsertCache[key]
	crawlModeDefaultUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			crawlModeDefaultAllColumns,
			crawlModeDefaultColumnsWithDefault,
			crawlModeDefaultColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			crawlModeDefaultAllColumns,
			crawlModeDefaultPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert crawl_mode_defaults, could not build update column list")
		}

		ret := strmangle.SetComplement(crawlModeDefaultAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(crawlModeDefaultPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert crawl_mode_defaults, could not build conflict column list")
			}

			conflict = make([]string, len(crawlModeDefaultPrimaryKeyColumns))
			copy(conflict, crawlModeDefaultPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ingest\".\"crawl_mode_defaults\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(crawlModeDefaultType, crawlModeDefaultMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(crawlModeDefaultType, crawlModeDefaultMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert crawl_mode_defaults")
	}

	if !cached {
		crawlModeDefaultUpsertCacheMut.Lock()
		crawlModeDefaultUpsertCache[key] = cache
		crawlModeDefaultUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CrawlModeDefault record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CrawlModeDefault) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no CrawlModeDefault provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), crawlModeDefaultPrimaryKeyMapping)
	sql := "DELETE FROM \"ingest\".\"crawl_mode_defaults\" WHERE \"mode\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from crawl_mode_defaults")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for crawl_mode_defaults")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q crawlModeDefaultQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no crawlModeDefaultQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from crawl_mode_defaults")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for crawl_mode_defaults")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CrawlModeDefaultSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(crawlModeDefaultBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlModeDefaultPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ingest\".\"crawl_mode_defaults\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, crawlModeDefaultPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from crawlModeDefault slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for crawl_mode_defaults")
	}

	if len(crawlModeDefaultAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CrawlModeDefault) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCrawlModeDefault(ctx, exec, o.Mode)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CrawlModeDefaultSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CrawlModeDefaultSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), crawlModeDefaultPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ingest\".\"crawl_mode_defaults\".* FROM \"ingest\".\"crawl_mode_defaults\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, crawlModeDefaultPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in CrawlModeDefaultSlice")
	}

	*o = slice

	return nil
}

// CrawlModeDefaultExists checks if the CrawlModeDefault row exists.
func CrawlModeDefaultExists(ctx context.Context, exec boil.ContextExecutor, mode CrawlMode) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ingest\".\"crawl_mode_defaults\" where \"mode\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, mode)
	}
	row := exec.QueryRowContext(ctx, sql, mode)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if crawl_mode_defaults exists")
	}

	return exists, nil
}

// Exists checks if the CrawlModeDefault row exists.
func (o *CrawlModeDefault) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CrawlModeDefaultExists(ctx, exec, o.Mode)
}
