// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DataSource is an object representing the database table.
type DataSource struct {
	ID                     string           `boil:"id" json:"id" toml:"id" yaml:"id"`
	ProjectID              string           `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	Name                   string           `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description            null.String      `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	SourceType             SourceType       `boil:"source_type" json:"source_type" toml:"source_type" yaml:"source_type"`
	SourceCategory         SourceCategory   `boil:"source_category" json:"source_category" toml:"source_category" yaml:"source_category"`
	Status                 SourceStatus     `boil:"status" json:"status" toml:"status" yaml:"status"`
	Config                 types.JSON       `boil:"config" json:"config" toml:"config" yaml:"config"`
	AccountRef             null.JSON        `boil:"account_ref" json:"account_ref,omitempty" toml:"account_ref" yaml:"account_ref,omitempty"`
	MappingRules           null.JSON        `boil:"mapping_rules" json:"mapping_rules,omitempty" toml:"mapping_rules" yaml:"mapping_rules,omitempty"`
	OnboardingStatus       OnboardingStatus `boil:"onboarding_status" json:"onboarding_status" toml:"onboarding_status" yaml:"onboarding_status"`
	DryrunStatus           DryrunStatus     `boil:"dryrun_status" json:"dryrun_status" toml:"dryrun_status" yaml:"dryrun_status"`
	DryrunLastResultID     null.String      `boil:"dryrun_last_result_id" json:"dryrun_last_result_id,omitempty" toml:"dryrun_last_result_id" yaml:"dryrun_last_result_id,omitempty"`
	CrawlMode              NullCrawlMode    `boil:"crawl_mode" json:"crawl_mode,omitempty" toml:"crawl_mode" yaml:"crawl_mode,omitempty"`
	CrawlIntervalMinutes   null.Int         `boil:"crawl_interval_minutes" json:"crawl_interval_minutes,omitempty" toml:"crawl_interval_minutes" yaml:"crawl_interval_minutes,omitempty"`
	NextCrawlAt            null.Time        `boil:"next_crawl_at" json:"next_crawl_at,omitempty" toml:"next_crawl_at" yaml:"next_crawl_at,omitempty"`
	LastCrawlAt            null.Time        `boil:"last_crawl_at" json:"last_crawl_at,omitempty" toml:"last_crawl_at" yaml:"last_crawl_at,omitempty"`
	LastSuccessAt          null.Time        `boil:"last_success_at" json:"last_success_at,omitempty" toml:"last_success_at" yaml:"last_success_at,omitempty"`
	LastErrorAt            null.Time        `boil:"last_error_at" json:"last_error_at,omitempty" toml:"last_error_at" yaml:"last_error_at,omitempty"`
	LastErrorMessage       null.String      `boil:"last_error_message" json:"last_error_message,omitempty" toml:"last_error_message" yaml:"last_error_message,omitempty"`
	WebhookID              null.String      `boil:"webhook_id" json:"webhook_id,omitempty" toml:"webhook_id" yaml:"webhook_id,omitempty"`
	WebhookSecretEncrypted null.String      `boil:"webhook_secret_encrypted" json:"webhook_secret_encrypted,omitempty" toml:"webhook_secret_encrypted" yaml:"webhook_secret_encrypted,omitempty"`
	CreatedBy              null.String      `boil:"created_by" json:"created_by,omitempty" toml:"created_by" yaml:"created_by,omitempty"`
	ActivatedAt            null.Time        `boil:"activated_at" json:"activated_at,omitempty" toml:"activated_at" yaml:"activated_at,omitempty"`
	PausedAt               null.Time        `boil:"paused_at" json:"paused_at,omitempty" toml:"paused_at" yaml:"paused_at,omitempty"`
	ArchivedAt             null.Time        `boil:"archived_at" json:"archived_at,omitempty" toml:"archived_at" yaml:"archived_at,omitempty"`
	CreatedAt              time.Time        `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt              time.Time        `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt              null.Time        `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *dataSourceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dataSourceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DataSourceColumns = struct {
	ID                     string
	ProjectID              string
	Name                   string
	Description            string
	SourceType             string
	SourceCategory         string
	Status                 string
	Config                 string
	AccountRef             string
	MappingRules           string
	OnboardingStatus       string
	DryrunStatus           string
	DryrunLastResultID     string
	CrawlMode              string
	CrawlIntervalMinutes   string
	NextCrawlAt            string
	LastCrawlAt            string
	LastSuccessAt          string
	LastErrorAt            string
	LastErrorMessage       string
	WebhookID              string
	WebhookSecretEncrypted string
	CreatedBy              string
	ActivatedAt            string
	PausedAt               string
	ArchivedAt             string
	CreatedAt              string
	UpdatedAt              string
	DeletedAt              string
}{
	ID:                     "id",
	ProjectID:              "project_id",
	Name:                   "name",
	Description:            "description",
	SourceType:             "source_type",
	SourceCategory:         "source_category",
	Status:                 "status",
	Config:                 "config",
	AccountRef:             "account_ref",
	MappingRules:           "mapping_rules",
	OnboardingStatus:       "onboarding_status",
	DryrunStatus:           "dryrun_status",
	DryrunLastResultID:     "dryrun_last_result_id",
	CrawlMode:              "crawl_mode",
	CrawlIntervalMinutes:   "crawl_interval_minutes",
	NextCrawlAt:            "next_crawl_at",
	LastCrawlAt:            "last_crawl_at",
	LastSuccessAt:          "last_success_at",
	LastErrorAt:            "last_error_at",
	LastErrorMessage:       "last_error_message",
	WebhookID:              "webhook_id",
	WebhookSecretEncrypted: "webhook_secret_encrypted",
	CreatedBy:              "created_by",
	ActivatedAt:            "activated_at",
	PausedAt:               "paused_at",
	ArchivedAt:             "archived_at",
	CreatedAt:              "created_at",
	UpdatedAt:              "updated_at",
	DeletedAt:              "deleted_at",
}

var DataSourceTableColumns = struct {
	ID                     string
	ProjectID              string
	Name                   string
	Description            string
	SourceType             string
	SourceCategory         string
	Status                 string
	Config                 string
	AccountRef             string
	MappingRules           string
	OnboardingStatus       string
	DryrunStatus           string
	DryrunLastResultID     string
	CrawlMode              string
	CrawlIntervalMinutes   string
	NextCrawlAt            string
	LastCrawlAt            string
	LastSuccessAt          string
	LastErrorAt            string
	LastErrorMessage       string
	WebhookID              string
	WebhookSecretEncrypted string
	CreatedBy              string
	ActivatedAt            string
	PausedAt               string
	ArchivedAt             string
	CreatedAt              string
	UpdatedAt              string
	DeletedAt              string
}{
	ID:                     "data_sources.id",
	ProjectID:              "data_sources.project_id",
	Name:                   "data_sources.name",
	Description:            "data_sources.description",
	SourceType:             "data_sources.source_type",
	SourceCategory:         "data_sources.source_category",
	Status:                 "data_sources.status",
	Config:                 "data_sources.config",
	AccountRef:             "data_sources.account_ref",
	MappingRules:           "data_sources.mapping_rules",
	OnboardingStatus:       "data_sources.onboarding_status",
	DryrunStatus:           "data_sources.dryrun_status",
	DryrunLastResultID:     "data_sources.dryrun_last_result_id",
	CrawlMode:              "data_sources.crawl_mode",
	CrawlIntervalMinutes:   "data_sources.crawl_interval_minutes",
	NextCrawlAt:            "data_sources.next_crawl_at",
	LastCrawlAt:            "data_sources.last_crawl_at",
	LastSuccessAt:          "data_sources.last_success_at",
	LastErrorAt:            "data_sources.last_error_at",
	LastErrorMessage:       "data_sources.last_error_message",
	WebhookID:              "data_sources.webhook_id",
	WebhookSecretEncrypted: "data_sources.webhook_secret_encrypted",
	CreatedBy:              "data_sources.created_by",
	ActivatedAt:            "data_sources.activated_at",
	PausedAt:               "data_sources.paused_at",
	ArchivedAt:             "data_sources.archived_at",
	CreatedAt:              "data_sources.created_at",
	UpdatedAt:              "data_sources.updated_at",
	DeletedAt:              "data_sources.deleted_at",
}

// Generated where

type whereHelperSourceType struct{ field string }

func (w whereHelperSourceType) EQ(x SourceType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperSourceType) NEQ(x SourceType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperSourceType) LT(x SourceType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperSourceType) LTE(x SourceType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperSourceType) GT(x SourceType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperSourceType) GTE(x SourceType) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperSourceType) IN(slice []SourceType) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperSourceType) NIN(slice []SourceType) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperSourceCategory struct{ field string }

func (w whereHelperSourceCategory) EQ(x SourceCategory) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperSourceCategory) NEQ(x SourceCategory) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperSourceCategory) LT(x SourceCategory) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperSourceCategory) LTE(x SourceCategory) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperSourceCategory) GT(x SourceCategory) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperSourceCategory) GTE(x SourceCategory) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperSourceCategory) IN(slice []SourceCategory) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperSourceCategory) NIN(slice []SourceCategory) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperSourceStatus struct{ field string }

func (w whereHelperSourceStatus) EQ(x SourceStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperSourceStatus) NEQ(x SourceStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperSourceStatus) LT(x SourceStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperSourceStatus) LTE(x SourceStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperSourceStatus) GT(x SourceStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperSourceStatus) GTE(x SourceStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperSourceStatus) IN(slice []SourceStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperSourceStatus) NIN(slice []SourceStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelperOnboardingStatus struct{ field string }

func (w whereHelperOnboardingStatus) EQ(x OnboardingStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperOnboardingStatus) NEQ(x OnboardingStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperOnboardingStatus) LT(x OnboardingStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperOnboardingStatus) LTE(x OnboardingStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperOnboardingStatus) GT(x OnboardingStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperOnboardingStatus) GTE(x OnboardingStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperOnboardingStatus) IN(slice []OnboardingStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperOnboardingStatus) NIN(slice []OnboardingStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperDryrunStatus struct{ field string }

func (w whereHelperDryrunStatus) EQ(x DryrunStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperDryrunStatus) NEQ(x DryrunStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperDryrunStatus) LT(x DryrunStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperDryrunStatus) LTE(x DryrunStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperDryrunStatus) GT(x DryrunStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperDryrunStatus) GTE(x DryrunStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperDryrunStatus) IN(slice []DryrunStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperDryrunStatus) NIN(slice []DryrunStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperNullCrawlMode struct{ field string }

func (w whereHelperNullCrawlMode) EQ(x NullCrawlMode) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelperNullCrawlMode) NEQ(x NullCrawlMode) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelperNullCrawlMode) LT(x NullCrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperNullCrawlMode) LTE(x NullCrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperNullCrawlMode) GT(x NullCrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperNullCrawlMode) GTE(x NullCrawlMode) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperNullCrawlMode) IN(slice []NullCrawlMode) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperNullCrawlMode) NIN(slice []NullCrawlMode) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelperNullCrawlMode) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelperNullCrawlMode) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var DataSourceWhere = struct {
	ID                     whereHelperstring
	ProjectID              whereHelperstring
	Name                   whereHelperstring
	Description            whereHelpernull_String
	SourceType             whereHelperSourceType
	SourceCategory         whereHelperSourceCategory
	Status                 whereHelperSourceStatus
	Config                 whereHelpertypes_JSON
	AccountRef             whereHelpernull_JSON
	MappingRules           whereHelpernull_JSON
	OnboardingStatus       whereHelperOnboardingStatus
	DryrunStatus           whereHelperDryrunStatus
	DryrunLastResultID     whereHelpernull_String
	CrawlMode              whereHelperNullCrawlMode
	CrawlIntervalMinutes   whereHelpernull_Int
	NextCrawlAt            whereHelpernull_Time
	LastCrawlAt            whereHelpernull_Time
	LastSuccessAt          whereHelpernull_Time
	LastErrorAt            whereHelpernull_Time
	LastErrorMessage       whereHelpernull_String
	WebhookID              whereHelpernull_String
	WebhookSecretEncrypted whereHelpernull_String
	CreatedBy              whereHelpernull_String
	ActivatedAt            whereHelpernull_Time
	PausedAt               whereHelpernull_Time
	ArchivedAt             whereHelpernull_Time
	CreatedAt              whereHelpertime_Time
	UpdatedAt              whereHelpertime_Time
	DeletedAt              whereHelpernull_Time
}{
	ID:                     whereHelperstring{field: "\"schema_ingest\".\"data_sources\".\"id\""},
	ProjectID:              whereHelperstring{field: "\"schema_ingest\".\"data_sources\".\"project_id\""},
	Name:                   whereHelperstring{field: "\"schema_ingest\".\"data_sources\".\"name\""},
	Description:            whereHelpernull_String{field: "\"schema_ingest\".\"data_sources\".\"description\""},
	SourceType:             whereHelperSourceType{field: "\"schema_ingest\".\"data_sources\".\"source_type\""},
	SourceCategory:         whereHelperSourceCategory{field: "\"schema_ingest\".\"data_sources\".\"source_category\""},
	Status:                 whereHelperSourceStatus{field: "\"schema_ingest\".\"data_sources\".\"status\""},
	Config:                 whereHelpertypes_JSON{field: "\"schema_ingest\".\"data_sources\".\"config\""},
	AccountRef:             whereHelpernull_JSON{field: "\"schema_ingest\".\"data_sources\".\"account_ref\""},
	MappingRules:           whereHelpernull_JSON{field: "\"schema_ingest\".\"data_sources\".\"mapping_rules\""},
	OnboardingStatus:       whereHelperOnboardingStatus{field: "\"schema_ingest\".\"data_sources\".\"onboarding_status\""},
	DryrunStatus:           whereHelperDryrunStatus{field: "\"schema_ingest\".\"data_sources\".\"dryrun_status\""},
	DryrunLastResultID:     whereHelpernull_String{field: "\"schema_ingest\".\"data_sources\".\"dryrun_last_result_id\""},
	CrawlMode:              whereHelperNullCrawlMode{field: "\"schema_ingest\".\"data_sources\".\"crawl_mode\""},
	CrawlIntervalMinutes:   whereHelpernull_Int{field: "\"schema_ingest\".\"data_sources\".\"crawl_interval_minutes\""},
	NextCrawlAt:            whereHelpernull_Time{field: "\"schema_ingest\".\"data_sources\".\"next_crawl_at\""},
	LastCrawlAt:            whereHelpernull_Time{field: "\"schema_ingest\".\"data_sources\".\"last_crawl_at\""},
	LastSuccessAt:          whereHelpernull_Time{field: "\"schema_ingest\".\"data_sources\".\"last_success_at\""},
	LastErrorAt:            whereHelpernull_Time{field: "\"schema_ingest\".\"data_sources\".\"last_error_at\""},
	LastErrorMessage:       whereHelpernull_String{field: "\"schema_ingest\".\"data_sources\".\"last_error_message\""},
	WebhookID:              whereHelpernull_String{field: "\"schema_ingest\".\"data_sources\".\"webhook_id\""},
	WebhookSecretEncrypted: whereHelpernull_String{field: "\"schema_ingest\".\"data_sources\".\"webhook_secret_encrypted\""},
	CreatedBy:              whereHelpernull_String{field: "\"schema_ingest\".\"data_sources\".\"created_by\""},
	ActivatedAt:            whereHelpernull_Time{field: "\"schema_ingest\".\"data_sources\".\"activated_at\""},
	PausedAt:               whereHelpernull_Time{field: "\"schema_ingest\".\"data_sources\".\"paused_at\""},
	ArchivedAt:             whereHelpernull_Time{field: "\"schema_ingest\".\"data_sources\".\"archived_at\""},
	CreatedAt:              whereHelpertime_Time{field: "\"schema_ingest\".\"data_sources\".\"created_at\""},
	UpdatedAt:              whereHelpertime_Time{field: "\"schema_ingest\".\"data_sources\".\"updated_at\""},
	DeletedAt:              whereHelpernull_Time{field: "\"schema_ingest\".\"data_sources\".\"deleted_at\""},
}

// DataSourceRels is where relationship names are stored.
var DataSourceRels = struct {
	DryrunLastResult       string
	SourceCrawlModeChanges string
	CrawlTargets           string
	SourceDryrunResults    string
	SourceExternalTasks    string
	SourceRawBatches       string
	SourceScheduledJobs    string
}{
	DryrunLastResult:       "DryrunLastResult",
	SourceCrawlModeChanges: "SourceCrawlModeChanges",
	CrawlTargets:           "CrawlTargets",
	SourceDryrunResults:    "SourceDryrunResults",
	SourceExternalTasks:    "SourceExternalTasks",
	SourceRawBatches:       "SourceRawBatches",
	SourceScheduledJobs:    "SourceScheduledJobs",
}

// dataSourceR is where relationships are stored.
type dataSourceR struct {
	DryrunLastResult       *DryrunResult        `boil:"DryrunLastResult" json:"DryrunLastResult" toml:"DryrunLastResult" yaml:"DryrunLastResult"`
	SourceCrawlModeChanges CrawlModeChangeSlice `boil:"SourceCrawlModeChanges" json:"SourceCrawlModeChanges" toml:"SourceCrawlModeChanges" yaml:"SourceCrawlModeChanges"`
	CrawlTargets           CrawlTargetSlice     `boil:"CrawlTargets" json:"CrawlTargets" toml:"CrawlTargets" yaml:"CrawlTargets"`
	SourceDryrunResults    DryrunResultSlice    `boil:"SourceDryrunResults" json:"SourceDryrunResults" toml:"SourceDryrunResults" yaml:"SourceDryrunResults"`
	SourceExternalTasks    ExternalTaskSlice    `boil:"SourceExternalTasks" json:"SourceExternalTasks" toml:"SourceExternalTasks" yaml:"SourceExternalTasks"`
	SourceRawBatches       RawBatchSlice        `boil:"SourceRawBatches" json:"SourceRawBatches" toml:"SourceRawBatches" yaml:"SourceRawBatches"`
	SourceScheduledJobs    ScheduledJobSlice    `boil:"SourceScheduledJobs" json:"SourceScheduledJobs" toml:"SourceScheduledJobs" yaml:"SourceScheduledJobs"`
}

// NewStruct creates a new relationship struct
func (*dataSourceR) NewStruct() *dataSourceR {
	return &dataSourceR{}
}

func (o *DataSource) GetDryrunLastResult() *DryrunResult {
	if o == nil {
		return nil
	}

	return o.R.GetDryrunLastResult()
}

func (r *dataSourceR) GetDryrunLastResult() *DryrunResult {
	if r == nil {
		return nil
	}

	return r.DryrunLastResult
}

func (o *DataSource) GetSourceCrawlModeChanges() CrawlModeChangeSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSourceCrawlModeChanges()
}

func (r *dataSourceR) GetSourceCrawlModeChanges() CrawlModeChangeSlice {
	if r == nil {
		return nil
	}

	return r.SourceCrawlModeChanges
}

func (o *DataSource) GetCrawlTargets() CrawlTargetSlice {
	if o == nil {
		return nil
	}

	return o.R.GetCrawlTargets()
}

func (r *dataSourceR) GetCrawlTargets() CrawlTargetSlice {
	if r == nil {
		return nil
	}

	return r.CrawlTargets
}

func (o *DataSource) GetSourceDryrunResults() DryrunResultSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSourceDryrunResults()
}

func (r *dataSourceR) GetSourceDryrunResults() DryrunResultSlice {
	if r == nil {
		return nil
	}

	return r.SourceDryrunResults
}

func (o *DataSource) GetSourceExternalTasks() ExternalTaskSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSourceExternalTasks()
}

func (r *dataSourceR) GetSourceExternalTasks() ExternalTaskSlice {
	if r == nil {
		return nil
	}

	return r.SourceExternalTasks
}

func (o *DataSource) GetSourceRawBatches() RawBatchSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSourceRawBatches()
}

func (r *dataSourceR) GetSourceRawBatches() RawBatchSlice {
	if r == nil {
		return nil
	}

	return r.SourceRawBatches
}

func (o *DataSource) GetSourceScheduledJobs() ScheduledJobSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSourceScheduledJobs()
}

func (r *dataSourceR) GetSourceScheduledJobs() ScheduledJobSlice {
	if r == nil {
		return nil
	}

	return r.SourceScheduledJobs
}

// dataSourceL is where Load methods for each relationship are stored.
type dataSourceL struct{}

var (
	dataSourceAllColumns            = []string{"id", "project_id", "name", "description", "source_type", "source_category", "status", "config", "account_ref", "mapping_rules", "onboarding_status", "dryrun_status", "dryrun_last_result_id", "crawl_mode", "crawl_interval_minutes", "next_crawl_at", "last_crawl_at", "last_success_at", "last_error_at", "last_error_message", "webhook_id", "webhook_secret_encrypted", "created_by", "activated_at", "paused_at", "archived_at", "created_at", "updated_at", "deleted_at"}
	dataSourceColumnsWithoutDefault = []string{"id", "project_id", "name", "source_type", "source_category"}
	dataSourceColumnsWithDefault    = []string{"description", "status", "config", "account_ref", "mapping_rules", "onboarding_status", "dryrun_status", "dryrun_last_result_id", "crawl_mode", "crawl_interval_minutes", "next_crawl_at", "last_crawl_at", "last_success_at", "last_error_at", "last_error_message", "webhook_id", "webhook_secret_encrypted", "created_by", "activated_at", "paused_at", "archived_at", "created_at", "updated_at", "deleted_at"}
	dataSourcePrimaryKeyColumns     = []string{"id"}
	dataSourceGeneratedColumns      = []string{}
)

type (
	// DataSourceSlice is an alias for a slice of pointers to DataSource.
	// This should almost always be used instead of []DataSource.
	DataSourceSlice []*DataSource
	// DataSourceHook is the signature for custom DataSource hook methods
	DataSourceHook func(context.Context, boil.ContextExecutor, *DataSource) error

	dataSourceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dataSourceType                 = reflect.TypeOf(&DataSource{})
	dataSourceMapping              = queries.MakeStructMapping(dataSourceType)
	dataSourcePrimaryKeyMapping, _ = queries.BindMapping(dataSourceType, dataSourceMapping, dataSourcePrimaryKeyColumns)
	dataSourceInsertCacheMut       sync.RWMutex
	dataSourceInsertCache          = make(map[string]insertCache)
	dataSourceUpdateCacheMut       sync.RWMutex
	dataSourceUpdateCache          = make(map[string]updateCache)
	dataSourceUpsertCacheMut       sync.RWMutex
	dataSourceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dataSourceAfterSelectMu sync.Mutex
var dataSourceAfterSelectHooks []DataSourceHook

var dataSourceBeforeInsertMu sync.Mutex
var dataSourceBeforeInsertHooks []DataSourceHook
var dataSourceAfterInsertMu sync.Mutex
var dataSourceAfterInsertHooks []DataSourceHook

var dataSourceBeforeUpdateMu sync.Mutex
var dataSourceBeforeUpdateHooks []DataSourceHook
var dataSourceAfterUpdateMu sync.Mutex
var dataSourceAfterUpdateHooks []DataSourceHook

var dataSourceBeforeDeleteMu sync.Mutex
var dataSourceBeforeDeleteHooks []DataSourceHook
var dataSourceAfterDeleteMu sync.Mutex
var dataSourceAfterDeleteHooks []DataSourceHook

var dataSourceBeforeUpsertMu sync.Mutex
var dataSourceBeforeUpsertHooks []DataSourceHook
var dataSourceAfterUpsertMu sync.Mutex
var dataSourceAfterUpsertHooks []DataSourceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DataSource) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DataSource) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DataSource) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DataSource) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DataSource) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DataSource) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DataSource) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DataSource) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DataSource) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dataSourceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDataSourceHook registers your hook function for all future operations.
func AddDataSourceHook(hookPoint boil.HookPoint, dataSourceHook DataSourceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		dataSourceAfterSelectMu.Lock()
		dataSourceAfterSelectHooks = append(dataSourceAfterSelectHooks, dataSourceHook)
		dataSourceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		dataSourceBeforeInsertMu.Lock()
		dataSourceBeforeInsertHooks = append(dataSourceBeforeInsertHooks, dataSourceHook)
		dataSourceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		dataSourceAfterInsertMu.Lock()
		dataSourceAfterInsertHooks = append(dataSourceAfterInsertHooks, dataSourceHook)
		dataSourceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		dataSourceBeforeUpdateMu.Lock()
		dataSourceBeforeUpdateHooks = append(dataSourceBeforeUpdateHooks, dataSourceHook)
		dataSourceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		dataSourceAfterUpdateMu.Lock()
		dataSourceAfterUpdateHooks = append(dataSourceAfterUpdateHooks, dataSourceHook)
		dataSourceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		dataSourceBeforeDeleteMu.Lock()
		dataSourceBeforeDeleteHooks = append(dataSourceBeforeDeleteHooks, dataSourceHook)
		dataSourceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		dataSourceAfterDeleteMu.Lock()
		dataSourceAfterDeleteHooks = append(dataSourceAfterDeleteHooks, dataSourceHook)
		dataSourceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		dataSourceBeforeUpsertMu.Lock()
		dataSourceBeforeUpsertHooks = append(dataSourceBeforeUpsertHooks, dataSourceHook)
		dataSourceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		dataSourceAfterUpsertMu.Lock()
		dataSourceAfterUpsertHooks = append(dataSourceAfterUpsertHooks, dataSourceHook)
		dataSourceAfterUpsertMu.Unlock()
	}
}

// One returns a single dataSource record from the query.
func (q dataSourceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DataSource, error) {
	o := &DataSource{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for data_sources")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DataSource records from the query.
func (q dataSourceQuery) All(ctx context.Context, exec boil.ContextExecutor) (DataSourceSlice, error) {
	var o []*DataSource

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to DataSource slice")
	}

	if len(dataSourceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DataSource records in the query.
func (q dataSourceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count data_sources rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dataSourceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if data_sources exists")
	}

	return count > 0, nil
}

// DryrunLastResult pointed to by the foreign key.
func (o *DataSource) DryrunLastResult(mods ...qm.QueryMod) dryrunResultQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DryrunLastResultID),
	}

	queryMods = append(queryMods, mods...)

	return DryrunResults(queryMods...)
}

// SourceCrawlModeChanges retrieves all the crawl_mode_change's CrawlModeChanges with an executor via source_id column.
func (o *DataSource) SourceCrawlModeChanges(mods ...qm.QueryMod) crawlModeChangeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"schema_ingest\".\"crawl_mode_changes\".\"source_id\"=?", o.ID),
	)

	return CrawlModeChanges(queryMods...)
}

// CrawlTargets retrieves all the crawl_target's CrawlTargets with an executor.
func (o *DataSource) CrawlTargets(mods ...qm.QueryMod) crawlTargetQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"schema_ingest\".\"crawl_targets\".\"data_source_id\"=?", o.ID),
	)

	return CrawlTargets(queryMods...)
}

// SourceDryrunResults retrieves all the dryrun_result's DryrunResults with an executor via source_id column.
func (o *DataSource) SourceDryrunResults(mods ...qm.QueryMod) dryrunResultQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"schema_ingest\".\"dryrun_results\".\"source_id\"=?", o.ID),
	)

	return DryrunResults(queryMods...)
}

// SourceExternalTasks retrieves all the external_task's ExternalTasks with an executor via source_id column.
func (o *DataSource) SourceExternalTasks(mods ...qm.QueryMod) externalTaskQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"schema_ingest\".\"external_tasks\".\"source_id\"=?", o.ID),
	)

	return ExternalTasks(queryMods...)
}

// SourceRawBatches retrieves all the raw_batch's RawBatches with an executor via source_id column.
func (o *DataSource) SourceRawBatches(mods ...qm.QueryMod) rawBatchQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"schema_ingest\".\"raw_batches\".\"source_id\"=?", o.ID),
	)

	return RawBatches(queryMods...)
}

// SourceScheduledJobs retrieves all the scheduled_job's ScheduledJobs with an executor via source_id column.
func (o *DataSource) SourceScheduledJobs(mods ...qm.QueryMod) scheduledJobQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"schema_ingest\".\"scheduled_jobs\".\"source_id\"=?", o.ID),
	)

	return ScheduledJobs(queryMods...)
}

// LoadDryrunLastResult allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (dataSourceL) LoadDryrunLastResult(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataSource any, mods queries.Applicator) error {
	var slice []*DataSource
	var object *DataSource

	if singular {
		var ok bool
		object, ok = maybeDataSource.(*DataSource)
		if !ok {
			object = new(DataSource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataSource))
			}
		}
	} else {
		s, ok := maybeDataSource.(*[]*DataSource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataSource))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataSourceR{}
		}
		if !queries.IsNil(object.DryrunLastResultID) {
			args[object.DryrunLastResultID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataSourceR{}
			}

			if !queries.IsNil(obj.DryrunLastResultID) {
				args[obj.DryrunLastResultID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.dryrun_results`),
		qm.WhereIn(`schema_ingest.dryrun_results.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DryrunResult")
	}

	var resultSlice []*DryrunResult
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DryrunResult")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for dryrun_results")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for dryrun_results")
	}

	if len(dryrunResultAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DryrunLastResult = foreign
		if foreign.R == nil {
			foreign.R = &dryrunResultR{}
		}
		foreign.R.DryrunLastResultDataSources = append(foreign.R.DryrunLastResultDataSources, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.DryrunLastResultID, foreign.ID) {
				local.R.DryrunLastResult = foreign
				if foreign.R == nil {
					foreign.R = &dryrunResultR{}
				}
				foreign.R.DryrunLastResultDataSources = append(foreign.R.DryrunLastResultDataSources, local)
				break
			}
		}
	}

	return nil
}

// LoadSourceCrawlModeChanges allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataSourceL) LoadSourceCrawlModeChanges(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataSource any, mods queries.Applicator) error {
	var slice []*DataSource
	var object *DataSource

	if singular {
		var ok bool
		object, ok = maybeDataSource.(*DataSource)
		if !ok {
			object = new(DataSource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataSource))
			}
		}
	} else {
		s, ok := maybeDataSource.(*[]*DataSource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataSource))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataSourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataSourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.crawl_mode_changes`),
		qm.WhereIn(`schema_ingest.crawl_mode_changes.source_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load crawl_mode_changes")
	}

	var resultSlice []*CrawlModeChange
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice crawl_mode_changes")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on crawl_mode_changes")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for crawl_mode_changes")
	}

	if len(crawlModeChangeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SourceCrawlModeChanges = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &crawlModeChangeR{}
			}
			foreign.R.Source = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SourceID {
				local.R.SourceCrawlModeChanges = append(local.R.SourceCrawlModeChanges, foreign)
				if foreign.R == nil {
					foreign.R = &crawlModeChangeR{}
				}
				foreign.R.Source = local
				break
			}
		}
	}

	return nil
}

// LoadCrawlTargets allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataSourceL) LoadCrawlTargets(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataSource any, mods queries.Applicator) error {
	var slice []*DataSource
	var object *DataSource

	if singular {
		var ok bool
		object, ok = maybeDataSource.(*DataSource)
		if !ok {
			object = new(DataSource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataSource))
			}
		}
	} else {
		s, ok := maybeDataSource.(*[]*DataSource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataSource))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataSourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataSourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.crawl_targets`),
		qm.WhereIn(`schema_ingest.crawl_targets.data_source_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load crawl_targets")
	}

	var resultSlice []*CrawlTarget
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice crawl_targets")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on crawl_targets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for crawl_targets")
	}

	if len(crawlTargetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CrawlTargets = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &crawlTargetR{}
			}
			foreign.R.DataSource = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.DataSourceID {
				local.R.CrawlTargets = append(local.R.CrawlTargets, foreign)
				if foreign.R == nil {
					foreign.R = &crawlTargetR{}
				}
				foreign.R.DataSource = local
				break
			}
		}
	}

	return nil
}

// LoadSourceDryrunResults allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataSourceL) LoadSourceDryrunResults(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataSource any, mods queries.Applicator) error {
	var slice []*DataSource
	var object *DataSource

	if singular {
		var ok bool
		object, ok = maybeDataSource.(*DataSource)
		if !ok {
			object = new(DataSource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataSource))
			}
		}
	} else {
		s, ok := maybeDataSource.(*[]*DataSource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataSource))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataSourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataSourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.dryrun_results`),
		qm.WhereIn(`schema_ingest.dryrun_results.source_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load dryrun_results")
	}

	var resultSlice []*DryrunResult
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice dryrun_results")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on dryrun_results")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for dryrun_results")
	}

	if len(dryrunResultAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SourceDryrunResults = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &dryrunResultR{}
			}
			foreign.R.Source = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SourceID {
				local.R.SourceDryrunResults = append(local.R.SourceDryrunResults, foreign)
				if foreign.R == nil {
					foreign.R = &dryrunResultR{}
				}
				foreign.R.Source = local
				break
			}
		}
	}

	return nil
}

// LoadSourceExternalTasks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataSourceL) LoadSourceExternalTasks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataSource any, mods queries.Applicator) error {
	var slice []*DataSource
	var object *DataSource

	if singular {
		var ok bool
		object, ok = maybeDataSource.(*DataSource)
		if !ok {
			object = new(DataSource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataSource))
			}
		}
	} else {
		s, ok := maybeDataSource.(*[]*DataSource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataSource))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataSourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataSourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.external_tasks`),
		qm.WhereIn(`schema_ingest.external_tasks.source_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load external_tasks")
	}

	var resultSlice []*ExternalTask
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice external_tasks")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on external_tasks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for external_tasks")
	}

	if len(externalTaskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SourceExternalTasks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &externalTaskR{}
			}
			foreign.R.Source = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SourceID {
				local.R.SourceExternalTasks = append(local.R.SourceExternalTasks, foreign)
				if foreign.R == nil {
					foreign.R = &externalTaskR{}
				}
				foreign.R.Source = local
				break
			}
		}
	}

	return nil
}

// LoadSourceRawBatches allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataSourceL) LoadSourceRawBatches(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataSource any, mods queries.Applicator) error {
	var slice []*DataSource
	var object *DataSource

	if singular {
		var ok bool
		object, ok = maybeDataSource.(*DataSource)
		if !ok {
			object = new(DataSource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataSource))
			}
		}
	} else {
		s, ok := maybeDataSource.(*[]*DataSource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataSource))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataSourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataSourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.raw_batches`),
		qm.WhereIn(`schema_ingest.raw_batches.source_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load raw_batches")
	}

	var resultSlice []*RawBatch
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice raw_batches")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on raw_batches")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for raw_batches")
	}

	if len(rawBatchAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SourceRawBatches = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &rawBatchR{}
			}
			foreign.R.Source = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SourceID {
				local.R.SourceRawBatches = append(local.R.SourceRawBatches, foreign)
				if foreign.R == nil {
					foreign.R = &rawBatchR{}
				}
				foreign.R.Source = local
				break
			}
		}
	}

	return nil
}

// LoadSourceScheduledJobs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataSourceL) LoadSourceScheduledJobs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataSource any, mods queries.Applicator) error {
	var slice []*DataSource
	var object *DataSource

	if singular {
		var ok bool
		object, ok = maybeDataSource.(*DataSource)
		if !ok {
			object = new(DataSource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataSource))
			}
		}
	} else {
		s, ok := maybeDataSource.(*[]*DataSource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataSource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataSource))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &dataSourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataSourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.scheduled_jobs`),
		qm.WhereIn(`schema_ingest.scheduled_jobs.source_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load scheduled_jobs")
	}

	var resultSlice []*ScheduledJob
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice scheduled_jobs")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on scheduled_jobs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for scheduled_jobs")
	}

	if len(scheduledJobAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SourceScheduledJobs = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &scheduledJobR{}
			}
			foreign.R.Source = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SourceID {
				local.R.SourceScheduledJobs = append(local.R.SourceScheduledJobs, foreign)
				if foreign.R == nil {
					foreign.R = &scheduledJobR{}
				}
				foreign.R.Source = local
				break
			}
		}
	}

	return nil
}

// SetDryrunLastResult of the dataSource to the related item.
// Sets o.R.DryrunLastResult to related.
// Adds o to related.R.DryrunLastResultDataSources.
func (o *DataSource) SetDryrunLastResult(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DryrunResult) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"schema_ingest\".\"data_sources\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"dryrun_last_result_id"}),
		strmangle.WhereClause("\"", "\"", 2, dataSourcePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.DryrunLastResultID, related.ID)
	if o.R == nil {
		o.R = &dataSourceR{
			DryrunLastResult: related,
		}
	} else {
		o.R.DryrunLastResult = related
	}

	if related.R == nil {
		related.R = &dryrunResultR{
			DryrunLastResultDataSources: DataSourceSlice{o},
		}
	} else {
		related.R.DryrunLastResultDataSources = append(related.R.DryrunLastResultDataSources, o)
	}

	return nil
}

// RemoveDryrunLastResult relationship.
// Sets o.R.DryrunLastResult to nil.
// Removes o from all passed in related items' relationships struct.
func (o *DataSource) RemoveDryrunLastResult(ctx context.Context, exec boil.ContextExecutor, related *DryrunResult) error {
	var err error

	queries.SetScanner(&o.DryrunLastResultID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("dryrun_last_result_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.DryrunLastResult = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.DryrunLastResultDataSources {
		if queries.Equal(o.DryrunLastResultID, ri.DryrunLastResultID) {
			continue
		}

		ln := len(related.R.DryrunLastResultDataSources)
		if ln > 1 && i < ln-1 {
			related.R.DryrunLastResultDataSources[i] = related.R.DryrunLastResultDataSources[ln-1]
		}
		related.R.DryrunLastResultDataSources = related.R.DryrunLastResultDataSources[:ln-1]
		break
	}
	return nil
}

// AddSourceCrawlModeChanges adds the given related objects to the existing relationships
// of the data_source, optionally inserting them as new records.
// Appends related to o.R.SourceCrawlModeChanges.
// Sets related.R.Source appropriately.
func (o *DataSource) AddSourceCrawlModeChanges(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CrawlModeChange) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SourceID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"schema_ingest\".\"crawl_mode_changes\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
				strmangle.WhereClause("\"", "\"", 2, crawlModeChangePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SourceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &dataSourceR{
			SourceCrawlModeChanges: related,
		}
	} else {
		o.R.SourceCrawlModeChanges = append(o.R.SourceCrawlModeChanges, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &crawlModeChangeR{
				Source: o,
			}
		} else {
			rel.R.Source = o
		}
	}
	return nil
}

// AddCrawlTargets adds the given related objects to the existing relationships
// of the data_source, optionally inserting them as new records.
// Appends related to o.R.CrawlTargets.
// Sets related.R.DataSource appropriately.
func (o *DataSource) AddCrawlTargets(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CrawlTarget) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.DataSourceID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"schema_ingest\".\"crawl_targets\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"data_source_id"}),
				strmangle.WhereClause("\"", "\"", 2, crawlTargetPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.DataSourceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &dataSourceR{
			CrawlTargets: related,
		}
	} else {
		o.R.CrawlTargets = append(o.R.CrawlTargets, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &crawlTargetR{
				DataSource: o,
			}
		} else {
			rel.R.DataSource = o
		}
	}
	return nil
}

// AddSourceDryrunResults adds the given related objects to the existing relationships
// of the data_source, optionally inserting them as new records.
// Appends related to o.R.SourceDryrunResults.
// Sets related.R.Source appropriately.
func (o *DataSource) AddSourceDryrunResults(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DryrunResult) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SourceID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"schema_ingest\".\"dryrun_results\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
				strmangle.WhereClause("\"", "\"", 2, dryrunResultPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SourceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &dataSourceR{
			SourceDryrunResults: related,
		}
	} else {
		o.R.SourceDryrunResults = append(o.R.SourceDryrunResults, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &dryrunResultR{
				Source: o,
			}
		} else {
			rel.R.Source = o
		}
	}
	return nil
}

// AddSourceExternalTasks adds the given related objects to the existing relationships
// of the data_source, optionally inserting them as new records.
// Appends related to o.R.SourceExternalTasks.
// Sets related.R.Source appropriately.
func (o *DataSource) AddSourceExternalTasks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ExternalTask) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SourceID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"schema_ingest\".\"external_tasks\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
				strmangle.WhereClause("\"", "\"", 2, externalTaskPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SourceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &dataSourceR{
			SourceExternalTasks: related,
		}
	} else {
		o.R.SourceExternalTasks = append(o.R.SourceExternalTasks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &externalTaskR{
				Source: o,
			}
		} else {
			rel.R.Source = o
		}
	}
	return nil
}

// AddSourceRawBatches adds the given related objects to the existing relationships
// of the data_source, optionally inserting them as new records.
// Appends related to o.R.SourceRawBatches.
// Sets related.R.Source appropriately.
func (o *DataSource) AddSourceRawBatches(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RawBatch) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SourceID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"schema_ingest\".\"raw_batches\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
				strmangle.WhereClause("\"", "\"", 2, rawBatchPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SourceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &dataSourceR{
			SourceRawBatches: related,
		}
	} else {
		o.R.SourceRawBatches = append(o.R.SourceRawBatches, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &rawBatchR{
				Source: o,
			}
		} else {
			rel.R.Source = o
		}
	}
	return nil
}

// AddSourceScheduledJobs adds the given related objects to the existing relationships
// of the data_source, optionally inserting them as new records.
// Appends related to o.R.SourceScheduledJobs.
// Sets related.R.Source appropriately.
func (o *DataSource) AddSourceScheduledJobs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ScheduledJob) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SourceID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"schema_ingest\".\"scheduled_jobs\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
				strmangle.WhereClause("\"", "\"", 2, scheduledJobPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SourceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &dataSourceR{
			SourceScheduledJobs: related,
		}
	} else {
		o.R.SourceScheduledJobs = append(o.R.SourceScheduledJobs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &scheduledJobR{
				Source: o,
			}
		} else {
			rel.R.Source = o
		}
	}
	return nil
}

// DataSources retrieves all the records using an executor.
func DataSources(mods ...qm.QueryMod) dataSourceQuery {
	mods = append(mods, qm.From("\"schema_ingest\".\"data_sources\""), qmhelper.WhereIsNull("\"schema_ingest\".\"data_sources\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"schema_ingest\".\"data_sources\".*"})
	}

	return dataSourceQuery{q}
}

// FindDataSource retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDataSource(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*DataSource, error) {
	dataSourceObj := &DataSource{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"schema_ingest\".\"data_sources\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, dataSourceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from data_sources")
	}

	if err = dataSourceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return dataSourceObj, err
	}

	return dataSourceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DataSource) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no data_sources provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataSourceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dataSourceInsertCacheMut.RLock()
	cache, cached := dataSourceInsertCache[key]
	dataSourceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dataSourceAllColumns,
			dataSourceColumnsWithDefault,
			dataSourceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dataSourceType, dataSourceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dataSourceType, dataSourceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"schema_ingest\".\"data_sources\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"schema_ingest\".\"data_sources\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into data_sources")
	}

	if !cached {
		dataSourceInsertCacheMut.Lock()
		dataSourceInsertCache[key] = cache
		dataSourceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DataSource.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DataSource) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dataSourceUpdateCacheMut.RLock()
	cache, cached := dataSourceUpdateCache[key]
	dataSourceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dataSourceAllColumns,
			dataSourcePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update data_sources, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"schema_ingest\".\"data_sources\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, dataSourcePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dataSourceType, dataSourceMapping, append(wl, dataSourcePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update data_sources row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for data_sources")
	}

	if !cached {
		dataSourceUpdateCacheMut.Lock()
		dataSourceUpdateCache[key] = cache
		dataSourceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dataSourceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for data_sources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for data_sources")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DataSourceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataSourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"schema_ingest\".\"data_sources\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, dataSourcePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in dataSource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all dataSource")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DataSource) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no data_sources provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dataSourceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dataSourceUpsertCacheMut.RLock()
	cache, cached := dataSourceUpsertCache[key]
	dataSourceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			dataSourceAllColumns,
			dataSourceColumnsWithDefault,
			dataSourceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dataSourceAllColumns,
			dataSourcePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert data_sources, could not build update column list")
		}

		ret := strmangle.SetComplement(dataSourceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(dataSourcePrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert data_sources, could not build conflict column list")
			}

			conflict = make([]string, len(dataSourcePrimaryKeyColumns))
			copy(conflict, dataSourcePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"schema_ingest\".\"data_sources\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(dataSourceType, dataSourceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dataSourceType, dataSourceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert data_sources")
	}

	if !cached {
		dataSourceUpsertCacheMut.Lock()
		dataSourceUpsertCache[key] = cache
		dataSourceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DataSource record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DataSource) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no DataSource provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []any
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dataSourcePrimaryKeyMapping)
		sql = "DELETE FROM \"schema_ingest\".\"data_sources\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"schema_ingest\".\"data_sources\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(dataSourceType, dataSourceMapping, append(wl, dataSourcePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from data_sources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for data_sources")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dataSourceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no dataSourceQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from data_sources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for data_sources")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DataSourceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dataSourceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []any
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataSourcePrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"schema_ingest\".\"data_sources\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, dataSourcePrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataSourcePrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"schema_ingest\".\"data_sources\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, dataSourcePrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]any{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from dataSource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for data_sources")
	}

	if len(dataSourceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DataSource) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDataSource(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DataSourceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DataSourceSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataSourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"schema_ingest\".\"data_sources\".* FROM \"schema_ingest\".\"data_sources\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, dataSourcePrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in DataSourceSlice")
	}

	*o = slice

	return nil
}

// DataSourceExists checks if the DataSource row exists.
func DataSourceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"schema_ingest\".\"data_sources\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if data_sources exists")
	}

	return exists, nil
}

// Exists checks if the DataSource row exists.
func (o *DataSource) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DataSourceExists(ctx, exec, o.ID)
}
