// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ExternalTask is an object representing the database table.
type ExternalTask struct {
	ID                 string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	SourceID           string      `boil:"source_id" json:"source_id" toml:"source_id" yaml:"source_id"`
	ProjectID          string      `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	DomainTypeCode     string      `boil:"domain_type_code" json:"domain_type_code" toml:"domain_type_code" yaml:"domain_type_code"`
	TargetID           null.String `boil:"target_id" json:"target_id,omitempty" toml:"target_id" yaml:"target_id,omitempty"`
	ScheduledJobID     null.String `boil:"scheduled_job_id" json:"scheduled_job_id,omitempty" toml:"scheduled_job_id" yaml:"scheduled_job_id,omitempty"`
	TaskID             string      `boil:"task_id" json:"task_id" toml:"task_id" yaml:"task_id"`
	Platform           string      `boil:"platform" json:"platform" toml:"platform" yaml:"platform"`
	TaskType           string      `boil:"task_type" json:"task_type" toml:"task_type" yaml:"task_type"`
	RoutingKey         string      `boil:"routing_key" json:"routing_key" toml:"routing_key" yaml:"routing_key"`
	RequestPayload     types.JSON  `boil:"request_payload" json:"request_payload" toml:"request_payload" yaml:"request_payload"`
	Status             JobStatus   `boil:"status" json:"status" toml:"status" yaml:"status"`
	PublishedAt        null.Time   `boil:"published_at" json:"published_at,omitempty" toml:"published_at" yaml:"published_at,omitempty"`
	ResponseReceivedAt null.Time   `boil:"response_received_at" json:"response_received_at,omitempty" toml:"response_received_at" yaml:"response_received_at,omitempty"`
	CompletedAt        null.Time   `boil:"completed_at" json:"completed_at,omitempty" toml:"completed_at" yaml:"completed_at,omitempty"`
	ErrorMessage       null.String `boil:"error_message" json:"error_message,omitempty" toml:"error_message" yaml:"error_message,omitempty"`
	CreatedAt          time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *externalTaskR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L externalTaskL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ExternalTaskColumns = struct {
	ID                 string
	SourceID           string
	ProjectID          string
	DomainTypeCode     string
	TargetID           string
	ScheduledJobID     string
	TaskID             string
	Platform           string
	TaskType           string
	RoutingKey         string
	RequestPayload     string
	Status             string
	PublishedAt        string
	ResponseReceivedAt string
	CompletedAt        string
	ErrorMessage       string
	CreatedAt          string
}{
	ID:                 "id",
	SourceID:           "source_id",
	ProjectID:          "project_id",
	DomainTypeCode:     "domain_type_code",
	TargetID:           "target_id",
	ScheduledJobID:     "scheduled_job_id",
	TaskID:             "task_id",
	Platform:           "platform",
	TaskType:           "task_type",
	RoutingKey:         "routing_key",
	RequestPayload:     "request_payload",
	Status:             "status",
	PublishedAt:        "published_at",
	ResponseReceivedAt: "response_received_at",
	CompletedAt:        "completed_at",
	ErrorMessage:       "error_message",
	CreatedAt:          "created_at",
}

var ExternalTaskTableColumns = struct {
	ID                 string
	SourceID           string
	ProjectID          string
	DomainTypeCode     string
	TargetID           string
	ScheduledJobID     string
	TaskID             string
	Platform           string
	TaskType           string
	RoutingKey         string
	RequestPayload     string
	Status             string
	PublishedAt        string
	ResponseReceivedAt string
	CompletedAt        string
	ErrorMessage       string
	CreatedAt          string
}{
	ID:                 "external_tasks.id",
	SourceID:           "external_tasks.source_id",
	ProjectID:          "external_tasks.project_id",
	DomainTypeCode:     "external_tasks.domain_type_code",
	TargetID:           "external_tasks.target_id",
	ScheduledJobID:     "external_tasks.scheduled_job_id",
	TaskID:             "external_tasks.task_id",
	Platform:           "external_tasks.platform",
	TaskType:           "external_tasks.task_type",
	RoutingKey:         "external_tasks.routing_key",
	RequestPayload:     "external_tasks.request_payload",
	Status:             "external_tasks.status",
	PublishedAt:        "external_tasks.published_at",
	ResponseReceivedAt: "external_tasks.response_received_at",
	CompletedAt:        "external_tasks.completed_at",
	ErrorMessage:       "external_tasks.error_message",
	CreatedAt:          "external_tasks.created_at",
}

// Generated where

type whereHelperJobStatus struct{ field string }

func (w whereHelperJobStatus) EQ(x JobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperJobStatus) NEQ(x JobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperJobStatus) LT(x JobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperJobStatus) LTE(x JobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperJobStatus) GT(x JobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperJobStatus) GTE(x JobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperJobStatus) IN(slice []JobStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperJobStatus) NIN(slice []JobStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ExternalTaskWhere = struct {
	ID                 whereHelperstring
	SourceID           whereHelperstring
	ProjectID          whereHelperstring
	TargetID           whereHelpernull_String
	ScheduledJobID     whereHelpernull_String
	TaskID             whereHelperstring
	Platform           whereHelperstring
	TaskType           whereHelperstring
	RoutingKey         whereHelperstring
	RequestPayload     whereHelpertypes_JSON
	Status             whereHelperJobStatus
	PublishedAt        whereHelpernull_Time
	ResponseReceivedAt whereHelpernull_Time
	CompletedAt        whereHelpernull_Time
	ErrorMessage       whereHelpernull_String
	CreatedAt          whereHelpertime_Time
}{
	ID:                 whereHelperstring{field: "\"schema_ingest\".\"external_tasks\".\"id\""},
	SourceID:           whereHelperstring{field: "\"schema_ingest\".\"external_tasks\".\"source_id\""},
	ProjectID:          whereHelperstring{field: "\"schema_ingest\".\"external_tasks\".\"project_id\""},
	TargetID:           whereHelpernull_String{field: "\"schema_ingest\".\"external_tasks\".\"target_id\""},
	ScheduledJobID:     whereHelpernull_String{field: "\"schema_ingest\".\"external_tasks\".\"scheduled_job_id\""},
	TaskID:             whereHelperstring{field: "\"schema_ingest\".\"external_tasks\".\"task_id\""},
	Platform:           whereHelperstring{field: "\"schema_ingest\".\"external_tasks\".\"platform\""},
	TaskType:           whereHelperstring{field: "\"schema_ingest\".\"external_tasks\".\"task_type\""},
	RoutingKey:         whereHelperstring{field: "\"schema_ingest\".\"external_tasks\".\"routing_key\""},
	RequestPayload:     whereHelpertypes_JSON{field: "\"schema_ingest\".\"external_tasks\".\"request_payload\""},
	Status:             whereHelperJobStatus{field: "\"schema_ingest\".\"external_tasks\".\"status\""},
	PublishedAt:        whereHelpernull_Time{field: "\"schema_ingest\".\"external_tasks\".\"published_at\""},
	ResponseReceivedAt: whereHelpernull_Time{field: "\"schema_ingest\".\"external_tasks\".\"response_received_at\""},
	CompletedAt:        whereHelpernull_Time{field: "\"schema_ingest\".\"external_tasks\".\"completed_at\""},
	ErrorMessage:       whereHelpernull_String{field: "\"schema_ingest\".\"external_tasks\".\"error_message\""},
	CreatedAt:          whereHelpertime_Time{field: "\"schema_ingest\".\"external_tasks\".\"created_at\""},
}

// ExternalTaskRels is where relationship names are stored.
var ExternalTaskRels = struct {
	ScheduledJob string
	Source       string
	Target       string
	RawBatches   string
}{
	ScheduledJob: "ScheduledJob",
	Source:       "Source",
	Target:       "Target",
	RawBatches:   "RawBatches",
}

// externalTaskR is where relationships are stored.
type externalTaskR struct {
	ScheduledJob *ScheduledJob `boil:"ScheduledJob" json:"ScheduledJob" toml:"ScheduledJob" yaml:"ScheduledJob"`
	Source       *DataSource   `boil:"Source" json:"Source" toml:"Source" yaml:"Source"`
	Target       *CrawlTarget  `boil:"Target" json:"Target" toml:"Target" yaml:"Target"`
	RawBatches   RawBatchSlice `boil:"RawBatches" json:"RawBatches" toml:"RawBatches" yaml:"RawBatches"`
}

// NewStruct creates a new relationship struct
func (*externalTaskR) NewStruct() *externalTaskR {
	return &externalTaskR{}
}

func (o *ExternalTask) GetScheduledJob() *ScheduledJob {
	if o == nil {
		return nil
	}

	return o.R.GetScheduledJob()
}

func (r *externalTaskR) GetScheduledJob() *ScheduledJob {
	if r == nil {
		return nil
	}

	return r.ScheduledJob
}

func (o *ExternalTask) GetSource() *DataSource {
	if o == nil {
		return nil
	}

	return o.R.GetSource()
}

func (r *externalTaskR) GetSource() *DataSource {
	if r == nil {
		return nil
	}

	return r.Source
}

func (o *ExternalTask) GetTarget() *CrawlTarget {
	if o == nil {
		return nil
	}

	return o.R.GetTarget()
}

func (r *externalTaskR) GetTarget() *CrawlTarget {
	if r == nil {
		return nil
	}

	return r.Target
}

func (o *ExternalTask) GetRawBatches() RawBatchSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRawBatches()
}

func (r *externalTaskR) GetRawBatches() RawBatchSlice {
	if r == nil {
		return nil
	}

	return r.RawBatches
}

// externalTaskL is where Load methods for each relationship are stored.
type externalTaskL struct{}

var (
	externalTaskAllColumns            = []string{"id", "source_id", "project_id", "target_id", "scheduled_job_id", "task_id", "platform", "task_type", "routing_key", "request_payload", "status", "published_at", "response_received_at", "completed_at", "error_message", "created_at"}
	externalTaskColumnsWithoutDefault = []string{"id", "source_id", "project_id", "task_id", "platform", "task_type", "routing_key"}
	externalTaskColumnsWithDefault    = []string{"target_id", "scheduled_job_id", "request_payload", "status", "published_at", "response_received_at", "completed_at", "error_message", "created_at"}
	externalTaskPrimaryKeyColumns     = []string{"id"}
	externalTaskGeneratedColumns      = []string{}
)

type (
	// ExternalTaskSlice is an alias for a slice of pointers to ExternalTask.
	// This should almost always be used instead of []ExternalTask.
	ExternalTaskSlice []*ExternalTask
	// ExternalTaskHook is the signature for custom ExternalTask hook methods
	ExternalTaskHook func(context.Context, boil.ContextExecutor, *ExternalTask) error

	externalTaskQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	externalTaskType                 = reflect.TypeOf(&ExternalTask{})
	externalTaskMapping              = queries.MakeStructMapping(externalTaskType)
	externalTaskPrimaryKeyMapping, _ = queries.BindMapping(externalTaskType, externalTaskMapping, externalTaskPrimaryKeyColumns)
	externalTaskInsertCacheMut       sync.RWMutex
	externalTaskInsertCache          = make(map[string]insertCache)
	externalTaskUpdateCacheMut       sync.RWMutex
	externalTaskUpdateCache          = make(map[string]updateCache)
	externalTaskUpsertCacheMut       sync.RWMutex
	externalTaskUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var externalTaskAfterSelectMu sync.Mutex
var externalTaskAfterSelectHooks []ExternalTaskHook

var externalTaskBeforeInsertMu sync.Mutex
var externalTaskBeforeInsertHooks []ExternalTaskHook
var externalTaskAfterInsertMu sync.Mutex
var externalTaskAfterInsertHooks []ExternalTaskHook

var externalTaskBeforeUpdateMu sync.Mutex
var externalTaskBeforeUpdateHooks []ExternalTaskHook
var externalTaskAfterUpdateMu sync.Mutex
var externalTaskAfterUpdateHooks []ExternalTaskHook

var externalTaskBeforeDeleteMu sync.Mutex
var externalTaskBeforeDeleteHooks []ExternalTaskHook
var externalTaskAfterDeleteMu sync.Mutex
var externalTaskAfterDeleteHooks []ExternalTaskHook

var externalTaskBeforeUpsertMu sync.Mutex
var externalTaskBeforeUpsertHooks []ExternalTaskHook
var externalTaskAfterUpsertMu sync.Mutex
var externalTaskAfterUpsertHooks []ExternalTaskHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ExternalTask) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ExternalTask) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ExternalTask) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ExternalTask) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ExternalTask) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ExternalTask) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ExternalTask) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ExternalTask) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ExternalTask) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range externalTaskAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddExternalTaskHook registers your hook function for all future operations.
func AddExternalTaskHook(hookPoint boil.HookPoint, externalTaskHook ExternalTaskHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		externalTaskAfterSelectMu.Lock()
		externalTaskAfterSelectHooks = append(externalTaskAfterSelectHooks, externalTaskHook)
		externalTaskAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		externalTaskBeforeInsertMu.Lock()
		externalTaskBeforeInsertHooks = append(externalTaskBeforeInsertHooks, externalTaskHook)
		externalTaskBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		externalTaskAfterInsertMu.Lock()
		externalTaskAfterInsertHooks = append(externalTaskAfterInsertHooks, externalTaskHook)
		externalTaskAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		externalTaskBeforeUpdateMu.Lock()
		externalTaskBeforeUpdateHooks = append(externalTaskBeforeUpdateHooks, externalTaskHook)
		externalTaskBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		externalTaskAfterUpdateMu.Lock()
		externalTaskAfterUpdateHooks = append(externalTaskAfterUpdateHooks, externalTaskHook)
		externalTaskAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		externalTaskBeforeDeleteMu.Lock()
		externalTaskBeforeDeleteHooks = append(externalTaskBeforeDeleteHooks, externalTaskHook)
		externalTaskBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		externalTaskAfterDeleteMu.Lock()
		externalTaskAfterDeleteHooks = append(externalTaskAfterDeleteHooks, externalTaskHook)
		externalTaskAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		externalTaskBeforeUpsertMu.Lock()
		externalTaskBeforeUpsertHooks = append(externalTaskBeforeUpsertHooks, externalTaskHook)
		externalTaskBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		externalTaskAfterUpsertMu.Lock()
		externalTaskAfterUpsertHooks = append(externalTaskAfterUpsertHooks, externalTaskHook)
		externalTaskAfterUpsertMu.Unlock()
	}
}

// One returns a single externalTask record from the query.
func (q externalTaskQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ExternalTask, error) {
	o := &ExternalTask{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for external_tasks")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ExternalTask records from the query.
func (q externalTaskQuery) All(ctx context.Context, exec boil.ContextExecutor) (ExternalTaskSlice, error) {
	var o []*ExternalTask

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to ExternalTask slice")
	}

	if len(externalTaskAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ExternalTask records in the query.
func (q externalTaskQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count external_tasks rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q externalTaskQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if external_tasks exists")
	}

	return count > 0, nil
}

// ScheduledJob pointed to by the foreign key.
func (o *ExternalTask) ScheduledJob(mods ...qm.QueryMod) scheduledJobQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ScheduledJobID),
	}

	queryMods = append(queryMods, mods...)

	return ScheduledJobs(queryMods...)
}

// Source pointed to by the foreign key.
func (o *ExternalTask) Source(mods ...qm.QueryMod) dataSourceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SourceID),
	}

	queryMods = append(queryMods, mods...)

	return DataSources(queryMods...)
}

// Target pointed to by the foreign key.
func (o *ExternalTask) Target(mods ...qm.QueryMod) crawlTargetQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TargetID),
	}

	queryMods = append(queryMods, mods...)

	return CrawlTargets(queryMods...)
}

// RawBatches retrieves all the raw_batch's RawBatches with an executor.
func (o *ExternalTask) RawBatches(mods ...qm.QueryMod) rawBatchQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"schema_ingest\".\"raw_batches\".\"external_task_id\"=?", o.ID),
	)

	return RawBatches(queryMods...)
}

// LoadScheduledJob allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (externalTaskL) LoadScheduledJob(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExternalTask any, mods queries.Applicator) error {
	var slice []*ExternalTask
	var object *ExternalTask

	if singular {
		var ok bool
		object, ok = maybeExternalTask.(*ExternalTask)
		if !ok {
			object = new(ExternalTask)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExternalTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExternalTask))
			}
		}
	} else {
		s, ok := maybeExternalTask.(*[]*ExternalTask)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExternalTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExternalTask))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &externalTaskR{}
		}
		if !queries.IsNil(object.ScheduledJobID) {
			args[object.ScheduledJobID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &externalTaskR{}
			}

			if !queries.IsNil(obj.ScheduledJobID) {
				args[obj.ScheduledJobID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.scheduled_jobs`),
		qm.WhereIn(`schema_ingest.scheduled_jobs.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ScheduledJob")
	}

	var resultSlice []*ScheduledJob
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ScheduledJob")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for scheduled_jobs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for scheduled_jobs")
	}

	if len(scheduledJobAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ScheduledJob = foreign
		if foreign.R == nil {
			foreign.R = &scheduledJobR{}
		}
		foreign.R.ExternalTasks = append(foreign.R.ExternalTasks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ScheduledJobID, foreign.ID) {
				local.R.ScheduledJob = foreign
				if foreign.R == nil {
					foreign.R = &scheduledJobR{}
				}
				foreign.R.ExternalTasks = append(foreign.R.ExternalTasks, local)
				break
			}
		}
	}

	return nil
}

// LoadSource allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (externalTaskL) LoadSource(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExternalTask any, mods queries.Applicator) error {
	var slice []*ExternalTask
	var object *ExternalTask

	if singular {
		var ok bool
		object, ok = maybeExternalTask.(*ExternalTask)
		if !ok {
			object = new(ExternalTask)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExternalTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExternalTask))
			}
		}
	} else {
		s, ok := maybeExternalTask.(*[]*ExternalTask)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExternalTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExternalTask))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &externalTaskR{}
		}
		args[object.SourceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &externalTaskR{}
			}

			args[obj.SourceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.data_sources`),
		qm.WhereIn(`schema_ingest.data_sources.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`schema_ingest.data_sources.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataSource")
	}

	var resultSlice []*DataSource
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataSource")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_sources")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_sources")
	}

	if len(dataSourceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Source = foreign
		if foreign.R == nil {
			foreign.R = &dataSourceR{}
		}
		foreign.R.SourceExternalTasks = append(foreign.R.SourceExternalTasks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SourceID == foreign.ID {
				local.R.Source = foreign
				if foreign.R == nil {
					foreign.R = &dataSourceR{}
				}
				foreign.R.SourceExternalTasks = append(foreign.R.SourceExternalTasks, local)
				break
			}
		}
	}

	return nil
}

// LoadTarget allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (externalTaskL) LoadTarget(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExternalTask any, mods queries.Applicator) error {
	var slice []*ExternalTask
	var object *ExternalTask

	if singular {
		var ok bool
		object, ok = maybeExternalTask.(*ExternalTask)
		if !ok {
			object = new(ExternalTask)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExternalTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExternalTask))
			}
		}
	} else {
		s, ok := maybeExternalTask.(*[]*ExternalTask)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExternalTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExternalTask))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &externalTaskR{}
		}
		if !queries.IsNil(object.TargetID) {
			args[object.TargetID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &externalTaskR{}
			}

			if !queries.IsNil(obj.TargetID) {
				args[obj.TargetID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.crawl_targets`),
		qm.WhereIn(`schema_ingest.crawl_targets.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load CrawlTarget")
	}

	var resultSlice []*CrawlTarget
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice CrawlTarget")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for crawl_targets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for crawl_targets")
	}

	if len(crawlTargetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Target = foreign
		if foreign.R == nil {
			foreign.R = &crawlTargetR{}
		}
		foreign.R.TargetExternalTasks = append(foreign.R.TargetExternalTasks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.TargetID, foreign.ID) {
				local.R.Target = foreign
				if foreign.R == nil {
					foreign.R = &crawlTargetR{}
				}
				foreign.R.TargetExternalTasks = append(foreign.R.TargetExternalTasks, local)
				break
			}
		}
	}

	return nil
}

// LoadRawBatches allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (externalTaskL) LoadRawBatches(ctx context.Context, e boil.ContextExecutor, singular bool, maybeExternalTask any, mods queries.Applicator) error {
	var slice []*ExternalTask
	var object *ExternalTask

	if singular {
		var ok bool
		object, ok = maybeExternalTask.(*ExternalTask)
		if !ok {
			object = new(ExternalTask)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeExternalTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeExternalTask))
			}
		}
	} else {
		s, ok := maybeExternalTask.(*[]*ExternalTask)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeExternalTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeExternalTask))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &externalTaskR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &externalTaskR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`schema_ingest.raw_batches`),
		qm.WhereIn(`schema_ingest.raw_batches.external_task_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load raw_batches")
	}

	var resultSlice []*RawBatch
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice raw_batches")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on raw_batches")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for raw_batches")
	}

	if len(rawBatchAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RawBatches = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &rawBatchR{}
			}
			foreign.R.ExternalTask = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ExternalTaskID) {
				local.R.RawBatches = append(local.R.RawBatches, foreign)
				if foreign.R == nil {
					foreign.R = &rawBatchR{}
				}
				foreign.R.ExternalTask = local
				break
			}
		}
	}

	return nil
}

// SetScheduledJob of the externalTask to the related item.
// Sets o.R.ScheduledJob to related.
// Adds o to related.R.ExternalTasks.
func (o *ExternalTask) SetScheduledJob(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ScheduledJob) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"schema_ingest\".\"external_tasks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"scheduled_job_id"}),
		strmangle.WhereClause("\"", "\"", 2, externalTaskPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ScheduledJobID, related.ID)
	if o.R == nil {
		o.R = &externalTaskR{
			ScheduledJob: related,
		}
	} else {
		o.R.ScheduledJob = related
	}

	if related.R == nil {
		related.R = &scheduledJobR{
			ExternalTasks: ExternalTaskSlice{o},
		}
	} else {
		related.R.ExternalTasks = append(related.R.ExternalTasks, o)
	}

	return nil
}

// RemoveScheduledJob relationship.
// Sets o.R.ScheduledJob to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ExternalTask) RemoveScheduledJob(ctx context.Context, exec boil.ContextExecutor, related *ScheduledJob) error {
	var err error

	queries.SetScanner(&o.ScheduledJobID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("scheduled_job_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ScheduledJob = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ExternalTasks {
		if queries.Equal(o.ScheduledJobID, ri.ScheduledJobID) {
			continue
		}

		ln := len(related.R.ExternalTasks)
		if ln > 1 && i < ln-1 {
			related.R.ExternalTasks[i] = related.R.ExternalTasks[ln-1]
		}
		related.R.ExternalTasks = related.R.ExternalTasks[:ln-1]
		break
	}
	return nil
}

// SetSource of the externalTask to the related item.
// Sets o.R.Source to related.
// Adds o to related.R.SourceExternalTasks.
func (o *ExternalTask) SetSource(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataSource) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"schema_ingest\".\"external_tasks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
		strmangle.WhereClause("\"", "\"", 2, externalTaskPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SourceID = related.ID
	if o.R == nil {
		o.R = &externalTaskR{
			Source: related,
		}
	} else {
		o.R.Source = related
	}

	if related.R == nil {
		related.R = &dataSourceR{
			SourceExternalTasks: ExternalTaskSlice{o},
		}
	} else {
		related.R.SourceExternalTasks = append(related.R.SourceExternalTasks, o)
	}

	return nil
}

// SetTarget of the externalTask to the related item.
// Sets o.R.Target to related.
// Adds o to related.R.TargetExternalTasks.
func (o *ExternalTask) SetTarget(ctx context.Context, exec boil.ContextExecutor, insert bool, related *CrawlTarget) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"schema_ingest\".\"external_tasks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"target_id"}),
		strmangle.WhereClause("\"", "\"", 2, externalTaskPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.TargetID, related.ID)
	if o.R == nil {
		o.R = &externalTaskR{
			Target: related,
		}
	} else {
		o.R.Target = related
	}

	if related.R == nil {
		related.R = &crawlTargetR{
			TargetExternalTasks: ExternalTaskSlice{o},
		}
	} else {
		related.R.TargetExternalTasks = append(related.R.TargetExternalTasks, o)
	}

	return nil
}

// RemoveTarget relationship.
// Sets o.R.Target to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ExternalTask) RemoveTarget(ctx context.Context, exec boil.ContextExecutor, related *CrawlTarget) error {
	var err error

	queries.SetScanner(&o.TargetID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("target_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Target = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.TargetExternalTasks {
		if queries.Equal(o.TargetID, ri.TargetID) {
			continue
		}

		ln := len(related.R.TargetExternalTasks)
		if ln > 1 && i < ln-1 {
			related.R.TargetExternalTasks[i] = related.R.TargetExternalTasks[ln-1]
		}
		related.R.TargetExternalTasks = related.R.TargetExternalTasks[:ln-1]
		break
	}
	return nil
}

// AddRawBatches adds the given related objects to the existing relationships
// of the external_task, optionally inserting them as new records.
// Appends related to o.R.RawBatches.
// Sets related.R.ExternalTask appropriately.
func (o *ExternalTask) AddRawBatches(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RawBatch) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ExternalTaskID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"schema_ingest\".\"raw_batches\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"external_task_id"}),
				strmangle.WhereClause("\"", "\"", 2, rawBatchPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ExternalTaskID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &externalTaskR{
			RawBatches: related,
		}
	} else {
		o.R.RawBatches = append(o.R.RawBatches, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &rawBatchR{
				ExternalTask: o,
			}
		} else {
			rel.R.ExternalTask = o
		}
	}
	return nil
}

// SetRawBatches removes all previously related items of the
// external_task replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ExternalTask's RawBatches accordingly.
// Replaces o.R.RawBatches with related.
// Sets related.R.ExternalTask's RawBatches accordingly.
func (o *ExternalTask) SetRawBatches(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RawBatch) error {
	query := "update \"schema_ingest\".\"raw_batches\" set \"external_task_id\" = null where \"external_task_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.RawBatches {
			queries.SetScanner(&rel.ExternalTaskID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.ExternalTask = nil
		}
		o.R.RawBatches = nil
	}

	return o.AddRawBatches(ctx, exec, insert, related...)
}

// RemoveRawBatches relationships from objects passed in.
// Removes related items from R.RawBatches (uses pointer comparison, removal does not keep order)
// Sets related.R.ExternalTask.
func (o *ExternalTask) RemoveRawBatches(ctx context.Context, exec boil.ContextExecutor, related ...*RawBatch) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ExternalTaskID, nil)
		if rel.R != nil {
			rel.R.ExternalTask = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("external_task_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.RawBatches {
			if rel != ri {
				continue
			}

			ln := len(o.R.RawBatches)
			if ln > 1 && i < ln-1 {
				o.R.RawBatches[i] = o.R.RawBatches[ln-1]
			}
			o.R.RawBatches = o.R.RawBatches[:ln-1]
			break
		}
	}

	return nil
}

// ExternalTasks retrieves all the records using an executor.
func ExternalTasks(mods ...qm.QueryMod) externalTaskQuery {
	mods = append(mods, qm.From("\"schema_ingest\".\"external_tasks\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"schema_ingest\".\"external_tasks\".*"})
	}

	return externalTaskQuery{q}
}

// FindExternalTask retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindExternalTask(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ExternalTask, error) {
	externalTaskObj := &ExternalTask{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"schema_ingest\".\"external_tasks\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, externalTaskObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from external_tasks")
	}

	if err = externalTaskObj.doAfterSelectHooks(ctx, exec); err != nil {
		return externalTaskObj, err
	}

	return externalTaskObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ExternalTask) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no external_tasks provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(externalTaskColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	externalTaskInsertCacheMut.RLock()
	cache, cached := externalTaskInsertCache[key]
	externalTaskInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			externalTaskAllColumns,
			externalTaskColumnsWithDefault,
			externalTaskColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(externalTaskType, externalTaskMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(externalTaskType, externalTaskMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"schema_ingest\".\"external_tasks\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"schema_ingest\".\"external_tasks\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into external_tasks")
	}

	if !cached {
		externalTaskInsertCacheMut.Lock()
		externalTaskInsertCache[key] = cache
		externalTaskInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ExternalTask.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ExternalTask) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	externalTaskUpdateCacheMut.RLock()
	cache, cached := externalTaskUpdateCache[key]
	externalTaskUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			externalTaskAllColumns,
			externalTaskPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update external_tasks, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"schema_ingest\".\"external_tasks\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, externalTaskPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(externalTaskType, externalTaskMapping, append(wl, externalTaskPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update external_tasks row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for external_tasks")
	}

	if !cached {
		externalTaskUpdateCacheMut.Lock()
		externalTaskUpdateCache[key] = cache
		externalTaskUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q externalTaskQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for external_tasks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for external_tasks")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ExternalTaskSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalTaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"schema_ingest\".\"external_tasks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, externalTaskPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in externalTask slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all externalTask")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ExternalTask) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no external_tasks provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(externalTaskColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	externalTaskUpsertCacheMut.RLock()
	cache, cached := externalTaskUpsertCache[key]
	externalTaskUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			externalTaskAllColumns,
			externalTaskColumnsWithDefault,
			externalTaskColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			externalTaskAllColumns,
			externalTaskPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert external_tasks, could not build update column list")
		}

		ret := strmangle.SetComplement(externalTaskAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(externalTaskPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert external_tasks, could not build conflict column list")
			}

			conflict = make([]string, len(externalTaskPrimaryKeyColumns))
			copy(conflict, externalTaskPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"schema_ingest\".\"external_tasks\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(externalTaskType, externalTaskMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(externalTaskType, externalTaskMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert external_tasks")
	}

	if !cached {
		externalTaskUpsertCacheMut.Lock()
		externalTaskUpsertCache[key] = cache
		externalTaskUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ExternalTask record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ExternalTask) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no ExternalTask provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), externalTaskPrimaryKeyMapping)
	sql := "DELETE FROM \"schema_ingest\".\"external_tasks\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from external_tasks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for external_tasks")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q externalTaskQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no externalTaskQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from external_tasks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for external_tasks")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ExternalTaskSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(externalTaskBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalTaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"schema_ingest\".\"external_tasks\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, externalTaskPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from externalTask slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for external_tasks")
	}

	if len(externalTaskAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ExternalTask) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindExternalTask(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExternalTaskSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ExternalTaskSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), externalTaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"schema_ingest\".\"external_tasks\".* FROM \"schema_ingest\".\"external_tasks\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, externalTaskPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in ExternalTaskSlice")
	}

	*o = slice

	return nil
}

// ExternalTaskExists checks if the ExternalTask row exists.
func ExternalTaskExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"schema_ingest\".\"external_tasks\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if external_tasks exists")
	}

	return exists, nil
}

// Exists checks if the ExternalTask row exists.
func (o *ExternalTask) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ExternalTaskExists(ctx, exec, o.ID)
}
