// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// RawBatch is an object representing the database table.
type RawBatch struct {
	ID                 string        `boil:"id" json:"id" toml:"id" yaml:"id"`
	SourceID           string        `boil:"source_id" json:"source_id" toml:"source_id" yaml:"source_id"`
	ProjectID          string        `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	DomainTypeCode     string        `boil:"domain_type_code" json:"domain_type_code" toml:"domain_type_code" yaml:"domain_type_code"`
	ExternalTaskID     null.String   `boil:"external_task_id" json:"external_task_id,omitempty" toml:"external_task_id" yaml:"external_task_id,omitempty"`
	BatchID            string        `boil:"batch_id" json:"batch_id" toml:"batch_id" yaml:"batch_id"`
	Status             BatchStatus   `boil:"status" json:"status" toml:"status" yaml:"status"`
	StorageBucket      string        `boil:"storage_bucket" json:"storage_bucket" toml:"storage_bucket" yaml:"storage_bucket"`
	StoragePath        string        `boil:"storage_path" json:"storage_path" toml:"storage_path" yaml:"storage_path"`
	StorageURL         null.String   `boil:"storage_url" json:"storage_url,omitempty" toml:"storage_url" yaml:"storage_url,omitempty"`
	ItemCount          null.Int      `boil:"item_count" json:"item_count,omitempty" toml:"item_count" yaml:"item_count,omitempty"`
	SizeBytes          null.Int64    `boil:"size_bytes" json:"size_bytes,omitempty" toml:"size_bytes" yaml:"size_bytes,omitempty"`
	Checksum           null.String   `boil:"checksum" json:"checksum,omitempty" toml:"checksum" yaml:"checksum,omitempty"`
	ReceivedAt         time.Time     `boil:"received_at" json:"received_at" toml:"received_at" yaml:"received_at"`
	ParsedAt           null.Time     `boil:"parsed_at" json:"parsed_at,omitempty" toml:"parsed_at" yaml:"parsed_at,omitempty"`
	PublishStatus      PublishStatus `boil:"publish_status" json:"publish_status" toml:"publish_status" yaml:"publish_status"`
	PublishRecordCount int           `boil:"publish_record_count" json:"publish_record_count" toml:"publish_record_count" yaml:"publish_record_count"`
	FirstEventID       null.String   `boil:"first_event_id" json:"first_event_id,omitempty" toml:"first_event_id" yaml:"first_event_id,omitempty"`
	LastEventID        null.String   `boil:"last_event_id" json:"last_event_id,omitempty" toml:"last_event_id" yaml:"last_event_id,omitempty"`
	UapPublishedAt     null.Time     `boil:"uap_published_at" json:"uap_published_at,omitempty" toml:"uap_published_at" yaml:"uap_published_at,omitempty"`
	ErrorMessage       null.String   `boil:"error_message" json:"error_message,omitempty" toml:"error_message" yaml:"error_message,omitempty"`
	PublishError       null.String   `boil:"publish_error" json:"publish_error,omitempty" toml:"publish_error" yaml:"publish_error,omitempty"`
	RawMetadata        null.JSON     `boil:"raw_metadata" json:"raw_metadata,omitempty" toml:"raw_metadata" yaml:"raw_metadata,omitempty"`
	CreatedAt          time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *rawBatchR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L rawBatchL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RawBatchColumns = struct {
	ID                 string
	SourceID           string
	ProjectID          string
	DomainTypeCode     string
	ExternalTaskID     string
	BatchID            string
	Status             string
	StorageBucket      string
	StoragePath        string
	StorageURL         string
	ItemCount          string
	SizeBytes          string
	Checksum           string
	ReceivedAt         string
	ParsedAt           string
	PublishStatus      string
	PublishRecordCount string
	FirstEventID       string
	LastEventID        string
	UapPublishedAt     string
	ErrorMessage       string
	PublishError       string
	RawMetadata        string
	CreatedAt          string
}{
	ID:                 "id",
	SourceID:           "source_id",
	ProjectID:          "project_id",
	DomainTypeCode:     "domain_type_code",
	ExternalTaskID:     "external_task_id",
	BatchID:            "batch_id",
	Status:             "status",
	StorageBucket:      "storage_bucket",
	StoragePath:        "storage_path",
	StorageURL:         "storage_url",
	ItemCount:          "item_count",
	SizeBytes:          "size_bytes",
	Checksum:           "checksum",
	ReceivedAt:         "received_at",
	ParsedAt:           "parsed_at",
	PublishStatus:      "publish_status",
	PublishRecordCount: "publish_record_count",
	FirstEventID:       "first_event_id",
	LastEventID:        "last_event_id",
	UapPublishedAt:     "uap_published_at",
	ErrorMessage:       "error_message",
	PublishError:       "publish_error",
	RawMetadata:        "raw_metadata",
	CreatedAt:          "created_at",
}

var RawBatchTableColumns = struct {
	ID                 string
	SourceID           string
	ProjectID          string
	DomainTypeCode     string
	ExternalTaskID     string
	BatchID            string
	Status             string
	StorageBucket      string
	StoragePath        string
	StorageURL         string
	ItemCount          string
	SizeBytes          string
	Checksum           string
	ReceivedAt         string
	ParsedAt           string
	PublishStatus      string
	PublishRecordCount string
	FirstEventID       string
	LastEventID        string
	UapPublishedAt     string
	ErrorMessage       string
	PublishError       string
	RawMetadata        string
	CreatedAt          string
}{
	ID:                 "raw_batches.id",
	SourceID:           "raw_batches.source_id",
	ProjectID:          "raw_batches.project_id",
	DomainTypeCode:     "raw_batches.domain_type_code",
	ExternalTaskID:     "raw_batches.external_task_id",
	BatchID:            "raw_batches.batch_id",
	Status:             "raw_batches.status",
	StorageBucket:      "raw_batches.storage_bucket",
	StoragePath:        "raw_batches.storage_path",
	StorageURL:         "raw_batches.storage_url",
	ItemCount:          "raw_batches.item_count",
	SizeBytes:          "raw_batches.size_bytes",
	Checksum:           "raw_batches.checksum",
	ReceivedAt:         "raw_batches.received_at",
	ParsedAt:           "raw_batches.parsed_at",
	PublishStatus:      "raw_batches.publish_status",
	PublishRecordCount: "raw_batches.publish_record_count",
	FirstEventID:       "raw_batches.first_event_id",
	LastEventID:        "raw_batches.last_event_id",
	UapPublishedAt:     "raw_batches.uap_published_at",
	ErrorMessage:       "raw_batches.error_message",
	PublishError:       "raw_batches.publish_error",
	RawMetadata:        "raw_batches.raw_metadata",
	CreatedAt:          "raw_batches.created_at",
}

// Generated where

type whereHelperBatchStatus struct{ field string }

func (w whereHelperBatchStatus) EQ(x BatchStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperBatchStatus) NEQ(x BatchStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperBatchStatus) LT(x BatchStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperBatchStatus) LTE(x BatchStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperBatchStatus) GT(x BatchStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperBatchStatus) GTE(x BatchStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperBatchStatus) IN(slice []BatchStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperBatchStatus) NIN(slice []BatchStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Int64 struct{ field string }

func (w whereHelpernull_Int64) EQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int64) NEQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int64) LT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int64) LTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int64) GT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int64) GTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperPublishStatus struct{ field string }

func (w whereHelperPublishStatus) EQ(x PublishStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperPublishStatus) NEQ(x PublishStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperPublishStatus) LT(x PublishStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperPublishStatus) LTE(x PublishStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperPublishStatus) GT(x PublishStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperPublishStatus) GTE(x PublishStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperPublishStatus) IN(slice []PublishStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperPublishStatus) NIN(slice []PublishStatus) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var RawBatchWhere = struct {
	ID                 whereHelperstring
	SourceID           whereHelperstring
	ProjectID          whereHelperstring
	DomainTypeCode     whereHelperstring
	ExternalTaskID     whereHelpernull_String
	BatchID            whereHelperstring
	Status             whereHelperBatchStatus
	StorageBucket      whereHelperstring
	StoragePath        whereHelperstring
	StorageURL         whereHelpernull_String
	ItemCount          whereHelpernull_Int
	SizeBytes          whereHelpernull_Int64
	Checksum           whereHelpernull_String
	ReceivedAt         whereHelpertime_Time
	ParsedAt           whereHelpernull_Time
	PublishStatus      whereHelperPublishStatus
	PublishRecordCount whereHelperint
	FirstEventID       whereHelpernull_String
	LastEventID        whereHelpernull_String
	UapPublishedAt     whereHelpernull_Time
	ErrorMessage       whereHelpernull_String
	PublishError       whereHelpernull_String
	RawMetadata        whereHelpernull_JSON
	CreatedAt          whereHelpertime_Time
}{
	ID:                 whereHelperstring{field: "\"ingest\".\"raw_batches\".\"id\""},
	SourceID:           whereHelperstring{field: "\"ingest\".\"raw_batches\".\"source_id\""},
	ProjectID:          whereHelperstring{field: "\"ingest\".\"raw_batches\".\"project_id\""},
	DomainTypeCode:     whereHelperstring{field: "\"ingest\".\"raw_batches\".\"domain_type_code\""},
	ExternalTaskID:     whereHelpernull_String{field: "\"ingest\".\"raw_batches\".\"external_task_id\""},
	BatchID:            whereHelperstring{field: "\"ingest\".\"raw_batches\".\"batch_id\""},
	Status:             whereHelperBatchStatus{field: "\"ingest\".\"raw_batches\".\"status\""},
	StorageBucket:      whereHelperstring{field: "\"ingest\".\"raw_batches\".\"storage_bucket\""},
	StoragePath:        whereHelperstring{field: "\"ingest\".\"raw_batches\".\"storage_path\""},
	StorageURL:         whereHelpernull_String{field: "\"ingest\".\"raw_batches\".\"storage_url\""},
	ItemCount:          whereHelpernull_Int{field: "\"ingest\".\"raw_batches\".\"item_count\""},
	SizeBytes:          whereHelpernull_Int64{field: "\"ingest\".\"raw_batches\".\"size_bytes\""},
	Checksum:           whereHelpernull_String{field: "\"ingest\".\"raw_batches\".\"checksum\""},
	ReceivedAt:         whereHelpertime_Time{field: "\"ingest\".\"raw_batches\".\"received_at\""},
	ParsedAt:           whereHelpernull_Time{field: "\"ingest\".\"raw_batches\".\"parsed_at\""},
	PublishStatus:      whereHelperPublishStatus{field: "\"ingest\".\"raw_batches\".\"publish_status\""},
	PublishRecordCount: whereHelperint{field: "\"ingest\".\"raw_batches\".\"publish_record_count\""},
	FirstEventID:       whereHelpernull_String{field: "\"ingest\".\"raw_batches\".\"first_event_id\""},
	LastEventID:        whereHelpernull_String{field: "\"ingest\".\"raw_batches\".\"last_event_id\""},
	UapPublishedAt:     whereHelpernull_Time{field: "\"ingest\".\"raw_batches\".\"uap_published_at\""},
	ErrorMessage:       whereHelpernull_String{field: "\"ingest\".\"raw_batches\".\"error_message\""},
	PublishError:       whereHelpernull_String{field: "\"ingest\".\"raw_batches\".\"publish_error\""},
	RawMetadata:        whereHelpernull_JSON{field: "\"ingest\".\"raw_batches\".\"raw_metadata\""},
	CreatedAt:          whereHelpertime_Time{field: "\"ingest\".\"raw_batches\".\"created_at\""},
}

// RawBatchRels is where relationship names are stored.
var RawBatchRels = struct {
	ExternalTask string
	Source       string
}{
	ExternalTask: "ExternalTask",
	Source:       "Source",
}

// rawBatchR is where relationships are stored.
type rawBatchR struct {
	ExternalTask *ExternalTask `boil:"ExternalTask" json:"ExternalTask" toml:"ExternalTask" yaml:"ExternalTask"`
	Source       *DataSource   `boil:"Source" json:"Source" toml:"Source" yaml:"Source"`
}

// NewStruct creates a new relationship struct
func (*rawBatchR) NewStruct() *rawBatchR {
	return &rawBatchR{}
}

func (o *RawBatch) GetExternalTask() *ExternalTask {
	if o == nil {
		return nil
	}

	return o.R.GetExternalTask()
}

func (r *rawBatchR) GetExternalTask() *ExternalTask {
	if r == nil {
		return nil
	}

	return r.ExternalTask
}

func (o *RawBatch) GetSource() *DataSource {
	if o == nil {
		return nil
	}

	return o.R.GetSource()
}

func (r *rawBatchR) GetSource() *DataSource {
	if r == nil {
		return nil
	}

	return r.Source
}

// rawBatchL is where Load methods for each relationship are stored.
type rawBatchL struct{}

var (
	rawBatchAllColumns            = []string{"id", "source_id", "project_id", "domain_type_code", "external_task_id", "batch_id", "status", "storage_bucket", "storage_path", "storage_url", "item_count", "size_bytes", "checksum", "received_at", "parsed_at", "publish_status", "publish_record_count", "first_event_id", "last_event_id", "uap_published_at", "error_message", "publish_error", "raw_metadata", "created_at"}
	rawBatchColumnsWithoutDefault = []string{"id", "source_id", "project_id", "batch_id", "storage_bucket", "storage_path"}
	rawBatchColumnsWithDefault    = []string{"domain_type_code", "external_task_id", "status", "storage_url", "item_count", "size_bytes", "checksum", "received_at", "parsed_at", "publish_status", "publish_record_count", "first_event_id", "last_event_id", "uap_published_at", "error_message", "publish_error", "raw_metadata", "created_at"}
	rawBatchPrimaryKeyColumns     = []string{"id"}
	rawBatchGeneratedColumns      = []string{}
)

type (
	// RawBatchSlice is an alias for a slice of pointers to RawBatch.
	// This should almost always be used instead of []RawBatch.
	RawBatchSlice []*RawBatch
	// RawBatchHook is the signature for custom RawBatch hook methods
	RawBatchHook func(context.Context, boil.ContextExecutor, *RawBatch) error

	rawBatchQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	rawBatchType                 = reflect.TypeOf(&RawBatch{})
	rawBatchMapping              = queries.MakeStructMapping(rawBatchType)
	rawBatchPrimaryKeyMapping, _ = queries.BindMapping(rawBatchType, rawBatchMapping, rawBatchPrimaryKeyColumns)
	rawBatchInsertCacheMut       sync.RWMutex
	rawBatchInsertCache          = make(map[string]insertCache)
	rawBatchUpdateCacheMut       sync.RWMutex
	rawBatchUpdateCache          = make(map[string]updateCache)
	rawBatchUpsertCacheMut       sync.RWMutex
	rawBatchUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var rawBatchAfterSelectMu sync.Mutex
var rawBatchAfterSelectHooks []RawBatchHook

var rawBatchBeforeInsertMu sync.Mutex
var rawBatchBeforeInsertHooks []RawBatchHook
var rawBatchAfterInsertMu sync.Mutex
var rawBatchAfterInsertHooks []RawBatchHook

var rawBatchBeforeUpdateMu sync.Mutex
var rawBatchBeforeUpdateHooks []RawBatchHook
var rawBatchAfterUpdateMu sync.Mutex
var rawBatchAfterUpdateHooks []RawBatchHook

var rawBatchBeforeDeleteMu sync.Mutex
var rawBatchBeforeDeleteHooks []RawBatchHook
var rawBatchAfterDeleteMu sync.Mutex
var rawBatchAfterDeleteHooks []RawBatchHook

var rawBatchBeforeUpsertMu sync.Mutex
var rawBatchBeforeUpsertHooks []RawBatchHook
var rawBatchAfterUpsertMu sync.Mutex
var rawBatchAfterUpsertHooks []RawBatchHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *RawBatch) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *RawBatch) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *RawBatch) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *RawBatch) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *RawBatch) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *RawBatch) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *RawBatch) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *RawBatch) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *RawBatch) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rawBatchAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRawBatchHook registers your hook function for all future operations.
func AddRawBatchHook(hookPoint boil.HookPoint, rawBatchHook RawBatchHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		rawBatchAfterSelectMu.Lock()
		rawBatchAfterSelectHooks = append(rawBatchAfterSelectHooks, rawBatchHook)
		rawBatchAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		rawBatchBeforeInsertMu.Lock()
		rawBatchBeforeInsertHooks = append(rawBatchBeforeInsertHooks, rawBatchHook)
		rawBatchBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		rawBatchAfterInsertMu.Lock()
		rawBatchAfterInsertHooks = append(rawBatchAfterInsertHooks, rawBatchHook)
		rawBatchAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		rawBatchBeforeUpdateMu.Lock()
		rawBatchBeforeUpdateHooks = append(rawBatchBeforeUpdateHooks, rawBatchHook)
		rawBatchBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		rawBatchAfterUpdateMu.Lock()
		rawBatchAfterUpdateHooks = append(rawBatchAfterUpdateHooks, rawBatchHook)
		rawBatchAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		rawBatchBeforeDeleteMu.Lock()
		rawBatchBeforeDeleteHooks = append(rawBatchBeforeDeleteHooks, rawBatchHook)
		rawBatchBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		rawBatchAfterDeleteMu.Lock()
		rawBatchAfterDeleteHooks = append(rawBatchAfterDeleteHooks, rawBatchHook)
		rawBatchAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		rawBatchBeforeUpsertMu.Lock()
		rawBatchBeforeUpsertHooks = append(rawBatchBeforeUpsertHooks, rawBatchHook)
		rawBatchBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		rawBatchAfterUpsertMu.Lock()
		rawBatchAfterUpsertHooks = append(rawBatchAfterUpsertHooks, rawBatchHook)
		rawBatchAfterUpsertMu.Unlock()
	}
}

// One returns a single rawBatch record from the query.
func (q rawBatchQuery) One(ctx context.Context, exec boil.ContextExecutor) (*RawBatch, error) {
	o := &RawBatch{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for raw_batches")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all RawBatch records from the query.
func (q rawBatchQuery) All(ctx context.Context, exec boil.ContextExecutor) (RawBatchSlice, error) {
	var o []*RawBatch

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to RawBatch slice")
	}

	if len(rawBatchAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all RawBatch records in the query.
func (q rawBatchQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count raw_batches rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q rawBatchQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if raw_batches exists")
	}

	return count > 0, nil
}

// ExternalTask pointed to by the foreign key.
func (o *RawBatch) ExternalTask(mods ...qm.QueryMod) externalTaskQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ExternalTaskID),
	}

	queryMods = append(queryMods, mods...)

	return ExternalTasks(queryMods...)
}

// Source pointed to by the foreign key.
func (o *RawBatch) Source(mods ...qm.QueryMod) dataSourceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SourceID),
	}

	queryMods = append(queryMods, mods...)

	return DataSources(queryMods...)
}

// LoadExternalTask allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (rawBatchL) LoadExternalTask(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRawBatch any, mods queries.Applicator) error {
	var slice []*RawBatch
	var object *RawBatch

	if singular {
		var ok bool
		object, ok = maybeRawBatch.(*RawBatch)
		if !ok {
			object = new(RawBatch)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRawBatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRawBatch))
			}
		}
	} else {
		s, ok := maybeRawBatch.(*[]*RawBatch)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRawBatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRawBatch))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &rawBatchR{}
		}
		if !queries.IsNil(object.ExternalTaskID) {
			args[object.ExternalTaskID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &rawBatchR{}
			}

			if !queries.IsNil(obj.ExternalTaskID) {
				args[obj.ExternalTaskID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.external_tasks`),
		qm.WhereIn(`ingest.external_tasks.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ExternalTask")
	}

	var resultSlice []*ExternalTask
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ExternalTask")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for external_tasks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for external_tasks")
	}

	if len(externalTaskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ExternalTask = foreign
		if foreign.R == nil {
			foreign.R = &externalTaskR{}
		}
		foreign.R.RawBatches = append(foreign.R.RawBatches, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ExternalTaskID, foreign.ID) {
				local.R.ExternalTask = foreign
				if foreign.R == nil {
					foreign.R = &externalTaskR{}
				}
				foreign.R.RawBatches = append(foreign.R.RawBatches, local)
				break
			}
		}
	}

	return nil
}

// LoadSource allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (rawBatchL) LoadSource(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRawBatch any, mods queries.Applicator) error {
	var slice []*RawBatch
	var object *RawBatch

	if singular {
		var ok bool
		object, ok = maybeRawBatch.(*RawBatch)
		if !ok {
			object = new(RawBatch)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRawBatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRawBatch))
			}
		}
	} else {
		s, ok := maybeRawBatch.(*[]*RawBatch)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRawBatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRawBatch))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &rawBatchR{}
		}
		args[object.SourceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &rawBatchR{}
			}

			args[obj.SourceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.data_sources`),
		qm.WhereIn(`ingest.data_sources.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`ingest.data_sources.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataSource")
	}

	var resultSlice []*DataSource
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataSource")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_sources")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_sources")
	}

	if len(dataSourceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Source = foreign
		if foreign.R == nil {
			foreign.R = &dataSourceR{}
		}
		foreign.R.SourceRawBatches = append(foreign.R.SourceRawBatches, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SourceID == foreign.ID {
				local.R.Source = foreign
				if foreign.R == nil {
					foreign.R = &dataSourceR{}
				}
				foreign.R.SourceRawBatches = append(foreign.R.SourceRawBatches, local)
				break
			}
		}
	}

	return nil
}

// SetExternalTask of the rawBatch to the related item.
// Sets o.R.ExternalTask to related.
// Adds o to related.R.RawBatches.
func (o *RawBatch) SetExternalTask(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ExternalTask) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ingest\".\"raw_batches\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"external_task_id"}),
		strmangle.WhereClause("\"", "\"", 2, rawBatchPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ExternalTaskID, related.ID)
	if o.R == nil {
		o.R = &rawBatchR{
			ExternalTask: related,
		}
	} else {
		o.R.ExternalTask = related
	}

	if related.R == nil {
		related.R = &externalTaskR{
			RawBatches: RawBatchSlice{o},
		}
	} else {
		related.R.RawBatches = append(related.R.RawBatches, o)
	}

	return nil
}

// RemoveExternalTask relationship.
// Sets o.R.ExternalTask to nil.
// Removes o from all passed in related items' relationships struct.
func (o *RawBatch) RemoveExternalTask(ctx context.Context, exec boil.ContextExecutor, related *ExternalTask) error {
	var err error

	queries.SetScanner(&o.ExternalTaskID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("external_task_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ExternalTask = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.RawBatches {
		if queries.Equal(o.ExternalTaskID, ri.ExternalTaskID) {
			continue
		}

		ln := len(related.R.RawBatches)
		if ln > 1 && i < ln-1 {
			related.R.RawBatches[i] = related.R.RawBatches[ln-1]
		}
		related.R.RawBatches = related.R.RawBatches[:ln-1]
		break
	}
	return nil
}

// SetSource of the rawBatch to the related item.
// Sets o.R.Source to related.
// Adds o to related.R.SourceRawBatches.
func (o *RawBatch) SetSource(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataSource) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ingest\".\"raw_batches\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
		strmangle.WhereClause("\"", "\"", 2, rawBatchPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SourceID = related.ID
	if o.R == nil {
		o.R = &rawBatchR{
			Source: related,
		}
	} else {
		o.R.Source = related
	}

	if related.R == nil {
		related.R = &dataSourceR{
			SourceRawBatches: RawBatchSlice{o},
		}
	} else {
		related.R.SourceRawBatches = append(related.R.SourceRawBatches, o)
	}

	return nil
}

// RawBatches retrieves all the records using an executor.
func RawBatches(mods ...qm.QueryMod) rawBatchQuery {
	mods = append(mods, qm.From("\"ingest\".\"raw_batches\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ingest\".\"raw_batches\".*"})
	}

	return rawBatchQuery{q}
}

// FindRawBatch retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRawBatch(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*RawBatch, error) {
	rawBatchObj := &RawBatch{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ingest\".\"raw_batches\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, rawBatchObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from raw_batches")
	}

	if err = rawBatchObj.doAfterSelectHooks(ctx, exec); err != nil {
		return rawBatchObj, err
	}

	return rawBatchObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RawBatch) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no raw_batches provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rawBatchColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	rawBatchInsertCacheMut.RLock()
	cache, cached := rawBatchInsertCache[key]
	rawBatchInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			rawBatchAllColumns,
			rawBatchColumnsWithDefault,
			rawBatchColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(rawBatchType, rawBatchMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(rawBatchType, rawBatchMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ingest\".\"raw_batches\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ingest\".\"raw_batches\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into raw_batches")
	}

	if !cached {
		rawBatchInsertCacheMut.Lock()
		rawBatchInsertCache[key] = cache
		rawBatchInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the RawBatch.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RawBatch) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	rawBatchUpdateCacheMut.RLock()
	cache, cached := rawBatchUpdateCache[key]
	rawBatchUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			rawBatchAllColumns,
			rawBatchPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update raw_batches, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ingest\".\"raw_batches\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, rawBatchPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(rawBatchType, rawBatchMapping, append(wl, rawBatchPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update raw_batches row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for raw_batches")
	}

	if !cached {
		rawBatchUpdateCacheMut.Lock()
		rawBatchUpdateCache[key] = cache
		rawBatchUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q rawBatchQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for raw_batches")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for raw_batches")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RawBatchSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rawBatchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ingest\".\"raw_batches\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, rawBatchPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in rawBatch slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all rawBatch")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RawBatch) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no raw_batches provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rawBatchColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	rawBatchUpsertCacheMut.RLock()
	cache, cached := rawBatchUpsertCache[key]
	rawBatchUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			rawBatchAllColumns,
			rawBatchColumnsWithDefault,
			rawBatchColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			rawBatchAllColumns,
			rawBatchPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert raw_batches, could not build update column list")
		}

		ret := strmangle.SetComplement(rawBatchAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(rawBatchPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert raw_batches, could not build conflict column list")
			}

			conflict = make([]string, len(rawBatchPrimaryKeyColumns))
			copy(conflict, rawBatchPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ingest\".\"raw_batches\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(rawBatchType, rawBatchMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(rawBatchType, rawBatchMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert raw_batches")
	}

	if !cached {
		rawBatchUpsertCacheMut.Lock()
		rawBatchUpsertCache[key] = cache
		rawBatchUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single RawBatch record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RawBatch) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no RawBatch provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), rawBatchPrimaryKeyMapping)
	sql := "DELETE FROM \"ingest\".\"raw_batches\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from raw_batches")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for raw_batches")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q rawBatchQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no rawBatchQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from raw_batches")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for raw_batches")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RawBatchSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(rawBatchBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rawBatchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ingest\".\"raw_batches\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, rawBatchPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from rawBatch slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for raw_batches")
	}

	if len(rawBatchAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RawBatch) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindRawBatch(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RawBatchSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RawBatchSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rawBatchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ingest\".\"raw_batches\".* FROM \"ingest\".\"raw_batches\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, rawBatchPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in RawBatchSlice")
	}

	*o = slice

	return nil
}

// RawBatchExists checks if the RawBatch row exists.
func RawBatchExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ingest\".\"raw_batches\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if raw_batches exists")
	}

	return exists, nil
}

// Exists checks if the RawBatch row exists.
func (o *RawBatch) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return RawBatchExists(ctx, exec, o.ID)
}
