// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ScheduledJob is an object representing the database table.
type ScheduledJob struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	SourceID     string      `boil:"source_id" json:"source_id" toml:"source_id" yaml:"source_id"`
	ProjectID    string      `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	TargetID     null.String `boil:"target_id" json:"target_id,omitempty" toml:"target_id" yaml:"target_id,omitempty"`
	Status       JobStatus   `boil:"status" json:"status" toml:"status" yaml:"status"`
	TriggerType  TriggerType `boil:"trigger_type" json:"trigger_type" toml:"trigger_type" yaml:"trigger_type"`
	CronExpr     null.String `boil:"cron_expr" json:"cron_expr,omitempty" toml:"cron_expr" yaml:"cron_expr,omitempty"`
	CrawlMode    CrawlMode   `boil:"crawl_mode" json:"crawl_mode" toml:"crawl_mode" yaml:"crawl_mode"`
	ScheduledFor time.Time   `boil:"scheduled_for" json:"scheduled_for" toml:"scheduled_for" yaml:"scheduled_for"`
	StartedAt    null.Time   `boil:"started_at" json:"started_at,omitempty" toml:"started_at" yaml:"started_at,omitempty"`
	CompletedAt  null.Time   `boil:"completed_at" json:"completed_at,omitempty" toml:"completed_at" yaml:"completed_at,omitempty"`
	RetryCount   int         `boil:"retry_count" json:"retry_count" toml:"retry_count" yaml:"retry_count"`
	ErrorMessage null.String `boil:"error_message" json:"error_message,omitempty" toml:"error_message" yaml:"error_message,omitempty"`
	Payload      null.JSON   `boil:"payload" json:"payload,omitempty" toml:"payload" yaml:"payload,omitempty"`
	CreatedAt    time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *scheduledJobR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L scheduledJobL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ScheduledJobColumns = struct {
	ID           string
	SourceID     string
	ProjectID    string
	TargetID     string
	Status       string
	TriggerType  string
	CronExpr     string
	CrawlMode    string
	ScheduledFor string
	StartedAt    string
	CompletedAt  string
	RetryCount   string
	ErrorMessage string
	Payload      string
	CreatedAt    string
}{
	ID:           "id",
	SourceID:     "source_id",
	ProjectID:    "project_id",
	TargetID:     "target_id",
	Status:       "status",
	TriggerType:  "trigger_type",
	CronExpr:     "cron_expr",
	CrawlMode:    "crawl_mode",
	ScheduledFor: "scheduled_for",
	StartedAt:    "started_at",
	CompletedAt:  "completed_at",
	RetryCount:   "retry_count",
	ErrorMessage: "error_message",
	Payload:      "payload",
	CreatedAt:    "created_at",
}

var ScheduledJobTableColumns = struct {
	ID           string
	SourceID     string
	ProjectID    string
	TargetID     string
	Status       string
	TriggerType  string
	CronExpr     string
	CrawlMode    string
	ScheduledFor string
	StartedAt    string
	CompletedAt  string
	RetryCount   string
	ErrorMessage string
	Payload      string
	CreatedAt    string
}{
	ID:           "scheduled_jobs.id",
	SourceID:     "scheduled_jobs.source_id",
	ProjectID:    "scheduled_jobs.project_id",
	TargetID:     "scheduled_jobs.target_id",
	Status:       "scheduled_jobs.status",
	TriggerType:  "scheduled_jobs.trigger_type",
	CronExpr:     "scheduled_jobs.cron_expr",
	CrawlMode:    "scheduled_jobs.crawl_mode",
	ScheduledFor: "scheduled_jobs.scheduled_for",
	StartedAt:    "scheduled_jobs.started_at",
	CompletedAt:  "scheduled_jobs.completed_at",
	RetryCount:   "scheduled_jobs.retry_count",
	ErrorMessage: "scheduled_jobs.error_message",
	Payload:      "scheduled_jobs.payload",
	CreatedAt:    "scheduled_jobs.created_at",
}

// Generated where

var ScheduledJobWhere = struct {
	ID           whereHelperstring
	SourceID     whereHelperstring
	ProjectID    whereHelperstring
	TargetID     whereHelpernull_String
	Status       whereHelperJobStatus
	TriggerType  whereHelperTriggerType
	CronExpr     whereHelpernull_String
	CrawlMode    whereHelperCrawlMode
	ScheduledFor whereHelpertime_Time
	StartedAt    whereHelpernull_Time
	CompletedAt  whereHelpernull_Time
	RetryCount   whereHelperint
	ErrorMessage whereHelpernull_String
	Payload      whereHelpernull_JSON
	CreatedAt    whereHelpertime_Time
}{
	ID:           whereHelperstring{field: "\"ingest\".\"scheduled_jobs\".\"id\""},
	SourceID:     whereHelperstring{field: "\"ingest\".\"scheduled_jobs\".\"source_id\""},
	ProjectID:    whereHelperstring{field: "\"ingest\".\"scheduled_jobs\".\"project_id\""},
	TargetID:     whereHelpernull_String{field: "\"ingest\".\"scheduled_jobs\".\"target_id\""},
	Status:       whereHelperJobStatus{field: "\"ingest\".\"scheduled_jobs\".\"status\""},
	TriggerType:  whereHelperTriggerType{field: "\"ingest\".\"scheduled_jobs\".\"trigger_type\""},
	CronExpr:     whereHelpernull_String{field: "\"ingest\".\"scheduled_jobs\".\"cron_expr\""},
	CrawlMode:    whereHelperCrawlMode{field: "\"ingest\".\"scheduled_jobs\".\"crawl_mode\""},
	ScheduledFor: whereHelpertime_Time{field: "\"ingest\".\"scheduled_jobs\".\"scheduled_for\""},
	StartedAt:    whereHelpernull_Time{field: "\"ingest\".\"scheduled_jobs\".\"started_at\""},
	CompletedAt:  whereHelpernull_Time{field: "\"ingest\".\"scheduled_jobs\".\"completed_at\""},
	RetryCount:   whereHelperint{field: "\"ingest\".\"scheduled_jobs\".\"retry_count\""},
	ErrorMessage: whereHelpernull_String{field: "\"ingest\".\"scheduled_jobs\".\"error_message\""},
	Payload:      whereHelpernull_JSON{field: "\"ingest\".\"scheduled_jobs\".\"payload\""},
	CreatedAt:    whereHelpertime_Time{field: "\"ingest\".\"scheduled_jobs\".\"created_at\""},
}

// ScheduledJobRels is where relationship names are stored.
var ScheduledJobRels = struct {
	Target        string
	Source        string
	ExternalTasks string
}{
	Target:        "Target",
	Source:        "Source",
	ExternalTasks: "ExternalTasks",
}

// scheduledJobR is where relationships are stored.
type scheduledJobR struct {
	Target        *CrawlTarget      `boil:"Target" json:"Target" toml:"Target" yaml:"Target"`
	Source        *DataSource       `boil:"Source" json:"Source" toml:"Source" yaml:"Source"`
	ExternalTasks ExternalTaskSlice `boil:"ExternalTasks" json:"ExternalTasks" toml:"ExternalTasks" yaml:"ExternalTasks"`
}

// NewStruct creates a new relationship struct
func (*scheduledJobR) NewStruct() *scheduledJobR {
	return &scheduledJobR{}
}

func (o *ScheduledJob) GetTarget() *CrawlTarget {
	if o == nil {
		return nil
	}

	return o.R.GetTarget()
}

func (r *scheduledJobR) GetTarget() *CrawlTarget {
	if r == nil {
		return nil
	}

	return r.Target
}

func (o *ScheduledJob) GetSource() *DataSource {
	if o == nil {
		return nil
	}

	return o.R.GetSource()
}

func (r *scheduledJobR) GetSource() *DataSource {
	if r == nil {
		return nil
	}

	return r.Source
}

func (o *ScheduledJob) GetExternalTasks() ExternalTaskSlice {
	if o == nil {
		return nil
	}

	return o.R.GetExternalTasks()
}

func (r *scheduledJobR) GetExternalTasks() ExternalTaskSlice {
	if r == nil {
		return nil
	}

	return r.ExternalTasks
}

// scheduledJobL is where Load methods for each relationship are stored.
type scheduledJobL struct{}

var (
	scheduledJobAllColumns            = []string{"id", "source_id", "project_id", "target_id", "status", "trigger_type", "cron_expr", "crawl_mode", "scheduled_for", "started_at", "completed_at", "retry_count", "error_message", "payload", "created_at"}
	scheduledJobColumnsWithoutDefault = []string{"id", "source_id", "project_id", "trigger_type", "crawl_mode", "scheduled_for"}
	scheduledJobColumnsWithDefault    = []string{"target_id", "status", "cron_expr", "started_at", "completed_at", "retry_count", "error_message", "payload", "created_at"}
	scheduledJobPrimaryKeyColumns     = []string{"id"}
	scheduledJobGeneratedColumns      = []string{}
)

type (
	// ScheduledJobSlice is an alias for a slice of pointers to ScheduledJob.
	// This should almost always be used instead of []ScheduledJob.
	ScheduledJobSlice []*ScheduledJob
	// ScheduledJobHook is the signature for custom ScheduledJob hook methods
	ScheduledJobHook func(context.Context, boil.ContextExecutor, *ScheduledJob) error

	scheduledJobQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	scheduledJobType                 = reflect.TypeOf(&ScheduledJob{})
	scheduledJobMapping              = queries.MakeStructMapping(scheduledJobType)
	scheduledJobPrimaryKeyMapping, _ = queries.BindMapping(scheduledJobType, scheduledJobMapping, scheduledJobPrimaryKeyColumns)
	scheduledJobInsertCacheMut       sync.RWMutex
	scheduledJobInsertCache          = make(map[string]insertCache)
	scheduledJobUpdateCacheMut       sync.RWMutex
	scheduledJobUpdateCache          = make(map[string]updateCache)
	scheduledJobUpsertCacheMut       sync.RWMutex
	scheduledJobUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var scheduledJobAfterSelectMu sync.Mutex
var scheduledJobAfterSelectHooks []ScheduledJobHook

var scheduledJobBeforeInsertMu sync.Mutex
var scheduledJobBeforeInsertHooks []ScheduledJobHook
var scheduledJobAfterInsertMu sync.Mutex
var scheduledJobAfterInsertHooks []ScheduledJobHook

var scheduledJobBeforeUpdateMu sync.Mutex
var scheduledJobBeforeUpdateHooks []ScheduledJobHook
var scheduledJobAfterUpdateMu sync.Mutex
var scheduledJobAfterUpdateHooks []ScheduledJobHook

var scheduledJobBeforeDeleteMu sync.Mutex
var scheduledJobBeforeDeleteHooks []ScheduledJobHook
var scheduledJobAfterDeleteMu sync.Mutex
var scheduledJobAfterDeleteHooks []ScheduledJobHook

var scheduledJobBeforeUpsertMu sync.Mutex
var scheduledJobBeforeUpsertHooks []ScheduledJobHook
var scheduledJobAfterUpsertMu sync.Mutex
var scheduledJobAfterUpsertHooks []ScheduledJobHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ScheduledJob) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ScheduledJob) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ScheduledJob) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ScheduledJob) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ScheduledJob) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ScheduledJob) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ScheduledJob) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ScheduledJob) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ScheduledJob) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledJobAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddScheduledJobHook registers your hook function for all future operations.
func AddScheduledJobHook(hookPoint boil.HookPoint, scheduledJobHook ScheduledJobHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		scheduledJobAfterSelectMu.Lock()
		scheduledJobAfterSelectHooks = append(scheduledJobAfterSelectHooks, scheduledJobHook)
		scheduledJobAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		scheduledJobBeforeInsertMu.Lock()
		scheduledJobBeforeInsertHooks = append(scheduledJobBeforeInsertHooks, scheduledJobHook)
		scheduledJobBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		scheduledJobAfterInsertMu.Lock()
		scheduledJobAfterInsertHooks = append(scheduledJobAfterInsertHooks, scheduledJobHook)
		scheduledJobAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		scheduledJobBeforeUpdateMu.Lock()
		scheduledJobBeforeUpdateHooks = append(scheduledJobBeforeUpdateHooks, scheduledJobHook)
		scheduledJobBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		scheduledJobAfterUpdateMu.Lock()
		scheduledJobAfterUpdateHooks = append(scheduledJobAfterUpdateHooks, scheduledJobHook)
		scheduledJobAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		scheduledJobBeforeDeleteMu.Lock()
		scheduledJobBeforeDeleteHooks = append(scheduledJobBeforeDeleteHooks, scheduledJobHook)
		scheduledJobBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		scheduledJobAfterDeleteMu.Lock()
		scheduledJobAfterDeleteHooks = append(scheduledJobAfterDeleteHooks, scheduledJobHook)
		scheduledJobAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		scheduledJobBeforeUpsertMu.Lock()
		scheduledJobBeforeUpsertHooks = append(scheduledJobBeforeUpsertHooks, scheduledJobHook)
		scheduledJobBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		scheduledJobAfterUpsertMu.Lock()
		scheduledJobAfterUpsertHooks = append(scheduledJobAfterUpsertHooks, scheduledJobHook)
		scheduledJobAfterUpsertMu.Unlock()
	}
}

// One returns a single scheduledJob record from the query.
func (q scheduledJobQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ScheduledJob, error) {
	o := &ScheduledJob{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for scheduled_jobs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ScheduledJob records from the query.
func (q scheduledJobQuery) All(ctx context.Context, exec boil.ContextExecutor) (ScheduledJobSlice, error) {
	var o []*ScheduledJob

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to ScheduledJob slice")
	}

	if len(scheduledJobAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ScheduledJob records in the query.
func (q scheduledJobQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count scheduled_jobs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q scheduledJobQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if scheduled_jobs exists")
	}

	return count > 0, nil
}

// Target pointed to by the foreign key.
func (o *ScheduledJob) Target(mods ...qm.QueryMod) crawlTargetQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TargetID),
	}

	queryMods = append(queryMods, mods...)

	return CrawlTargets(queryMods...)
}

// Source pointed to by the foreign key.
func (o *ScheduledJob) Source(mods ...qm.QueryMod) dataSourceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SourceID),
	}

	queryMods = append(queryMods, mods...)

	return DataSources(queryMods...)
}

// ExternalTasks retrieves all the external_task's ExternalTasks with an executor.
func (o *ScheduledJob) ExternalTasks(mods ...qm.QueryMod) externalTaskQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ingest\".\"external_tasks\".\"scheduled_job_id\"=?", o.ID),
	)

	return ExternalTasks(queryMods...)
}

// LoadTarget allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (scheduledJobL) LoadTarget(ctx context.Context, e boil.ContextExecutor, singular bool, maybeScheduledJob any, mods queries.Applicator) error {
	var slice []*ScheduledJob
	var object *ScheduledJob

	if singular {
		var ok bool
		object, ok = maybeScheduledJob.(*ScheduledJob)
		if !ok {
			object = new(ScheduledJob)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeScheduledJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeScheduledJob))
			}
		}
	} else {
		s, ok := maybeScheduledJob.(*[]*ScheduledJob)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeScheduledJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeScheduledJob))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &scheduledJobR{}
		}
		if !queries.IsNil(object.TargetID) {
			args[object.TargetID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &scheduledJobR{}
			}

			if !queries.IsNil(obj.TargetID) {
				args[obj.TargetID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.crawl_targets`),
		qm.WhereIn(`ingest.crawl_targets.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load CrawlTarget")
	}

	var resultSlice []*CrawlTarget
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice CrawlTarget")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for crawl_targets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for crawl_targets")
	}

	if len(crawlTargetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Target = foreign
		if foreign.R == nil {
			foreign.R = &crawlTargetR{}
		}
		foreign.R.TargetScheduledJobs = append(foreign.R.TargetScheduledJobs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.TargetID, foreign.ID) {
				local.R.Target = foreign
				if foreign.R == nil {
					foreign.R = &crawlTargetR{}
				}
				foreign.R.TargetScheduledJobs = append(foreign.R.TargetScheduledJobs, local)
				break
			}
		}
	}

	return nil
}

// LoadSource allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (scheduledJobL) LoadSource(ctx context.Context, e boil.ContextExecutor, singular bool, maybeScheduledJob any, mods queries.Applicator) error {
	var slice []*ScheduledJob
	var object *ScheduledJob

	if singular {
		var ok bool
		object, ok = maybeScheduledJob.(*ScheduledJob)
		if !ok {
			object = new(ScheduledJob)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeScheduledJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeScheduledJob))
			}
		}
	} else {
		s, ok := maybeScheduledJob.(*[]*ScheduledJob)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeScheduledJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeScheduledJob))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &scheduledJobR{}
		}
		args[object.SourceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &scheduledJobR{}
			}

			args[obj.SourceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.data_sources`),
		qm.WhereIn(`ingest.data_sources.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`ingest.data_sources.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataSource")
	}

	var resultSlice []*DataSource
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataSource")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_sources")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_sources")
	}

	if len(dataSourceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Source = foreign
		if foreign.R == nil {
			foreign.R = &dataSourceR{}
		}
		foreign.R.SourceScheduledJobs = append(foreign.R.SourceScheduledJobs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SourceID == foreign.ID {
				local.R.Source = foreign
				if foreign.R == nil {
					foreign.R = &dataSourceR{}
				}
				foreign.R.SourceScheduledJobs = append(foreign.R.SourceScheduledJobs, local)
				break
			}
		}
	}

	return nil
}

// LoadExternalTasks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (scheduledJobL) LoadExternalTasks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeScheduledJob any, mods queries.Applicator) error {
	var slice []*ScheduledJob
	var object *ScheduledJob

	if singular {
		var ok bool
		object, ok = maybeScheduledJob.(*ScheduledJob)
		if !ok {
			object = new(ScheduledJob)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeScheduledJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeScheduledJob))
			}
		}
	} else {
		s, ok := maybeScheduledJob.(*[]*ScheduledJob)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeScheduledJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeScheduledJob))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &scheduledJobR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &scheduledJobR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ingest.external_tasks`),
		qm.WhereIn(`ingest.external_tasks.scheduled_job_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load external_tasks")
	}

	var resultSlice []*ExternalTask
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice external_tasks")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on external_tasks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for external_tasks")
	}

	if len(externalTaskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ExternalTasks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &externalTaskR{}
			}
			foreign.R.ScheduledJob = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ScheduledJobID) {
				local.R.ExternalTasks = append(local.R.ExternalTasks, foreign)
				if foreign.R == nil {
					foreign.R = &externalTaskR{}
				}
				foreign.R.ScheduledJob = local
				break
			}
		}
	}

	return nil
}

// SetTarget of the scheduledJob to the related item.
// Sets o.R.Target to related.
// Adds o to related.R.TargetScheduledJobs.
func (o *ScheduledJob) SetTarget(ctx context.Context, exec boil.ContextExecutor, insert bool, related *CrawlTarget) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ingest\".\"scheduled_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"target_id"}),
		strmangle.WhereClause("\"", "\"", 2, scheduledJobPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.TargetID, related.ID)
	if o.R == nil {
		o.R = &scheduledJobR{
			Target: related,
		}
	} else {
		o.R.Target = related
	}

	if related.R == nil {
		related.R = &crawlTargetR{
			TargetScheduledJobs: ScheduledJobSlice{o},
		}
	} else {
		related.R.TargetScheduledJobs = append(related.R.TargetScheduledJobs, o)
	}

	return nil
}

// RemoveTarget relationship.
// Sets o.R.Target to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ScheduledJob) RemoveTarget(ctx context.Context, exec boil.ContextExecutor, related *CrawlTarget) error {
	var err error

	queries.SetScanner(&o.TargetID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("target_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Target = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.TargetScheduledJobs {
		if queries.Equal(o.TargetID, ri.TargetID) {
			continue
		}

		ln := len(related.R.TargetScheduledJobs)
		if ln > 1 && i < ln-1 {
			related.R.TargetScheduledJobs[i] = related.R.TargetScheduledJobs[ln-1]
		}
		related.R.TargetScheduledJobs = related.R.TargetScheduledJobs[:ln-1]
		break
	}
	return nil
}

// SetSource of the scheduledJob to the related item.
// Sets o.R.Source to related.
// Adds o to related.R.SourceScheduledJobs.
func (o *ScheduledJob) SetSource(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataSource) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ingest\".\"scheduled_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"source_id"}),
		strmangle.WhereClause("\"", "\"", 2, scheduledJobPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SourceID = related.ID
	if o.R == nil {
		o.R = &scheduledJobR{
			Source: related,
		}
	} else {
		o.R.Source = related
	}

	if related.R == nil {
		related.R = &dataSourceR{
			SourceScheduledJobs: ScheduledJobSlice{o},
		}
	} else {
		related.R.SourceScheduledJobs = append(related.R.SourceScheduledJobs, o)
	}

	return nil
}

// AddExternalTasks adds the given related objects to the existing relationships
// of the scheduled_job, optionally inserting them as new records.
// Appends related to o.R.ExternalTasks.
// Sets related.R.ScheduledJob appropriately.
func (o *ScheduledJob) AddExternalTasks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ExternalTask) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ScheduledJobID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ingest\".\"external_tasks\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"scheduled_job_id"}),
				strmangle.WhereClause("\"", "\"", 2, externalTaskPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ScheduledJobID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &scheduledJobR{
			ExternalTasks: related,
		}
	} else {
		o.R.ExternalTasks = append(o.R.ExternalTasks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &externalTaskR{
				ScheduledJob: o,
			}
		} else {
			rel.R.ScheduledJob = o
		}
	}
	return nil
}

// SetExternalTasks removes all previously related items of the
// scheduled_job replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ScheduledJob's ExternalTasks accordingly.
// Replaces o.R.ExternalTasks with related.
// Sets related.R.ScheduledJob's ExternalTasks accordingly.
func (o *ScheduledJob) SetExternalTasks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ExternalTask) error {
	query := "update \"ingest\".\"external_tasks\" set \"scheduled_job_id\" = null where \"scheduled_job_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ExternalTasks {
			queries.SetScanner(&rel.ScheduledJobID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.ScheduledJob = nil
		}
		o.R.ExternalTasks = nil
	}

	return o.AddExternalTasks(ctx, exec, insert, related...)
}

// RemoveExternalTasks relationships from objects passed in.
// Removes related items from R.ExternalTasks (uses pointer comparison, removal does not keep order)
// Sets related.R.ScheduledJob.
func (o *ScheduledJob) RemoveExternalTasks(ctx context.Context, exec boil.ContextExecutor, related ...*ExternalTask) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ScheduledJobID, nil)
		if rel.R != nil {
			rel.R.ScheduledJob = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("scheduled_job_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ExternalTasks {
			if rel != ri {
				continue
			}

			ln := len(o.R.ExternalTasks)
			if ln > 1 && i < ln-1 {
				o.R.ExternalTasks[i] = o.R.ExternalTasks[ln-1]
			}
			o.R.ExternalTasks = o.R.ExternalTasks[:ln-1]
			break
		}
	}

	return nil
}

// ScheduledJobs retrieves all the records using an executor.
func ScheduledJobs(mods ...qm.QueryMod) scheduledJobQuery {
	mods = append(mods, qm.From("\"ingest\".\"scheduled_jobs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ingest\".\"scheduled_jobs\".*"})
	}

	return scheduledJobQuery{q}
}

// FindScheduledJob retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindScheduledJob(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ScheduledJob, error) {
	scheduledJobObj := &ScheduledJob{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ingest\".\"scheduled_jobs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, scheduledJobObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from scheduled_jobs")
	}

	if err = scheduledJobObj.doAfterSelectHooks(ctx, exec); err != nil {
		return scheduledJobObj, err
	}

	return scheduledJobObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ScheduledJob) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no scheduled_jobs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scheduledJobColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	scheduledJobInsertCacheMut.RLock()
	cache, cached := scheduledJobInsertCache[key]
	scheduledJobInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			scheduledJobAllColumns,
			scheduledJobColumnsWithDefault,
			scheduledJobColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(scheduledJobType, scheduledJobMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(scheduledJobType, scheduledJobMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ingest\".\"scheduled_jobs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ingest\".\"scheduled_jobs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into scheduled_jobs")
	}

	if !cached {
		scheduledJobInsertCacheMut.Lock()
		scheduledJobInsertCache[key] = cache
		scheduledJobInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ScheduledJob.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ScheduledJob) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	scheduledJobUpdateCacheMut.RLock()
	cache, cached := scheduledJobUpdateCache[key]
	scheduledJobUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			scheduledJobAllColumns,
			scheduledJobPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update scheduled_jobs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ingest\".\"scheduled_jobs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, scheduledJobPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(scheduledJobType, scheduledJobMapping, append(wl, scheduledJobPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update scheduled_jobs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for scheduled_jobs")
	}

	if !cached {
		scheduledJobUpdateCacheMut.Lock()
		scheduledJobUpdateCache[key] = cache
		scheduledJobUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q scheduledJobQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for scheduled_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for scheduled_jobs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ScheduledJobSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduledJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ingest\".\"scheduled_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, scheduledJobPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in scheduledJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all scheduledJob")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ScheduledJob) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no scheduled_jobs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scheduledJobColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	scheduledJobUpsertCacheMut.RLock()
	cache, cached := scheduledJobUpsertCache[key]
	scheduledJobUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			scheduledJobAllColumns,
			scheduledJobColumnsWithDefault,
			scheduledJobColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			scheduledJobAllColumns,
			scheduledJobPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert scheduled_jobs, could not build update column list")
		}

		ret := strmangle.SetComplement(scheduledJobAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(scheduledJobPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert scheduled_jobs, could not build conflict column list")
			}

			conflict = make([]string, len(scheduledJobPrimaryKeyColumns))
			copy(conflict, scheduledJobPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ingest\".\"scheduled_jobs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(scheduledJobType, scheduledJobMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(scheduledJobType, scheduledJobMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert scheduled_jobs")
	}

	if !cached {
		scheduledJobUpsertCacheMut.Lock()
		scheduledJobUpsertCache[key] = cache
		scheduledJobUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ScheduledJob record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ScheduledJob) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no ScheduledJob provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), scheduledJobPrimaryKeyMapping)
	sql := "DELETE FROM \"ingest\".\"scheduled_jobs\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from scheduled_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for scheduled_jobs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q scheduledJobQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no scheduledJobQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from scheduled_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for scheduled_jobs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ScheduledJobSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(scheduledJobBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduledJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ingest\".\"scheduled_jobs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scheduledJobPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from scheduledJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for scheduled_jobs")
	}

	if len(scheduledJobAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ScheduledJob) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindScheduledJob(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ScheduledJobSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ScheduledJobSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduledJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ingest\".\"scheduled_jobs\".* FROM \"ingest\".\"scheduled_jobs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scheduledJobPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in ScheduledJobSlice")
	}

	*o = slice

	return nil
}

// ScheduledJobExists checks if the ScheduledJob row exists.
func ScheduledJobExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ingest\".\"scheduled_jobs\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if scheduled_jobs exists")
	}

	return exists, nil
}

// Exists checks if the ScheduledJob row exists.
func (o *ScheduledJob) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ScheduledJobExists(ctx, exec, o.ID)
}
