apiVersion: v1
kind: ConfigMap
metadata:
  name: smap-ingest-config
  namespace: smap
data:
  HOST: "0.0.0.0"
  APP_PORT: "8080"
  API_MODE: "release"
  ENV: "development"
  LOGGER_LEVEL: "info"
  LOGGER_MODE: "production"
  LOGGER_ENCODING: "json"
  LOGGER_COLOR_ENABLED: "false"
