apiVersion: v1
kind: Secret
metadata:
  name: ingest-secrets
  namespace: smap
  labels:
    app: ingest-api
type: Opaque
stringData:
  # PostgreSQL Configuration
  POSTGRES_USER: "ingest_prod"
  POSTGRES_PASSWORD: "ingest_prod_pwd"

  # Redis Configuration
  REDIS_PASSWORD: "21042004"

  # MinIO Configuration
  MINIO_ACCESS_KEY: "tantai"
  MINIO_SECRET_KEY: "21042004"

  # RabbitMQ Configuration
  RABBITMQ_URL: "amqp://admin:21042004@172.16.21.206:5672/"

  # JWT Configuration
  JWT_SECRET_KEY: "smap-jwt-secret-2026-5cbPq8ZNywUafL3mX2r7HDqE1vS9kC4b0MRgx6VtYzQJKpLn"

  # Encrypter Configuration
  ENCRYPTER_KEY: "smap-encrypt-key-32-chars-2026!!"

  # Internal Configuration
  INTERNAL_INTERNAL_KEY: "smap-internal-key-2026-Yz7Fp4QvBmC9R2Ld"
